### ISSUE TITLE
[FR] - Add era, epoch, slot to cardano-cli query tip 

### ISSUE THREAD

**Issue by papacarp** [input-output-hk/cardano-node#1463] opened 2020-07-14 20:53 UTC
**External**

**Describe the feature you'd like**
For a chain with multiple era's the exact epoch and slot (within the epoch) becomes a confusing calculation.  Cardano-cli currently returns only `slotNo` which, prior to 15.1, was straightforward to calculate into an epoch.  However, with the byron era included we need to offset this by knowing the slots/epoch of all previous era's and when those era transitions occurred.  I've included a sample calculation below just for posterity Martin put together.

*Assuming the detailed calculation already exists in cardano-node for other reasons*, I'd like to ask that its exposed in the ` cardano-cli shelley query tip` api call.

IE, change the response from:
```
{
    "blockNo": 21029,
    "headerHash": "30eab5d9de331f0149859dbc31f8432ea864c9617d656d7a1d1c580a95be4863",
    "slotNo": 399960
}
```
to
```
{
    "blockNo": 21029,
    "headerHash": "30eab5d9de331f0149859dbc31f8432ea864c9617d656d7a1d1c580a95be4863",
    "slotNo": 399960,    
    "epoch":XX,
    "slot":XXXX,
    "era":"shelley"
}
```

**Describe alternatives you've considered**
We can still calculate it.  and ultimately may just end up with hard coded constants (or calculations) if it is decided to not add it to the cli.  I just feel to fulfill the desire of this command (return absolute state of the most recent block) the era, slot, epoch completes the data set.

**Additional context / screenshots**
Example calculation script for current epoch/slot (just for reference) from @gitmachtl  
```
#!/bin/bash

genesisfile="./mainnet_candidate-shelley-genesis.json"
genesisfile_byron="./mainnet_candidate-byron-genesis.json"

# Calculations from Genesis Values
slotLength=$(cat ${genesisfile} | jq -r .slotLength) #In Secs
epochLength=$(cat ${genesisfile} | jq -r .epochLength) #In Secs
slotsPerKESPeriod=$(cat ${genesisfile} | jq -r .slotsPerKESPeriod) #Number
startTimeByron=$(cat ${genesisfile_byron} | jq -r .startTime) #In Secs(abs)
#startTimeByron=1506203091 #RealValue MainNet
startTimeGenesis=$(cat ${genesisfile} | jq -r .systemStart) #In Text
startTimeSec=$(date --date=${startTimeGenesis} +%s) #In Secs(abs)
transTimeEnd=$(( ${startTimeSec}+(2*${epochLength}) )) #In Secs(abs) End of the transPhase(2 Epochs)
slotsPerKESPeriod=$(cat ${genesisfile} | jq -r .slotsPerKESPeriod)
byronSlots=$(( (${startTimeSec}-${startTimeByron}) / 20 )) #NumSlots ByronStart to ShelleyGenStart
transSlots=$(( (2*${epochLength}) / 20 )) #NumSlots in the TransitionPhase(2 Epochs)

get_referenceSlot()
{
local currentTimeSec=$(date -u +%s) #in seconds (UTC)
#Calculate current slot
if [[ "${currentTimeSec}" -lt "${transTimeEnd}" ]];
        then #In Transistion Phase between ShelleyGenesisStart and TransitionEnd
        local currentSlot=$(( ${byronSlots} + (${currentTimeSec}-${startTimeSec}) / 20 ))
        else #After Transition Phase
        local currentSlot=$(( ${byronSlots} + ${transSlots} + ((${currentTimeSec}-${transTimeEnd}) / ${slotLength}) ))
fi
echo ${currentSlot}
}

get_currentKESPeriod()
{
local currentKES=$(( (${currentTimeSec}-${transTimeEnd}) / (${slotsPerKESPeriod}*${slotLength}) ))
if [[ "${currentKES}" -lt 0 ]]; then currentKES=0; fi
echo ${currentKES}
}

#Current Reference Slot
referenceSlot=$(get_referenceSlot)
echo "Reference Slot#: ${referenceSlot}"

#Current KES Period
currentKESPeriod=$(get_currentKESPeriod)
echo "Current KES Period: ${currentKESPeriod}"
```

**Comment by disassembler** [comment] 2020-07-19 00:06
This would help my team as well @kevinhammond would be good to prioritize for next week

**Comment by mark-stopka** [comment] 2020-07-19 09:13
Should't this all be part of `cardano-cli get-tip`? It looks kind of funny to run `cardano-cli shelley query tip` and receive `"era":"byron"`, `get-tip` / `query tip` IMO should not be part of the `shelley` subsystem CLI...

**Comment by mrBliss** [comment] 2020-07-19 09:55
Implementation suggestion: get an [`Interpreter`](https://github.com/input-output-hk/ouroboros-network/blob/fb473dca5880893d6070db2e2efc80d483ca930d/ouroboros-consensus/src/Ouroboros/Consensus/HardFork/History/Qry.hs#L286) via the `LocalStateQuery` protocol via the [`CompatHardFork`](https://github.com/input-output-hk/ouroboros-network/blob/fb473dca5880893d6070db2e2efc80d483ca930d/ouroboros-consensus/src/Ouroboros/Consensus/HardFork/Combinator/Compat.hs#L51) [`GetInterpreter`](https://github.com/input-output-hk/ouroboros-network/blob/fb473dca5880893d6070db2e2efc80d483ca930d/ouroboros-consensus/src/Ouroboros/Consensus/HardFork/Combinator/Ledger/Query.hs#L275) query (see [`forwardCompatQuery`](https://github.com/input-output-hk/ouroboros-network/blob/fb473dca5880893d6070db2e2efc80d483ca930d/ouroboros-consensus/src/Ouroboros/Consensus/HardFork/Combinator/Compat.hs#L84) and [`singleEraCompatQuery`](https://github.com/input-output-hk/ouroboros-network/blob/fb473dca5880893d6070db2e2efc80d483ca930d/ouroboros-consensus/src/Ouroboros/Consensus/HardFork/Combinator/Compat.hs#L98)). That `Interpreter` can be used to answer conversion queries like: [`QAbsToRelEpoch`](https://github.com/input-output-hk/ouroboros-network/blob/fb473dca5880893d6070db2e2efc80d483ca930d/ouroboros-consensus/src/Ouroboros/Consensus/HardFork/History/Qry.hs#L140), [`QAbsToRelSlot`](https://github.com/input-output-hk/ouroboros-network/blob/fb473dca5880893d6070db2e2efc80d483ca930d/ouroboros-consensus/src/Ouroboros/Consensus/HardFork/History/Qry.hs#L139), and [`QAbsToRelTime`](https://github.com/input-output-hk/ouroboros-network/blob/fb473dca5880893d6070db2e2efc80d483ca930d/ouroboros-consensus/src/Ouroboros/Consensus/HardFork/History/Qry.hs#L138).

**Comment by erikd** [comment] 2020-08-15 04:38
I am currently syncing the chain while getting the current local chain tip is nice, it would also be nice to get an indication of whether the local node is still syncing the chain or following the global chain, maybe as a percentage. From by work with the history interpreter in `db-sync` this should not be too difficult.

**Comment by papacarp** [comment] 2020-09-03 15:40
We are now collecting the "at" times from the logs as well to look at global propagation delays.  IT would be wonderful if the "arrival" time of the block at the node was also available.

**Comment by vix-io** [comment] 2020-09-15 10:10
Duplicate of: https://github.com/input-output-hk/cardano-node/issues/1737 - closing

**Closed by vix-io** 2020-09-15 10:10 UTC
Labels: cli revision, enhancement
