### ISSUE TITLE
[BUG] - 1.34.1 cardano-cli query tip "MuxError (MuxIOException writev: resource vanished (Broken pipe))"

### ISSUE THREAD

**Issue by os11k** [input-output-hk/cardano-node#3684] opened 2022-03-05 13:39 UTC
*External*   otherwise.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
Using docker image on versions 1.34 & 1.34.1 "cardano-cli query tip" fails on relays

**Steps to reproduce**
1. Run Official IOHK docker image 1.34.1
2. Run "cardano-cli query tip"
3. See error:
```
bash-4.4# cardano-cli query tip --testnet-magic 1097911063
MuxError (MuxIOException writev: resource vanished (Broken pipe)) "(sendAll errored)"

cardano-cli: MuxIOException writev: resource vanished (Broken pipe) "(sendAll errored)"bash-4.4#
```

**Expected behavior**
Return:
```
{
    "era": "Alonzo",
    "syncProgress": "100.00",
    "hash": "d105ba87e98a5ff98ec482f79fdb958a22057660aa4bdc89a29546026b1630c6",
    "epoch": 190,
    "slot": 52118182,
    "block": 3370387
}
```

**System info (please complete the following information):**
- Official IOHK docker image 1.34.1
- Official IOHK docker image 1.34.1
- Node version (output of `cardano-node --version`):
```
cardano-node 1.34.1 - linux-x86_64 - ghc-8.10
git rev 73f9a746362695dc2cb63ba757fbcabb81733d23
```
- CLI version  (output of `cardano-cli --version`)
```
cardano-cli 1.34.1 - linux-x86_64 - ghc-8.10
git rev 73f9a746362695dc2cb63ba757fbcabb81733d23
```

If the git revision is reported to be `0000000000000000000000000000000000000000`, please use `cabal build` instead of `cabal install` to build the binaries because `cabal install` does not record the git revision in the binaries.

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by dorin100** [comment] 2022-03-06 17:53
are you running the `query tip` command in a loop? is this error always reproducible when running the command?

**Comment by os11k** [comment] 2022-03-06 21:14
Hi! It reproduces 100% with `"EnableP2P": true"` and respective `topology.json` file. Without p2p everything works as expected. So these is something to do with p2p settings.

**Comment by mkoura** [comment] 2022-03-07 09:20
See https://github.com/input-output-hk/cardano-node/issues/3568 and https://github.com/input-output-hk/cardano-node/issues/3659
It seems the issue is not resolved in 1.34.1 either, it is resolved only in master.

**Comment by cardanians** [comment] 2022-04-29 08:45
confirming, same issue with this version.
p2p OFF.

**Comment by os11k** [comment] 2022-05-15 18:15
Seems to be fixed on master, tested yesterday.

**Comment by os11k** [comment] 2022-05-21 08:33
I just tried `patch-cardano-ping-fix` tag and seems that is broken. It is 12+ hours it is not synced. First time I see such behavior on my relay.

**Comment by aidik** [comment] 2022-08-20 11:19
The same issue manifested on 1.35.3 with p2p enabled.

**Comment by Jimbo4350** [comment] 2022-10-27 08:47
Closing this. If this is still relevant please reopen.

**Comment by dorin100** [comment] 2022-10-27 08:49
this is still relevant in the latest release - 1.35.3

**Comment by os11k** [comment] 2022-10-27 08:53
I have no problem with 1.35.3:

```
{
    "block": 202385,
    "epoch": 29,
    "era": "Babbage",
    "hash": "9f8f0dafd376271168744e694cb227c37b9257d1f5039dd0271adc9e6bc60a5d",
    "slot": 11177535,
    "syncProgress": "100.00"
}
```

**Closed** 2022-10-27 08:56 UTC
Labels: bug, networking, comp: networking, comp: cardano-cli, area: p2p, release: 1.35.3, release: 1.34.1, comp: docker
