### ISSUE TITLE
[BUG] - 1.13.0: `cardano-api` doesn't prevent submission of transactions that would fail to deserialise

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#1280] opened 2020-06-15 19:59 UTC
**Internal**

**Summary**

`TxSignedShelley` transactions with `TxOut`'s containing negative `Coin` values are perfectly serialisable and transmissible using the `cardano-api` -- only to be failing to deserialise in a most cryptic manner:

```
ApiErrorCBOR (DecoderErrorDeserialiseFailure \"TxSigned\" (DeserialiseFailure 80 \"expected word\"))
```

This can be observed locally, by using a Tx with negative coin values and performing a ser/des roundtrip:  ` txSignedFromCBOR . txSignedToCBOR`.

A `Show`n transaction, as well as it's CBOR-ised forms are attached.

`cardano-api` commit id is exactly `1.13.0`: `9925ef37dccbe7f423f3ceb81a5e1da3d924393b`.

**Additional context**

- [TxSignedShelley.hs.txt](https://github.com/input-output-hk/cardano-node/files/4782656/TxSignedShelley.hs.txt)

- [TxSignedShelley.cbor.pretty.txt](https://github.com/input-output-hk/cardano-node/files/4782658/TxSignedShelley.cbor.pretty.txt)

- [TxSignedShelley.cbor.txt](https://github.com/input-output-hk/cardano-node/files/4782659/TxSignedShelley.cbor.txt)

**Comment by deepfire** [comment] 2020-06-15 20:00
[TxSignedShelley.hs.txt](https://github.com/input-output-hk/cardano-node/files/4782656/TxSignedShelley.hs.txt)

[TxSignedShelley.cbor.pretty.txt](https://github.com/input-output-hk/cardano-node/files/4782658/TxSignedShelley.cbor.pretty.txt)

[TxSignedShelley.cbor.txt](https://github.com/input-output-hk/cardano-node/files/4782659/TxSignedShelley.cbor.txt)

**Comment by deepfire** [comment] 2020-06-15 20:06
It could be that `Coin (-667666)` is the problem, as the decoder fails the negative `Coin` value, which happily passes the encoder.

**Comment by erikd** [comment] 2020-06-16 02:05
I think any attempt to encode a negative amount in a transaction should be rejected by the API as an error.

**Comment by dcoutts** [comment] 2020-06-17 12:18
We can do this validation step in the `cardano-api` tx construction, as part of the other sanity checks we have to do there (like Byron txs having the same number of witnesses as inputs).

**Comment by erikd** [comment] 2020-06-17 23:54
But doesn't that sanity check belong in `legder-specs` ?

**Comment by bergr01** [comment] 2020-06-22 00:15
{"at":"2020-06-21T23:36:38.53Z","env":"1.13.0:25efa","ns":["cardano.node.ChainDB"],"data":{"snapshot":{"snapshot":"DiskSnapshot 84","kind":"snapshot"},"kind":"TraceLedgerEvent.InvalidSnapshot","failure":"InitFailureRead (ReadFailed (DeserialiseFailure 334 \"An error occured while decoding Negative Coin.\\nError: -2970552586033663663\"))"},"app":[],"msg":"","pid":"21865","loc":null,"host":"myserver","sev":"Error","thread":"33"}
{"at":"2020-06-21T23:36:38.54Z","env":"1.13.0:25efa","ns":["cardano.node.ChainDB"],"data":{"snapshot":{"snapshot":"DiskSnapshot 83","kind":"snapshot"},"kind":"TraceLedgerEvent.InvalidSnapshot","failure":"InitFailureRead (ReadFailed (DeserialiseFailure 334 \"An error occured while decoding Negative Coin.\\nError: -2970247507364504374\"))"},"app":[],"msg":"","pid":"21865","loc":null,"host":"myserver","sev":"Error","thread":"33"}

Are the above errors related to/caused by this same issue?

**Comment by mrBliss** [comment] 2020-06-22 07:19
> {"at":"2020-06-21T23:36:38.53Z","env":"1.13.0:25efa","ns":["cardano.node.ChainDB"],"data":{"snapshot":{"snapshot":"DiskSnapshot 84","kind":"snapshot"},"kind":"TraceLedgerEvent.InvalidSnapshot","failure":"InitFailureRead (ReadFailed (DeserialiseFailure 334 "An error occured while decoding Negative Coin.\nError: -2970552586033663663"))"},"app":[],"msg":"","pid":"21865","loc":null,"host":"myserver","sev":"Error","thread":"33"}
> {"at":"2020-06-21T23:36:38.54Z","env":"1.13.0:25efa","ns":["cardano.node.ChainDB"],"data":{"snapshot":{"snapshot":"DiskSnapshot 83","kind":"snapshot"},"kind":"TraceLedgerEvent.InvalidSnapshot","failure":"InitFailureRead (ReadFailed (DeserialiseFailure 334 "An error occured while decoding Negative Coin.\nError: -2970247507364504374"))"},"app":[],"msg":"","pid":"21865","loc":null,"host":"myserver","sev":"Error","thread":"33"}
> 
> Are the above errors related to/caused by this same issue?

Indeed. (See https://github.com/input-output-hk/cardano-node/issues/1312#issuecomment-647329374)

**Comment by Jimbo4350** [comment] 2022-10-27 08:01
Closing this. If this is still relevant please re-open.

**Closed by Jimbo4350** 2022-10-27 08:01 UTC
Labels: enhancement, priority high, cli revision
