### ISSUE TITLE
[BUG] - cardano.node.DnsSubscription:Error

### ISSUE THREAD

**Issue by vae520283995** [input-output-hk/cardano-node#1715] opened 2020-08-18 04:13 UTC
**Internal/Exernal**
*External*

**Summary**
Unable to synchronize properly

**Steps to reproduce**
docker run latest
cardano-node-mainnet             inputoutput/cardano-node             latest        e8eb3a838c50   778 MB

**Expected behavior**
Normal synchronization

**System info (please complete the following information):**
- OS: Ubuntu
- Version 16.04.10
- Node version latest

**Screenshots and attachments**
cardano-node-mainnet             inputoutput/cardano-node             latest        e8eb3a838c50   778 MB

cardano-node-mainnet        | [4341dab7:cardano.node.ErrorPolicy:Notice:67] [2020-08-18 04:13:26.70 UTC] [String "ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = \"Parallel connection cancelled\", seStack = []}))) 1s",String "ErrorPolicyTrace",String "3.129.199.184:3001"]
cardano-node-mainnet        | [4341dab7:cardano.node.DnsSubscription:Error:3856] [2020-08-18 04:13:27.17 UTC] [String "Application Exception: 18.159.88.186:3001 HeaderError (At (Block {blockPointSlot = SlotNo {unSlotNo = 5789249}, blockPointHash = 68914f093daebff961def6df4830a21b2fffccec69442e8e6b780e51c40d5217})) (HeaderProtocolError (HardForkValidationErrFromEra S (Z (WrapValidationErr {unwrapValidationErr = ChainTransitionError [OverlayFailure (VRFLeaderValueTooBig (OutputVRF {getOutputVRFBytes = \"\\NUL\\NUL\\157\\185\\199\\189l\\210Y\\130\\175\\220\\248\\140\\242\\129\\&4!\\138\\193\\175\\235\\238c*h(\\\\\\187\\156Y3\\239\\204lYMF\\160\\239F.>S\\248\\193l\\CAN\\162\\181\\204\\147\\241\\EOT\\183\\182P{R`z\\200vM\"}) (0 % 1) (ActiveSlotCoeff {unActiveSlotVal = UnsafeUnitInterval (1 % 20), unActiveSlotLog = -512932943875505334261962382072846}))]})))) (Tip (SlotNo {unSlotNo = 5789244}) 9c925a40b21eb2768f2b07733568f7bd9dbfe74848f0b29755b9e8a230b4f43e (BlockNo {unBlockNo = 4555199})) (Tip (SlotNo {unSlotNo = 6157711}) 9bc99fa3047b1a4476e3bb061bfc04b7b217f83fa403d315cb257a3f146ff93f (BlockNo {unBlockNo = 4573383}))",String "SubscriptionTrace",String "\"relays-new.cardano-mainnet.iohk.io\""]
cardano-node-mainnet        | [4341dab7:cardano.node.ErrorPolicy:Warning:67] [2020-08-18 04:13:27.17 UTC] [String "ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (HeaderError (At (Block {blockPointSlot = SlotNo {unSlotNo = 5789249}, blockPointHash = 68914f093daebff961def6df4830a21b2fffccec69442e8e6b780e51c40d5217})) (HeaderProtocolError (HardForkValidationErrFromEra S (Z (WrapValidationErr {unwrapValidationErr = ChainTransitionError [OverlayFailure (VRFLeaderValueTooBig (OutputVRF {getOutputVRFBytes = \"\\NUL\\NUL\\157\\185\\199\\189l\\210Y\\130\\175\\220\\248\\140\\242\\129\\&4!\\138\\193\\175\\235\\238c*h(\\\\\\187\\156Y3\\239\\204lYMF\\160\\239F.>S\\248\\193l\\CAN\\162\\181\\204\\147\\241\\EOT\\183\\182P{R`z\\200vM\"}) (0 % 1) (ActiveSlotCoeff {unActiveSlotVal = UnsafeUnitInterval (1 % 20), unActiveSlotLog = -512932943875505334261962382072846}))]})))) (Tip (SlotNo {unSlotNo = 5789244}) 9c925a40b21eb2768f2b07733568f7bd9dbfe74848f0b29755b9e8a230b4f43e (BlockNo {unBlockNo = 4555199})) (Tip (SlotNo {unSlotNo = 6157711}) 9bc99fa3047b1a4476e3bb061bfc04b7b217f83fa403d315cb257a3f146ff93f (BlockNo {unBlockNo = 4573383}))))) 200s 200s",String "ErrorPolicyTrace",String "18.159.88.186:3001"]
cardano-node-mainnet        | [4341dab7:cardano.node.DnsSubscription:Error:3855] [2020-08-18 04:13:27.36 UTC] [String "Application Exception: 3.133.45.145:3001 HeaderError (At (Block {blockPointSlot = SlotNo {unSlotNo = 5789249}, blockPointHash = 68914f093daebff961def6df4830a21b2fffccec69442e8e6b780e51c40d5217})) (HeaderProtocolError (HardForkValidationErrFromEra S (Z (WrapValidationErr {unwrapValidationErr = ChainTransitionError [OverlayFailure (VRFLeaderValueTooBig (OutputVRF {getOutputVRFBytes = \"\\NUL\\NUL\\157\\185\\199\\189l\\210Y\\130\\175\\220\\248\\140\\242\\129\\&4!\\138\\193\\175\\235\\238c*h(\\\\\\187\\156Y3\\239\\204lYMF\\160\\239F.>S\\248\\193l\\CAN\\162\\181\\204\\147\\241\\EOT\\183\\182P{R`z\\200vM\"}) (0 % 1) (ActiveSlotCoeff {unActiveSlotVal = UnsafeUnitInterval (1 % 20), unActiveSlotLog = -512932943875505334261962382072846}))]})))) (Tip (SlotNo {unSlotNo = 5789244}) 9c925a40b21eb2768f2b07733568f7bd9dbfe74848f0b29755b9e8a230b4f43e (BlockNo {unBlockNo = 4555199})) (Tip (SlotNo {unSlotNo = 6157711}) 9bc99fa3047b1a4476e3bb061bfc04b7b217f83fa403d315cb257a3f146ff93f (BlockNo {unBlockNo = 4573383}))",String "SubscriptionTrace",String "\"relays-new.cardano-mainnet.iohk.io\""]
cardano-node-mainnet        | [4341dab7:cardano.node.ErrorPolicy:Warning:67] [2020-08-18 04:13:27.36 UTC] [String "ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (HeaderError (At (Block {blockPointSlot = SlotNo {unSlotNo = 5789249}, blockPointHash = 68914f093daebff961def6df4830a21b2fffccec69442e8e6b780e51c40d5217})) (HeaderProtocolError (HardForkValidationErrFromEra S (Z (WrapValidationErr {unwrapValidationErr = ChainTransitionError [OverlayFailure (VRFLeaderValueTooBig (OutputVRF {getOutputVRFBytes = \"\\NUL\\NUL\\157\\185\\199\\189l\\210Y\\130\\175\\220\\248\\140\\242\\129\\&4!\\138\\193\\175\\235\\238c*h(\\\\\\187\\156Y3\\239\\204lYMF\\160\\239F.>S\\248\\193l\\CAN\\162\\181\\204\\147\\241\\EOT\\183\\182P{R`z\\200vM\"}) (0 % 1) (ActiveSlotCoeff {unActiveSlotVal = UnsafeUnitInterval (1 % 20), unActiveSlotLog = -512932943875505334261962382072846}))]})))) (Tip (SlotNo {unSlotNo = 5789244}) 9c925a40b21eb2768f2b07733568f7bd9dbfe74848f0b29755b9e8a230b4f43e (BlockNo {unBlockNo = 4555199})) (Tip (SlotNo {unSlotNo = 6157711}) 9bc99fa3047b1a4476e3bb061bfc04b7b217f83fa403d315cb257a3f146ff93f (BlockNo {unBlockNo = 4573383}))))) 200s 200s",String "ErrorPolicyTrace",String "3.133.45.145:3001"]

**Comment by bmatthewshea** [comment] 2020-08-18 15:14
Same issue at same block.

`[cardanor:cardano.node.DnsSubscription:Error:170172] [2020-08-18 15:11:04.91 UTC] [String "Application Exception: 54.151.113.34:3001 HeaderError (At (Block {blockPointSlot = SlotNo {unSlotNo = 5789249}, blockPointHash = 68914f093daebff961def6df4830a21b2fffccec69442e8e6b780e51c40d5217})) (HeaderProtocolError (HardForkValidationErrFromEra S (Z (WrapValidationErr {unwrapValidationErr = ChainTransitionError [OverlayFailure (VRFLeaderValueTooBig (OutputVRF {getOutputVRFBytes = \"\\NUL\\NUL\\157\\185\\199\\189l\\210Y\\130\\175\\220\\248\\140\\242\\129\\&4!\\138\\193\\175\\235\\238c*h(\\\\\\187\\156Y3\\239\\204lYMF\\160\\239F.>S\\248\\193l\\CAN\\162\\181\\204\\147\\241\\EOT\\183\\182P{R`z\\200vM\"}) (0 % 1) (ActiveSlotCoeff {unActiveSlotVal = UnsafeUnitInterval (1 % 20), unActiveSlotLog = -512932943875505334261962382072846}))]})))) (Tip (SlotNo {unSlotNo = 5789044}) db29e1e0e9080c96bb41e78b119ffae1097192214c21a6f2d257fb98c8e80933 (BlockNo {unBlockNo = 4555190})) (Tip (SlotNo {unSlotNo = 6197155}) 8fa87b94d8c34ac6eaed669173306d74dc2467a4ed7694657157f7de6361aa51 (BlockNo {unBlockNo = 4575327}))",String "SubscriptionTrace",String "\"relays-new.cardano-mainnet.iohk.io\""]`

**Comment by mark-stopka** [comment] 2020-08-18 20:28
Known issue in `1.18.1`, downgrade to `1.18.0` or wait for `1.18.2` due for release this week...

https://github.com/input-output-hk/cardano-node/issues/1676

**Comment by rphair** [comment] 2020-08-19 10:01
We saw this issue today, probably on the basis of having run `1.18.1` for a while, even though we had downgraded to `1.18.0` a while ago.  I posted it there first without noticing that issue had been closed: https://github.com/input-output-hk/cardano-node/issues/1676#issuecomment-676064337

**Comment by cyber-russ** [comment] 2020-08-19 15:48
> We saw this issue today, probably on the basis of having run `1.18.1` for a day or so, even though we downgraded to `1.18.0` a while ago. I posted it here first without noticing that this issue has been closed: [#1676 (comment)](https://github.com/input-output-hk/cardano-node/issues/1676#issuecomment-676064337)
> 
> I haven't found any other way to resolve the problem, so as a last resort fix we are rebuilding the DB on all our nodes.

Saw the same issue. Required 'uncorrupted' DB to be copied from node that had only run 1.18.0.

**Comment by mrBliss** [comment] 2020-08-19 15:51
BTW, I think it's enough if you delete the `ledger` folder. This will require rebuilding the ledger from genesis, which will take a while (but this will be much faster with 1.19.0 than 1.18.0!). If you delete the entire database, including the `immutable` folder, you'll have to resync the whole chain, which takes much longer of course.

**Comment by kevinhammond** [comment] 2020-08-20 15:11
Closing since this relates to a rolled-back version (1.18.1).

**Closed by kevinhammond** 2020-08-20 15:11 UTC
Labels: bug

**Comment by arjun2364** [comment] 2021-02-20 10:03
same issue still in the 1.24.2

**Comment by mark-stopka** [comment] 2021-02-20 12:41
> same issue still in the 1.24.2

Current version is 1.25.1, can you confirm for that?

**Comment by arjun2364** [comment] 2021-02-21 04:18
Yes, I have created a new ubuntu server VM in azure. In which I am getting this error, I first tried with centOS and again did the whole process with the ubuntu server but still, the issue is coming. I have followed the exact steps given in the stake pool school course.
```
cardano-cli --version
cardano-cli 1.24.2 - linux-x86_64 - ghc-8.10
git rev 400d18092ce604352cf36fe5f105b0d7c78be074
```
`[Beast:cardano.node.DnsSubscription:Notice:139] [2021-02-21 04:13:55.44 UTC] [String "Connection Attempt Start, destination 52.74.88.13:3001",String "SubscriptionTrace",String "\"relays-new.cardano-testnet.iohkdev.io\""]
[Beast:cardano.node.DnsSubscription:Notice:140] [2021-02-21 04:13:55.47 UTC] [String "Connection Attempt Start, destination 54.250.11.33:3001",String "SubscriptionTrace",String "\"relays-new.cardano-testnet.iohkdev.io\""]
[Beast:cardano.node.DnsSubscription:Notice:135] [2021-02-21 04:13:55.48 UTC] [String "Connection Attempt End, destination 3.127.103.85:3001 outcome: ConnectSuccess",String "SubscriptionTrace",String "\"relays-new.cardano-testnet.iohkdev.io\""]
[Beast:cardano.node.DnsSubscription:Notice:136] [2021-02-21 04:13:55.48 UTC] [String "Connection Attempt End, destination 54.241.77.32:3001 outcome: ConnectSuccessLast",String "SubscriptionTrace",String "\"relays-new.cardano-testnet.iohkdev.io\""]
[Beast:cardano.node.ErrorPolicy:Notice:55] [2021-02-21 04:13:55.48 UTC] [String "ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = \"Parallel connection cancelled\", seStack = []}))) 1s",String "ErrorPolicyTrace",String "52.74.88.13:3001"]
[Beast:cardano.node.ErrorPolicy:Notice:55] [2021-02-21 04:13:55.48 UTC] [String "ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = \"Parallel connection cancelled\", seStack = []}))) 1s",String "ErrorPolicyTrace",String "54.250.11.33:3001"]
[Beast:cardano.node.DnsSubscription:Error:136] [2021-02-21 04:13:55.68 UTC] [String "Application Exception: 54.241.77.32:3001 InvalidBlock (At (Block {blockPointSlot = SlotNo 18023840, blockPointHash = c9881ce23d270f6b00369017015621e5735f029c8006e2077ab37c54dc7ef4d2})) (ValidationError (ExtValidationErrorLedger (HardForkLedgerErrorFromEra S (S (S (Z (WrapLedgerErr {unwrapLedgerErr = BBodyError (BlockTransitionError [LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (OutputTooSmallUTxO [(Addr Testnet (KeyHashObj (KeyHash \"53c493ab318b98d4bd5bfebee157f33a2c2dcf2752e818d558f8867d\")) (StakeRefBase (KeyHashObj (KeyHash \"54251fc51d128c9808585c95f66b0c5146dddf8fafe8dbf13de65774\"))),Value 1500000 (fromList [(PolicyID {policyID = ScriptHash \"9cebd568ac4ad908cdd2d45a52327fc4711911054c9951b90a603303\"},fromList [(\"BerryIndigo\",1)])]))]))))])})))))))",String "SubscriptionTrace",String "\"relays-new.cardano-testnet.iohkdev.io\""]
[Beast:cardano.node.ErrorPolicy:Warning:55] [2021-02-21 04:13:55.68 UTC] [String "ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (InvalidBlock (At (Block {blockPointSlot = SlotNo 18023840, blockPointHash = c9881ce23d270f6b00369017015621e5735f029c8006e2077ab37c54dc7ef4d2})) (ValidationError (ExtValidationErrorLedger (HardForkLedgerErrorFromEra S (S (S (Z (WrapLedgerErr {unwrapLedgerErr = BBodyError (BlockTransitionError [LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (OutputTooSmallUTxO [(Addr Testnet (KeyHashObj (KeyHash \"53c493ab318b98d4bd5bfebee157f33a2c2dcf2752e818d558f8867d\")) (StakeRefBase (KeyHashObj (KeyHash \"54251fc51d128c9808585c95f66b0c5146dddf8fafe8dbf13de65774\"))),Value 1500000 (fromList [(PolicyID {policyID = ScriptHash \"9cebd568ac4ad908cdd2d45a52327fc4711911054c9951b90a603303\"},fromList [(\"BerryIndigo\",1)])]))]))))])})))))))))) 200s 200s",String "ErrorPolicyTrace",String "54.241.77.32:3001"]
[Beast:cardano.node.DnsSubscription:Error:135] [2021-02-21 04:13:55.75 UTC] [String "Application Exception: 3.127.103.85:3001 InvalidBlock (At (Block {blockPointSlot = SlotNo 18023840, blockPointHash = c9881ce23d270f6b00369017015621e5735f029c8006e2077ab37c54dc7ef4d2})) (ValidationError (ExtValidationErrorLedger (HardForkLedgerErrorFromEra S (S (S (Z (WrapLedgerErr {unwrapLedgerErr = BBodyError (BlockTransitionError [LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (OutputTooSmallUTxO [(Addr Testnet (KeyHashObj (KeyHash \"53c493ab318b98d4bd5bfebee157f33a2c2dcf2752e818d558f8867d\")) (StakeRefBase (KeyHashObj (KeyHash \"54251fc51d128c9808585c95f66b0c5146dddf8fafe8dbf13de65774\"))),Value 1500000 (fromList [(PolicyID {policyID = ScriptHash \"9cebd568ac4ad908cdd2d45a52327fc4711911054c9951b90a603303\"},fromList [(\"BerryIndigo\",1)])]))]))))])})))))))",String "SubscriptionTrace",String "\"relays-new.cardano-testnet.iohkdev.io\""]
[Beast:cardano.node.ErrorPolicy:Warning:55] [2021-02-21 04:13:55.75 UTC] [String "ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (InvalidBlock (At (Block {blockPointSlot = SlotNo 18023840, blockPointHash = c9881ce23d270f6b00369017015621e5735f029c8006e2077ab37c54dc7ef4d2})) (ValidationError (ExtValidationErrorLedger (HardForkLedgerErrorFromEra S (S (S (Z (WrapLedgerErr {unwrapLedgerErr = BBodyError (BlockTransitionError [LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (OutputTooSmallUTxO [(Addr Testnet (KeyHashObj (KeyHash \"53c493ab318b98d4bd5bfebee157f33a2c2dcf2752e818d558f8867d\")) (StakeRefBase (KeyHashObj (KeyHash \"54251fc51d128c9808585c95f66b0c5146dddf8fafe8dbf13de65774\"))),Value 1500000 (fromList [(PolicyID {policyID = ScriptHash \"9cebd568ac4ad908cdd2d45a52327fc4711911054c9951b90a603303\"},fromList [(\"BerryIndigo\",1)])]))]))))])})))))))))) 200s 200s",String "ErrorPolicyTrace",String "3.127.103.85:3001"]`

And I am running this command with host-addr as 0.0.0.0 because when I am using my VM IP some directly gets shut down
```
cardano-node run \
 --topology testnet-topology.json \
 --database-path db \
 --socket-path db/node.socket \
 --host-addr 0.0.0.0 \
 --port 3001 \
 --config testnet-config.json
```

**Comment by chrisviboar** [comment] 2021-03-10 00:35
> BTW, I think it's enough if you delete the `ledger` folder. This will require rebuilding the ledger from genesis, which will take a while (but this will be much faster with 1.19.0 than 1.18.0!). If you delete the entire database, including the `immutable` folder, you'll have to resync the whole chain, which takes much longer of course.

It worked out by deleting the ledger folder
https://github.com/input-output-hk/cardano-node/issues/1715#issuecomment-782794167

**Comment by chrisviboar** [comment] 2021-03-10 00:37
> Yes, I have created a new ubuntu server VM in azure. In which I am getting this error, I first tried with centOS and again did the whole process with the ubuntu server but still, the issue is coming. I have followed the exact steps given in the stake pool school course.
> 
> ```
> cardano-cli --version
> cardano-cli 1.24.2 - linux-x86_64 - ghc-8.10
> git rev 400d18092ce604352cf36fe5f105b0d7c78be074
> ```
> 
> `[Beast:cardano.node.DnsSubscription:Notice:139] [2021-02-21 04:13:55.44 UTC] [String "Connection Attempt Start, destination 52.74.88.13:3001",String "SubscriptionTrace",String "\"relays-new.cardano-testnet.iohkdev.io\""] [Beast:cardano.node.DnsSubscription:Notice:140] [2021-02-21 04:13:55.47 UTC] [String "Connection Attempt Start, destination 54.250.11.33:3001",String "SubscriptionTrace",String "\"relays-new.cardano-testnet.iohkdev.io\""] [Beast:cardano.node.DnsSubscription:Notice:135] [2021-02-21 04:13:55.48 UTC] [String "Connection Attempt End, destination 3.127.103.85:3001 outcome: ConnectSuccess",String "SubscriptionTrace",String "\"relays-new.cardano-testnet.iohkdev.io\""] [Beast:cardano.node.DnsSubscription:Notice:136] [2021-02-21 04:13:55.48 UTC] [String "Connection Attempt End, destination 54.241.77.32:3001 outcome: ConnectSuccessLast",String "SubscriptionTrace",String "\"relays-new.cardano-testnet.iohkdev.io\""] [Beast:cardano.node.ErrorPolicy:Notice:55] [2021-02-21 04:13:55.48 UTC] [String "ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = \"Parallel connection cancelled\", seStack = []}))) 1s",String "ErrorPolicyTrace",String "52.74.88.13:3001"] [Beast:cardano.node.ErrorPolicy:Notice:55] [2021-02-21 04:13:55.48 UTC] [String "ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = \"Parallel connection cancelled\", seStack = []}))) 1s",String "ErrorPolicyTrace",String "54.250.11.33:3001"] [Beast:cardano.node.DnsSubscription:Error:136] [2021-02-21 04:13:55.68 UTC] [String "Application Exception: 54.241.77.32:3001 InvalidBlock (At (Block {blockPointSlot = SlotNo 18023840, blockPointHash = c9881ce23d270f6b00369017015621e5735f029c8006e2077ab37c54dc7ef4d2})) (ValidationError (ExtValidationErrorLedger (HardForkLedgerErrorFromEra S (S (S (Z (WrapLedgerErr {unwrapLedgerErr = BBodyError (BlockTransitionError [LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (OutputTooSmallUTxO [(Addr Testnet (KeyHashObj (KeyHash \"53c493ab318b98d4bd5bfebee157f33a2c2dcf2752e818d558f8867d\")) (StakeRefBase (KeyHashObj (KeyHash \"54251fc51d128c9808585c95f66b0c5146dddf8fafe8dbf13de65774\"))),Value 1500000 (fromList [(PolicyID {policyID = ScriptHash \"9cebd568ac4ad908cdd2d45a52327fc4711911054c9951b90a603303\"},fromList [(\"BerryIndigo\",1)])]))]))))])})))))))",String "SubscriptionTrace",String "\"relays-new.cardano-testnet.iohkdev.io\""] [Beast:cardano.node.ErrorPolicy:Warning:55] [2021-02-21 04:13:55.68 UTC] [String "ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (InvalidBlock (At (Block {blockPointSlot = SlotNo 18023840, blockPointHash = c9881ce23d270f6b00369017015621e5735f029c8006e2077ab37c54dc7ef4d2})) (ValidationError (ExtValidationErrorLedger (HardForkLedgerErrorFromEra S (S (S (Z (WrapLedgerErr {unwrapLedgerErr = BBodyError (BlockTransitionError [LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (OutputTooSmallUTxO [(Addr Testnet (KeyHashObj (KeyHash \"53c493ab318b98d4bd5bfebee157f33a2c2dcf2752e818d558f8867d\")) (StakeRefBase (KeyHashObj (KeyHash \"54251fc51d128c9808585c95f66b0c5146dddf8fafe8dbf13de65774\"))),Value 1500000 (fromList [(PolicyID {policyID = ScriptHash \"9cebd568ac4ad908cdd2d45a52327fc4711911054c9951b90a603303\"},fromList [(\"BerryIndigo\",1)])]))]))))])})))))))))) 200s 200s",String "ErrorPolicyTrace",String "54.241.77.32:3001"] [Beast:cardano.node.DnsSubscription:Error:135] [2021-02-21 04:13:55.75 UTC] [String "Application Exception: 3.127.103.85:3001 InvalidBlock (At (Block {blockPointSlot = SlotNo 18023840, blockPointHash = c9881ce23d270f6b00369017015621e5735f029c8006e2077ab37c54dc7ef4d2})) (ValidationError (ExtValidationErrorLedger (HardForkLedgerErrorFromEra S (S (S (Z (WrapLedgerErr {unwrapLedgerErr = BBodyError (BlockTransitionError [LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (OutputTooSmallUTxO [(Addr Testnet (KeyHashObj (KeyHash \"53c493ab318b98d4bd5bfebee157f33a2c2dcf2752e818d558f8867d\")) (StakeRefBase (KeyHashObj (KeyHash \"54251fc51d128c9808585c95f66b0c5146dddf8fafe8dbf13de65774\"))),Value 1500000 (fromList [(PolicyID {policyID = ScriptHash \"9cebd568ac4ad908cdd2d45a52327fc4711911054c9951b90a603303\"},fromList [(\"BerryIndigo\",1)])]))]))))])})))))))",String "SubscriptionTrace",String "\"relays-new.cardano-testnet.iohkdev.io\""] [Beast:cardano.node.ErrorPolicy:Warning:55] [2021-02-21 04:13:55.75 UTC] [String "ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (InvalidBlock (At (Block {blockPointSlot = SlotNo 18023840, blockPointHash = c9881ce23d270f6b00369017015621e5735f029c8006e2077ab37c54dc7ef4d2})) (ValidationError (ExtValidationErrorLedger (HardForkLedgerErrorFromEra S (S (S (Z (WrapLedgerErr {unwrapLedgerErr = BBodyError (BlockTransitionError [LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (OutputTooSmallUTxO [(Addr Testnet (KeyHashObj (KeyHash \"53c493ab318b98d4bd5bfebee157f33a2c2dcf2752e818d558f8867d\")) (StakeRefBase (KeyHashObj (KeyHash \"54251fc51d128c9808585c95f66b0c5146dddf8fafe8dbf13de65774\"))),Value 1500000 (fromList [(PolicyID {policyID = ScriptHash \"9cebd568ac4ad908cdd2d45a52327fc4711911054c9951b90a603303\"},fromList [(\"BerryIndigo\",1)])]))]))))])})))))))))) 200s 200s",String "ErrorPolicyTrace",String "3.127.103.85:3001"]`
> 
> And I am running this command with host-addr as 0.0.0.0
> 
> ```
> cardano-node run \
>  --topology testnet-topology.json \
>  --database-path db \
>  --socket-path db/node.socket \
>  --host-addr 0.0.0.0 \
>  --port 3001 \
>  --config testnet-config.json
> ```
> 
> When I use my VM IP in host-addr this error comes
> 
> ```
> [Beast:cardano.node.DnsSubscription:Notice:63] [2021-02-21 04:16:36.77 UTC] [String "Connection Attempt Start, destination 3.129.133.68:3001",String "SubscriptionTrace",String "\"relays-new.cardano-testnet.iohkdev.io\""]
> [Beast:cardano.node.ChainDB:Info:5] [2021-02-21 04:16:36.77 UTC] Closed db with immutable tip at 5a6aebd494d8868440d2a5a44c8e928db7ed7b7dffecfd5bb1281cf9d639568c at slot 17962495 and tip aef965e0a82c1103e78454cfc6153996410126aa826176a3a16bb38d729d9f27 at slot 18023833
> 
> Shutting down..
> ```
https://github.com/input-output-hk/cardano-node/issues/1715#issuecomment-676509360

**Comment by chrisviboar** [comment] 2021-03-12 20:35
Same issue here.
I have the same versions and running under the same configurations and still having that issue. 
Please update the curse guide, it makes no sense that most of the configurations you give us are either wrong or obsolete.

**Comment by SmolPadok** [comment] 2021-09-06 18:53
> Please update the curse guide, it makes no sense that most of the configurations you give us are either wrong or obsolete.

This is a little out of the blue, but can agree, the documentation needs to be updated. Facing the same Dnssubscription error when I followed the documentation. I tried upgrading my cardano node to 1.29.0 and used the config files of that version, and the problems dissappeared.

**Comment by lucasvirus** [comment] 2021-11-10 00:53
> > Obtendo um `cardano.node.DnsSubscription:Error`nó cardano 1.29.0 Linux. A cadeia não está mais sincronizando, travada em "syncProgress": "99,78". Alguma ideia do que está causando isso?
> > Também há um aviso `cardano.node.ErrorPolicy:Warning`ErrorPolicySuspendPeer etc.
> 
> Você precisa atualizar para 1.30.1 para suportar Alonzo hard-fork ...

Good night, could you teach us how to accomplish this?
