### ISSUE TITLE
Unexpected costs of Babbage: journal of investigation

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#4213] opened 2022-07-21 22:11 UTC
@jutaro has discovered some interesting profiles results, attributing a non-trivial amount of to the SOP library.

**Comment by jutaro** [comment] 2022-08-30 08:24
From the task to profile the new tracing system arises the interest and meaningfulness to use profiling tools to get an overview of the performace bottelnecks for the benchmarking team.

**Comment by jutaro** [comment] 2022-08-30 08:46
The first problem to solve is to get all tools ready to profile a running node. This is much simplified with the workbench, which has profiling options available. For this profiling we use the chainsync-early-byron local cluster run of the workbench, which is used normally for benchmarking. It starts two nodes and runs about a minute. 
So to get a profile run it is as easy as:
1. modify:
`cardano-node/nix/workbench/lib-cabal.sh` line 11 to
`export WB_RTSARGS=${WB_PROFILED:+-p} `  The -p option is a ghc runtime flag, which produces a standard time profile report. It is written into the file *.prof
2. start the nix workbench in the node folder with `
make chainsync-early-byron-prof`. The -prof in the end will make a build with all libraries and the executables comiled for profiling.
3. execute `start-cluster` and you find the .prof files in the node1 and node0 directories under the run directory.

**Comment by jutaro** [comment] 2022-08-30 09:13
The second task is about tooling as well. To get meaningful results we need to be able to instrument the code. E.g. with individual cost centers or with inlining. In our case this source modification does not only happen in the node repository but as well in dependend libraries like `ouroboros-network` and even dependend libraries of dependend libraries like `generics-sop/sop-core`.
The best way to solve this is with is the [Dependency localisation -or- Cabal&Nix for painless cross-repository work](https://github.com/input-output-hk/cardano-node#id35) method.

**Comment by jutaro** [comment] 2022-08-31 14:46
If we edit sop-core and inline the SOP functions visible in this profile with:
{-# INLINE hcliftA #-}
{-# INLINE hliftA #-}
{-# INLINE hcmap #-}
{-# INLINE hmap #-}
{-# INLINE sList #-}
{-# INLINE fn #-}

**Comment by jutaro** [comment] 2022-09-08 11:50
If we go further into anchorFromBlock, which is top of the list, we see that it calls getHeaderFields and constructs a HeaderField data structure from it. getHeaderFields is a class method of class HasHeader. If we add SCCs to the different instances, we see that ```
instance CanHardFork xs => HasHeader (Header (HardForkBlock xs))
` is the costly entry ad appears alone on top.
```SCCHardFork2HeaderFields                         Ouroboros.Consensus.HardFork.Combinator.Block                               src/Ouroboros/Consensus/HardFork/Combinator/Block.hs:87:60-75                                                                                                                     3.5    5.3  20405 15216070168 `

**Comment by Jasagredo** [comment] 2022-09-12 11:46
So the `anchorFromBlock` function seems innocuous as long as the data is given to it. The `toShortRawHash` function doesn't seem very costly. Wild guess: the place where this is called mentions that `ReversePath` is lazy. 

https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/Impl/Paths.hs#L388-L391

Could this be related to the observed allocation and computation happening inside `anchorFromBlock`?

However these lines seem to indicate why this is the case:
```
      -- NOTE: we are intentionally lazy in the spine, as constructing the
      -- path requires lookups in the VolatileDB's in-memory indices, which
      -- are logarithmic in the size of the index.
```

**Comment by dnadales** [comment] 2022-09-20 16:57
Consensus will look at this in https://github.com/input-output-hk/ouroboros-network/issues/4021

**Comment by dnadales** [comment] 2023-02-27 16:19
Closing in favour of https://github.com/input-output-hk/ouroboros-network/issues/4021 Feel free to re-open if you don't think this is correct.

**Closed by dnadales** 2023-02-27 16:19 UTC
Labels: benchmark

**Comment by dnadales** [comment] 2023-04-19 16:20
Some additional considerations:

We do see SOP entries ranking high in that profile, however, I wonder if we should not compare the cost of such entries across eras? Otherwise how can we conclude that the cost of these operations increases after each era?

And the same question applies to the other functions analyzed here.

The benchmarks show performance regressions era after era, but it is not clear to me that this is due to the HFC or to the fact that the ledger operations take more time as the chain (and ledger state) grows. Our benchmarks [show this increase in processing time](https://github.com/input-output-hk/ouroboros-network/pull/4014#issuecomment-1254318158), but this increase is gradual and does not jump from one era to the next.

If we need to compare the cost of eras, we need to run benchmarks on two versions of the node: a normal node, and one where we add a large number of "dummy eras". We could make this happen.
