### ISSUE TITLE
[BUG] - Forge/ChainDB metrics not shown in /metrics starting 1.25.1 ?

### ISSUE THREAD

**Issue by garyng2000** [input-output-hk/cardano-node#2357] opened 2021-02-13 01:46 UTC
per the release note, I updated my node to 1.25.1 and download the latest mainnet-config.json (as there was some mentioning of metrics namespace consolidation).

however 
curl http://localhost:12798/metrics and http://localhost:13798/metrics no longer contain anything that is about Forge or ChainDB

I can still see the slot related info.

what should be the correct way to have them back ? need to track the KEH renew.

Was running 1.24.2 and everything was fine until Jan 20 2021 and it stopped syncing with other nodes.

**Comment by regel** [comment] 2021-07-17 09:55
Reproduced with `inputoutput/cardano-node:1.27.0` image and a local kind cluster.

Using testnet config, the only metrics scrapped are the following. Forge and ChainDB metrics are no longer exposed:

```
$ k run -ti --restart=Never --rm oo --image curlimages/curl sh
If you don't see a command prompt, try pressing enter.
/ $ curl foo-cardano-metrics:30100/metrics
^C
/ $ curl foo-cardano-metrics:30101/metrics
rts_gc_par_tot_bytes_copied 4833361320
rts_gc_num_gcs 5741
rts_gc_max_bytes_slop 1245792
cardano_node_metrics_Stat_threads_int 12
cardano_node_metrics_density_real 2.972381620773645e-2
cardano_node_metrics_epoch_int 144
rts_gc_num_bytes_usage_samples 434
rts_gc_wall_ms 3003867
cardano_node_metrics_RTS_gcMinorNum_int 5307
rts_gc_max_bytes_used 73340216
rts_gc_init_cpu_ms 2
rts_gc_bytes_copied 4833361320
rts_gc_init_wall_ms 3
cardano_node_metrics_RTS_gcLiveBytes_int 119427168
rts_gc_peak_megabytes_allocated 193
cardano_node_metrics_nodeStartTime_int 1626512003
ekg_server_timestamp_ms 1626515002132
cardano_node_metrics_RTS_gcMajorNum_int 434
cardano_node_metrics_blockNum_int 2760291
rts_gc_par_max_bytes_copied 4417297856
cardano_node_metrics_Stat_cputicks_int 24098
rts_gc_current_bytes_slop 9899936
cardano_node_metrics_RTS_gcticks_int 2954
cardano_node_metrics_RTS_mutticks_int 21138
rts_gc_cpu_ms 240937
rts_gc_bytes_allocated 170149267048
rts_gc_current_bytes_used 119427168
rts_gc_par_avg_bytes_copied 4833361320
cardano_node_metrics_served_header_counter_int 70
rts_gc_mutator_cpu_ms 211388
cardano_node_metrics_Mem_resident_int 228601856
rts_gc_gc_wall_ms 24677
rts_gc_mutator_wall_ms 2979189
rts_gc_gc_cpu_ms 29549
rts_gc_cumulative_bytes_used 1590911528
cardano_node_metrics_slotInEpoch_int 307315
cardano_node_metrics_slotNum_int 32145715
cardano_node_metrics_RTS_gcHeapBytes_int 202375168
```

This issue is breaking Grafana [dashboard](https://grafana.com/grafana/dashboards/12469). See screenshot below, the dashboard is empty since most of the metrics are no longer returned in /metrics endpoint.

![image](https://user-images.githubusercontent.com/355557/126033133-5bd8d7d4-fb22-44e7-9219-0fcded1f9a69.png)

**Comment by regel** [comment] 2021-07-17 20:21
Tested inputoutput/cardano-node docker tags 1.24.*, 1.25.* 1.26.* and I see the same metrics output. Probably, some changes related to config.json file. I will investigate in this direction and share findings.

**Comment by regel** [comment] 2021-07-17 21:23
Solution: include the following settings in the `config.json` file used to run the node:

```
  "options": {
    "mapBackends": {
      "cardano.node.metrics": [
        "EKGViewBK"
      ],
      "cardano.node.BlockFetchDecision.peers": [
        "EKGViewBK"
      ],
      "cardano.node.ChainDB.metrics": [
        "EKGViewBK"
      ],
      "cardano.node.Forge.metrics": [
        "EKGViewBK"
      ]
    },
```

Unfortunately I don't know where to find documentation for these settings nor the reason why they have been removed from default configurations in latest releases. Can IOHK devs help to provide more background information on metrics settings?

**Comment by regel** [comment] 2021-07-17 21:46
Last but not least, if you are using this Grafana dashboard template (cardano-node (stakepool overview)by rcmorano) then you will need to edit graphs and delete `ChainDB_` in PromQL queries in order to fix the dashboard.

**Comment by regel** [comment] 2021-07-21 20:58
Found this thread in the forum with some interesting [information](https://forum.cardano.org/t/post-upgrade-to-1-25-1-some-prometheus-grafana-metrics-not-showing/46137/29)

**Comment by Jimbo4350** [comment] 2022-10-27 08:15
Closing this. If this is still relevant please reopen.

**Closed by Jimbo4350** 2022-10-27 08:15 UTC
Labels: bug
