### ISSUE TITLE
[BUG] - cardano_node_BlockFetchDecision_peers_connectedPeers_int not reported if seveity not Info

### ISSUE THREAD

**Issue by ThaiTheo** [input-output-hk/cardano-node#1703] opened 2020-08-15 17:25 UTC
Internal/External
External

Summary
When in the mainnet-config.json the notication level is set higher than Info, the counter cardano_node_BlockFetchDecision_peers_connectedPeers_int is no longer reported.

Steps to reproduce
1. Monitor cardano_node_BlockFetchDecision_peers_connectedPeers_int through Prometheus or Grafana
2. Set FetchBlockPeerDecisions in mainnet-config.json to true and start cardano-node in basic setup
3. cardano_node_BlockFetchDecision_peers_connectedPeers_int will show values
4. Stop cardano-node and change minSeverity in mainnet-config.json from Info to Warning
5. Start cardano-node
6. cardano_node_BlockFetchDecision_peers_connectedPeers_int will not show values

Expected behavior
When in mainnet-config.json FetchBlockPeerDecisions is set to true, cardano_node_BlockFetchDecision_peers_connectedPeers_int will always show values.

System info (please complete the following information):
- OS: CentOS
- Version: 8
- Node version: 1.18.0

Screenshots and attachments
- Screenshot shows behavior of 1relay1 after changing severity level from Info to Warning
![Annotation 2020-08-15 191828](https://user-images.githubusercontent.com/41171413/90317807-3214cb00-df2c-11ea-85bb-a3fa0f201d58.png)

Additional context
The counter cardano_node_BlockFetchDecision_peers_connectedPeers_int is important to determine if a node is isolated from the block-chain. A block-producing node should have 1 peer at least (relay). A relay needs 2 peers at least (block-producing node and a relay).
The severity level should determine what gets logged, not which counters are reported or not.

**Comment by kevinhammond** [comment] 2020-08-25 11:39
There has been some ongoing work on the logging and monitoring system

**Comment by dcoutts** [comment] 2020-09-15 11:24
I _think_ the request here is that this tracer be assigned a "notice" level of severity rather than "info". If so, that should be a trivial one-line change.

**Comment by Jimbo4350** [comment] 2020-10-08 13:57
@dcoutts I've reproduced this, however `Notice` is less severe than `Warning` so it still won't show up in Prometheus as we filter by the minimum `Severity` ( @ThaiTheo set the minimum `Severity` to `Warning`) . If we want to log things regardless of what we set the minimum `Severity` at, we need to add another `Severity` level that trumps all others and perhaps allow the users to configure these overrides via the config yaml file. 
cc: @CodiePP

**Comment by denisshevchenko** [comment] 2020-10-20 19:29
FYI, currently RTView doesn't use `connectedPeers` metric because it has a delay (I don't know why), when the peer is already connected but this value is still `0`. Instead, RTView receives `peersFromNodeKernel` metric with the list of information about peers. And the length of this list is used as a number of connected peers. This value changes immediately.

**Comment by Jimbo4350** [comment] 2022-10-27 08:06
Closing this. If this is still relevant please re-open.

**Closed by Jimbo4350** 2022-10-27 08:06 UTC
Labels: bug
