### ISSUE TITLE
[BUG] - Delegated SPO rewards address does not get rewards

### ISSUE THREAD

**Issue by Straightpool** [input-output-hk/cardano-node#1964] opened 2020-10-09 21:12 UTC
**Internal/External**
*External*  

**Summary**
When an SPO has specified a separate rewards address to receive all of the pool operation and pledge rewards and at the same time has delegated this rewards wallet to his own pool, this address will not get rewards.
It seems the protocol rewards calculation has a bug in this edge case. Most SPOs probably do not delegate their rewards address and / or the rewards are small, so this is not easily noticed.

**Steps to reproduce**
1. Create pool X with separate wallets for operator, owner and rewards
2. Delegate all wallets owner, operator and rewards to pool X
3. Wait until stake gets effective
4. Produce blocks
5. Wait until rewards wallet has received rewards which have become active in delegation
6. Produce blocks
7. Receive rewards, and now compare rewards with the expected result, e.g. check on pooltool.io rewards tracking
8. Notice rewards for rewards wallet are missing

We double checked this on multiple epochs. On each epoch I have noted a small offset of sub 0-2 ADA. The offset is exactly the rewards the rewards wallet should receive but does not.

**Expected behavior**
A delegated extra rewards wallet should also get compounded rewards for its delegated reward ADA

**System info (please complete the following information):**
- OS: Ubunto
- Version 20.04
- Node version: 1.21.1 on mainnet
- Wallet to check on rewards: Daedalus 2.3.0

**Screenshots and attachments**
This table shows the exact tracking of the rewards wallet 

`addr1q9tg29teq5zcvmr0d0h7a2yp399msph6tj6zyq22xyw6znc5hdqk2pfvkk7sefgcd8dn3psse8hf9jn8u39z896e6pvs58572w`

in Daedalus, compared to pooltool.io calculation and offset
![image](https://user-images.githubusercontent.com/42584250/95630522-4aafe600-0a82-11eb-8e14-9ed1a1b99886.png)

This table plausibly shows it is the rewards missing for the rewards wallet:
![image](https://user-images.githubusercontent.com/42584250/95630544-569ba800-0a82-11eb-8c08-bdf30be856b7.png)
- epochs along top
- value in my reward wallet is the next line.  that is value staked, not what Daedalus says
- then my pledge wallet was used to calculate the percentage return.  that is the plege wallet return % line.
- then the last line.  Here that percentage is used, times my reward wallet stake.  Here we come up with the exact delta between my Daedalus rewards balance and pooltool rewards calculation.

**Additional context**
Here the pooltool rewards calculation for this edge case wallet can be seen: 
https://pooltool.io/address/14bb4165052cb5bd0ca51869db388610c9ee92ca67e44a239759d059

Thanks a ton to Mike to help debug this to this point!

**Comment by mkoura** [comment] 2020-10-26 22:41
I was not able to reproduce that on testnet.

I have a pool with separate wallets for owner and for rewards. At first the rewards wallet is not delegated. I tracked rewards for 10 epochs, in epoch 6 I delegated the rewards address to the pool, so the delegation took effect in epoch 10. The staked pledge is 1000000000000 Lovelace.

|epoch | rewards balance | reward in epoch | note                          |
|----- |-----------------|-----------------|-------------------------------|
|4     | 46168382574     | 46168382574     |                               |
|5     | 92183430194     | 46015047620     |                               |
|6     | 138046150221    | 45862720027     | delegated reward address      |
|7     | 183757590661    | 45711440440     |                               |
|8     | 229318738685    | 45561148024     |                               |
|9     | 274730571515    | 45411832830     |                               |
|10    | 323335569001    | 48604997486     | reward delegation took effect |
|11    | 372607553494    | 49271984493     |                               |
|12    | 422539324056    | 49931770562     |                               |
|13    | 473183903407    | 50644579351     |                               |

You can see reward amount received in each epoch increasing steadily from epoch 10 vs decreasing rewards received just for the pledged amount before the epoch 10.

**Comment by Straightpool** [comment] 2020-10-29 15:58
Martin, thanks a lot for trying to reproduce this! 
However, I do not think your test setup was suitable to reproduce the bug. Slots vary by epoch anyway due to the lottery so the effect you have seen is random IMHO and has no relation to the reported bug.

 May I propose the following change, if you still have this setup you can reuse this:

- The rewards wallet should have ONLY rewards, which are not yet claimed, please do double check 
- Reduce pledge on test pool down to 0, if not already down to 0
- Undelegate the owner wallet, so only the delegation of the rewards balance remains
- Wait on block, see if rewards balance rises (if it does not the bug is reproduced). Of course this might take a while when the rewards are small, so maybe you will want to accumulate more rewards first to get blocks

**Comment by mkoura** [comment] 2020-11-02 22:26
My testnet has just two very similar pools (it is my own testnet, not the original ITN), so lottery doesn't have effect here IMHO. I tested your scenario with the same result as with the previous test:

| epoch    | rewards balance   | reward in epoch   | note                          |
| -------- | ----------------- | ----------------- | ------                        |
| 4        | 46173467153       | 46173467153       |                               |
| 5        | 92192970606       | 46019503453       |                               |
| 6        | 138060135498      | 45867164892       | delegated reward address      |
| 7        | 183775959274      | 45715823776       |                               |
| 8        | 229341429729      | 45565470455       |                               |
| 9        | 274757524455      | 45416094726       |                               |
| 10       | 282243604887      | 7486080432        | reward delegation took effect |
| 11       | 291555591863      | 9311986976        |                               |
| 12       | 302675658440      | 11120066577       |                               |
| 13       | 314061987461      | 11386329021       |                               |
| 14       | 325786292657      | 11724305196       |                               |
| 15       | 337918884957      | 12132592300       |                               |

* in epoch 0, pledge for the pool was set to 0
* in epoch 6 the pool owner's stake address was deregistered (some reward was already accumulated) and reward address was delegated
* in epoch 10 the reward address delegation and stake address deregistration took effect
* from epoch 10 only rewards for delegated reward address are received

Notice that the first reward for delegated reward address is received in the epoch that comes 4th after the epoch where the reward address was delegated. Have you waited that long in your tests?

From ledger state dump for e.g. epoch 10 I can confirm that only the reward address (8a544fc263ee67446c8fc4f7e39dea344b8e19a7ab5d49bc3d84b694) is delegated for the pool (2a73a11e442a8195e8f719b88dc30a326c36cbf15904831a1ccd1dae). The addresses are bech32 decoded:

```
"_pstakeGo": {
    "_stake": [
        [
            {
                "key hash": "8a544fc263ee67446c8fc4f7e39dea344b8e19a7ab5d49bc3d84b694"
            },
            229341429729
        ]
    ],
    ...
    "_delegations": [
        [
            {
                "key hash": "8a544fc263ee67446c8fc4f7e39dea344b8e19a7ab5d49bc3d84b694"
            },
            "2a73a11e442a8195e8f719b88dc30a326c36cbf15904831a1ccd1dae"
        ]
    ]
```

**Comment by Jimbo4350** [comment] 2022-10-27 08:02
Closing this. If this is still relevant please re-open.

**Closed by Jimbo4350** 2022-10-27 08:02 UTC
Labels: bug
