### ISSUE TITLE
[FR] - GHC 8.8? 

### ISSUE THREAD

**Issue by Fell-x27** [input-output-hk/cardano-node#1702] opened 2020-08-15 16:04 UTC
There are some errors like https://github.com/input-output-hk/cardano-node/issues/1251 if you tried building with ghc>8.6
That means I cant update it to my own purposes. But there is 8.10 already. 

Is there a way to build node with ghc 8.8 at least? Or can we hope that 8.8 could be default version?

**Comment by mark-stopka** [comment] 2020-08-17 13:46
Duplicate of https://github.com/input-output-hk/cardano-node/issues/1484

**Comment by kevinhammond** [comment] 2020-08-20 15:27
Closed as a duplicate.  There are build dependencies that mean we cannot yet upgrade to more recent versions of GHC, unfortunately.

**Closed by kevinhammond** 2020-08-20 15:27 UTC
Labels: enhancement
