### ISSUE TITLE
[BUG] - Cardano-cli take longer to query

### ISSUE THREAD

**Issue by SebCli78** [input-output-hk/cardano-node#3490] opened 2022-01-09 19:48 UTC
*External*   otherwise.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**

Not really a bug but cardano-cli using node 1.33.0 is taking from 4 to 5 seconds to provide query result, versus less than a second using 1.30.1

As I'm using cardano-cli with scripts to automate minting of NFTs, this become a problem when doing queries to list utxo
So is there any tips on Cardano-node side to make it more responsive on queries here or anything to look for ?

This really makes regression on the process and especially when the mint process was good running at less than a second to refresh wallet utxo.

your help will be very welcome.
Thanks 

**Expected behavior**
an output as before is less than a second.

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version 20.04
- Node version 1.33.0
- CLI version 1.33.0

Thanks again

**Comment by frog357** [comment] 2022-01-09 20:24
I also experience this.
The following command using cli v1.31 takes less than a second.
cardano-cli query utxo --address $(cat pay.addr) --mainnet
The same command on v1.33 takes greater than 15 seconds.

**Comment by rdlrt** [comment] 2022-01-10 13:44
It is "by design", as UTxO is now saved on disk (keeping it in memory was not sustainable), you'd want to start looking at query layers for UTxO

**Comment by frog357** [comment] 2022-01-10 14:10
I have 64gb of ram - how about a flag to restore the functionality for those who can afford it? Seems like you just hurt all the builders who rely on such basic functionality.

**Comment by SebCli78** [comment] 2022-01-10 14:57
I hope to get a flag too to move it back in memory when we can afford it, at least the time to let us a chance to move on another way to query.

**Comment by frog357** [comment] 2022-01-10 15:33
> > you just hurt all the builders who rely on such basic functionality.
> 
> I am not associated with IO, just informing about the change. Widely used tools within builder community are already adopting :)

You might be able to help more by referring to some of these community solutions that you imply to have knowledge about. We have two people in this thread who are not a member of the insider club you seem to know more about and are seeking help - you say the community is adopting so you know about this - we are asking for help - I guess thank you for telling us that other people know more and don't need to ask for help here?

**Comment by den-is** [comment] 2022-01-10 16:54
@rdlrt 
> you'd want to start looking at query layers for checking UTxO details
what are these layers? any links to docs and/or examples?

**Comment by rdlrt** [comment] 2022-01-10 17:23
Current popular component being cardano-db-sync (which can be accessed  over cardano-graphql, postgREST, koios (locally or remotely) or using third party services like blockfrost, dandelion , etc), and/or can build one using ogmios.

**Comment by den-is** [comment] 2022-01-10 17:50
correct [link to koios](https://api.koios.rest), will delete when the original message is fixed @rdlrt

**Comment by SebCli78** [comment] 2022-01-12 09:08
so was looking to work around with cardano dbsync, where I'm testing it and face 'rollback issue' that takes ages to recover database and that is a bit not so powerful that was Cardano-cli in the past. See my previous link 'Query UTxOs' where it said that Cardano-cli is quicker due to in-memory than database ... 
so sounds like we need to have a robust infra and redundancy in place if we want to use dbsync instead cardano-cli

**Comment by den-is** [comment] 2022-01-12 09:41
> so sounds like we need to have a robust infra and redundancy in place if we want to use dbsync instead cardano-cli
or pay "query layers" to do that for you - that's how capitalist's mathematically proven, peer-reviewed, model of equality and universal balance, looks like.

**Comment by Jimbo4350** [comment] 2022-10-27 08:42
Closing this. If this is still relevant please reopen.

**Closed by Jimbo4350** 2022-10-27 08:42 UTC
Labels: bug, type: bug, user type: external, comp: cardano-cli, release: 1.33.0, area: query utxo
