### ISSUE TITLE
[BUG] - Problem building minting tx with cardano-cli

### ISSUE THREAD

**Issue by shawnim** [input-output-hk/cardano-node#3461] opened 2021-12-23 01:30 UTC
**Internal/External**
*External*   otherwise.

**Area**
*Native Tokens*    Related to Native Tokens (Mary).

**Summary**
When building a minting transaction, cardano-cli rejects the letter 'S' as not being alphanumeric.

**Steps to reproduce**
Executing the following minting transaction:
```
cardano-cli transaction build --mainnet --alonzo-era --tx-in 09b4[...]bf0#0 --tx-out addr1v8[...]jv7+1400000+1 a14[...]dd4.ShawnHead1 --change-address addr1v8[...]jv7 --mint=1 a14[...]dd4.ShawnHead1 --minting-script-file policy/policy.script --metadata-json-file metadata.json --invalid-hereafter 48745000 --witness-override 2 --out-file matx.raw
```
gave me this error:
```
option --tx-out: 
unexpected 'S'
expecting alphanumeric asset name, white space, "+" or end of input
```
and a usage message.
The character being objected to (first letter of asset name) is alphanumeric so this seems like a bug.
I was able to mint with an empty string as the asset name so there isn't anything wrong with the variable settings or environment.

**Expected behavior**
The command should accept the asset name and create the transaction.

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version 20.04
- Node version
```
cardano-node 1.32.1 - linux-x86_64 - ghc-8.10
git rev e9de7a2cf70796f6ff26eac9f9540184ded0e4e6

```
- CLI version
```
cardano-cli 1.32.1 - linux-x86_64 - ghc-8.10
git rev e9de7a2cf70796f6ff26eac9f9540184ded0e4e6
```

**Comment by kbj1213** [comment] 2021-12-23 03:37
I have the same problem. Is there anybody who resolved this problem?

**Comment by firojalamkhan786** [comment] 2021-12-23 06:32
I am trying to mint NFT in Cardano testnet, I am also facing the same issue. 
vagrant@vagrant:~/nft$ **cardano-cli transaction build --testnet-magic 1097911063 --byron-era --tx-in $txhash#$txix --tx-out $address+$output+"$tokenamount $policyid.$tokenname" --change-address $address --mint="$tokenamount $policyid.$tokenname" --minting-script-file $script --metadata-json-file metadata.json  --invalid-hereafter $slotnumber --witness-override 2 --out-file matx.raw**
option --tx-out:
unexpected 'N'
expecting alphanumeric asset name, white space, "+" or end of input

**Other details:**
vagrant@vagrant:~/nft$ echo $output $tokenamount $tokenname
1400000 1 NFTFIROJ
vagrant@vagrant:~/nft$ echo $output $tokenamount $tokenname1
1400000 1
vagrant@vagrant:~/nft$ echo $CARDANO_NODE_SOCKET_PATH
/home/vagrant/cardano/db/node.socket
vagrant@vagrant:~/nft$ echo $LD_LIBRARY_PATH
/usr/local/lib:/usr/local/lib:
vagrant@vagrant:~/nft$ echo $PKG_CONFIG_PATH
/usr/local/lib/pkgconfig:/usr/local/lib/pkgconfig:
vagrant@vagrant:~/nft$ cardano-node --version
cardano-node 1.32.1 - linux-x86_64 - ghc-8.10
git rev 4f65fb9a27aa7e3a1873ab4211e412af780a3648
vagrant@vagrant:~/nft$ cardano-cli --version
cardano-cli 1.32.1 - linux-x86_64 - ghc-8.10
git rev 4f65fb9a27aa7e3a1873ab4211e412af780a3648

Please let us know any workaround for this issue.

**Comment by alexdabast** [comment] 2021-12-23 14:55
Using a empty token name is working ... however it is not a valid workaround yet

**Comment by joebartels** [comment] 2021-12-24 10:35
same here. using cardano-node 1.32.1 also
```
cardano-cli 1.32.1 - darwin-x86_64 - ghc-8.10
git rev 4f65fb9a27aa7e3a1873ab4211e412af780a3648
```

**Comment by gitmachtl** [comment] 2021-12-25 00:56
This is not a bug, cli 1.32.1 is now operating in hex representation of nativeAssets. So all must be done directly in hexcode!

There is a warning about that in the release notes:
https://github.com/input-output-hk/cardano-node/releases/tag/1.32.1

A reference usage can be found in the docs:
https://github.com/input-output-hk/cardano-node/blob/master/doc/reference/multi-assets.md

**Comment by shawnim** [comment] 2021-12-25 04:11
It would be nice if these kind of breaking changes would be coordinated with Cardano Foundation docs.

**Comment by shawnim** [comment] 2021-12-25 04:24
Does this mean we need to do something like:

echo -n "Hello" | od -A n -t x1

 48 65 6c 6c 6f

to end up with an asset name of:

48656c6c6f

**Comment by gitmachtl** [comment] 2021-12-25 10:01
> It would be nice if these kind of breaking changes would be coordinated with Cardano Foundation docs.

You will find non consistent examples all over the place, in many tutorials, etc. Thats why the Release Notes are there IMO.

> Does this mean we need to do something like:
> echo -n "Hello" | od -A n -t x1
> 48 65 6c 6c 6f
> to end up with an asset name of:
> 48656c6c6f

There are many ways to convert it yes, like:

**Comment by shawnim** [comment] 2021-12-26 00:54
If this is closed then maybe we need a new issue to change the error message to "Asset name must be hexidecimal" as the current error message is incorrect.

**Comment by rdlrt** [comment] 2021-12-26 07:21
> would be coordinated with Cardano Foundation docs.

Just a note that those are more of a community maintained documentations where PRs are welcome , thus - only as strong as community activity 👍🏻

**Comment by gitmachtl** [comment] 2021-12-26 09:29
> If this is closed then maybe we need a new issue to change the error message to "Asset name must be hexidecimal" as the current error message is incorrect.

PR to change the error message submitted:
https://github.com/input-output-hk/cardano-node/pull/3466

**Comment by shawnim** [comment] 2021-12-26 18:53
> > If this is closed then maybe we need a new issue to change the error message to "Asset name must be hexidecimal" as the current error message is incorrect.
> 
> PR to change the error message submitted: #3466

Awesome! Thanks.

**Comment by shawnim** [comment] 2021-12-26 22:44
FYI, I created a PR for the CF native asset and NFT minting docs to use hex asset names.
https://github.com/cardano-foundation/developer-portal/pull/454

**Comment by Jimbo4350** [comment] 2022-01-03 19:26
> If this is closed then maybe we need a new issue to change the error message to "Asset name must be hexidecimal" as the current error message is incorrect.

cc: @cblp

**Comment by gitmachtl** [comment] 2022-01-04 12:56
@cblp https://github.com/input-output-hk/cardano-node/pull/3466

**Comment by dorin100** [comment] 2022-01-05 09:54
thank you guys for your input and initiative. 
@shawnim can we close this issue and keep only the created PRs (thank you @gitmachtl)?

**Comment by shawnim** [comment] 2022-01-05 18:59
Yes. Thanks!

**Closed** 2022-01-06 08:28 UTC
Labels: bug

**Comment by Wolfy18** [comment] 2022-02-17 03:42
> **Internal/External** _External_ otherwise.
> 
> **Area** _Native Tokens_ Related to Native Tokens (Mary).
> 
> **Summary** When building a minting transaction, cardano-cli rejects the letter 'S' as not being alphanumeric.
> 
> **Steps to reproduce** Executing the following minting transaction:
> 
> ```
> cardano-cli transaction build --mainnet --alonzo-era --tx-in 09b4[...]bf0#0 --tx-out addr1v8[...]jv7+1400000+1 a14[...]dd4.ShawnHead1 --change-address addr1v8[...]jv7 --mint=1 a14[...]dd4.ShawnHead1 --minting-script-file policy/policy.script --metadata-json-file metadata.json --invalid-hereafter 48745000 --witness-override 2 --out-file matx.raw
> ```
> 
> gave me this error:
> 
> ```
> option --tx-out: 
> unexpected 'S'
> expecting alphanumeric asset name, white space, "+" or end of input
> ```
> 
> and a usage message. The character being objected to (first letter of asset name) is alphanumeric so this seems like a bug. I was able to mint with an empty string as the asset name so there isn't anything wrong with the variable settings or environment.
> 
> **Expected behavior** The command should accept the asset name and create the transaction.
> 
> **System info (please complete the following information):**
> 
> * OS Name: Ubuntu
> * OS Version 20.04
> * Node version
> 
> ```
> cardano-node 1.32.1 - linux-x86_64 - ghc-8.10
> git rev e9de7a2cf70796f6ff26eac9f9540184ded0e4e6
> ```
> 
> * CLI version
> 
> ```
> cardano-cli 1.32.1 - linux-x86_64 - ghc-8.10
> git rev e9de7a2cf70796f6ff26eac9f9540184ded0e4e6
> ```

I think the problem may be related with bash. Try wrapping the minting transaction in quotes like:

```
cardano-cli transaction build \
--mainnet \
--alonzo-era \
--tx-in 09b4[...]bf0#0 \
--tx-out addr1v8[...]jv7+1400000+"1 a14[...]dd4.ShawnHead1" \
--change-address addr1v8[...]jv7 \
--mint="1 a14[...]dd4.ShawnHead1" \
--minting-script-file policy/policy.script \
--metadata-json-file metadata.json \
--invalid-hereafter 48745000 \
--witness-override 2 \
--out-file matx.raw
```

By the way, the asset name in the transaction out must be base16 encoded

```
name = b16encode(ShawnHead1)
--tx-out addr1v8[...]jv7+1400000+"1 a14[...]dd4.{name} " \
```
