### ISSUE TITLE
[BUG] - leaderlog error with hardfork transition epoch

### ISSUE THREAD

**Issue by Willburn** [input-output-hk/cardano-node#4478] opened 2022-09-26 07:22 UTC
*External* 

**Area**
*leaderlog*

**Summary**
Using the built in leaderlog function of cardano-cli to calculate the next epoch block scedule I got a different result before the HF and when I did the same leaderlog for the current epoch after the HF the scedule was changed.  While perhaps not a critical issue as it relates to HF, could be useful to investigate the cause of this for future HF's. 

**Steps to reproduce**
I have the leaderlog output still but it will require a testnet that HF's to reproduce the result. 

**Expected behavior**
Same leaderlog for next epoch before HF as current epoch leaderlog after HF.

**System info (please complete the following information):**
Ubuntu 20.04. Cardano-cli and cardano-node 1.35.3

**Comment by CarlosLopezDeLara** [comment] 2022-10-06 17:06
Duplicate of https://github.com/input-output-hk/cardano-node/issues/4131
Fixed in https://github.com/input-output-hk/cardano-node/pull/4106

Note: The fix is pending for release.

**Closed by CarlosLopezDeLara** 2022-10-06 17:06 UTC
Labels: bug, duplicate
