### ISSUE TITLE
[FR] - Make `json` formatted output explicit

### ISSUE THREAD

**Issue by nielstron** [input-output-hk/cardano-node#4390] opened 2022-08-25 14:03 UTC
**Internal/External**
*External*   otherwise.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
The json-formatted query utxo output should be obtainable by providing an optional `--json` flag or sth similar. Currently the output is automatically json-formatted when using `--out-file`. This is terrible for many reasons, some of them

- It is completely undocumented
- There is a semantic difference between `cardano-cli query utxo ... > file` and `cardano-cli query utxo ... --out-file file` which is... unintuitive to say the least
- The current canonical way to get json formatted output from the node is `cardano-cli query utxo ... --out-file /dev/stdout`... no more comments.

**Describe alternatives you've considered**
None

**Additional context / screenshots**
None

**Comment by gitmachtl** [comment] 2022-10-27 14:47
duplicate of https://github.com/input-output-hk/cardano-node/issues/3213

**Comment by newhoggy** [comment] 2023-02-27 13:17
Closing in favour of https://github.com/input-output-hk/cardano-node/issues/3213

**Closed by newhoggy** 2023-02-27 13:17 UTC
Labels: enhancement, type: enhancement, user type: external, comp: cardano-cli
