### ISSUE TITLE
[Release notes] : Breaking change for oCert

### ISSUE THREAD

**Issue by rdlrt** [input-output-hk/cardano-node#3976] opened 2022-06-01 23:13 UTC
## Internal/External
External

## Type of Change
Documentation/Release Notes

## Node Version
1.35.x

## Platform
All

## Description

To avoid looping in circles about the question, it would be good to document ***why*** ocert was changed to have restriction of counter being <= 1 than last counter seen for last block on the chain.

The tooling built by community (CNTools, @gitmachtl' SPO scripts, Jormanager, etc) will ofcourse add the support for this change to make it simpler, but there will be an impact to offline cold key holders (especially smaller pools - which may or may not have had blocks between two points of their rotation) as they will need to fetch latest KES keys from chain (via CLI or via third party service like Koios), and enter the number manually on offline machine.

All of this is manageable - as long as the reason for why this change was done for Babbage is obviously documented, and community tools can point to it, _**before**_ a release is out and SPOs are asked to upgrade on testnet

**Comment by rdlrt** [comment] 2022-06-06 21:21
> this might be a duplicate of #3959

It partially is, but we need these documented in docs as well as release notes - the current PR additions didn't tackle documenting the "why" for SPO facing actions like change in OCert behaviour, which is the primary target for this PR

**Comment by CarlosLopezDeLara** [comment] 2022-06-13 21:13
We will treat this as duplicate of #3959 (older one). @olgahryniuk is working on documentation. We will make sure to cover points in both tickets.

**Closed by CarlosLopezDeLara** 2022-06-13 21:13 UTC
Labels: documentation, Vasil
