### ISSUE TITLE
[FR] -  Add CLI command to display the leadership schedule

### ISSUE THREAD

**Issue by mmahut** [input-output-hk/cardano-node#1027] opened 2020-05-24 10:05 UTC
**Describe the feature you'd like**

I would like to know my leadership schedule, at least the nearest upcoming leadership event, so I can plan my node maintenance or/and KES rotating.

**Comment by cardadad** [comment] 2020-06-01 04:17
A summary of recently minted blocks as a part of this information would also be beneficial, similar to what is currently implemented on ITN - with status (in block / failed due to X) as well as epoch/slot and block hash data

**Comment by dcoutts** [comment] 2020-06-02 12:56
Recent events are available via the JSON logs and aggregates via the metrics.

Getting the future schedule will take a bit more effort. The node does not compute the schedule in advance, it does everything incrementally.

**Comment by AndrewWestberg** [comment] 2020-06-04 05:04
This is pretty important for pool operators to know. Without it we cannot know when it's best to do maintenance. We also cannot gauge performance of our pools. If you can get a schedule in advance, you can then evaluate after the fact as to how your node performed on those slots. During ITN, this was a primary way of differentiating how good a pool was on pooltool. Compare their assigned slots to how many blocks they minted. If we solely look backwards at blocks, we don't know whether we just got a random poor slot lottery or if our node is actually under-performing and missing or not propagating blocks properly.

**Comment by teamstaking** [comment] 2020-06-14 12:13
It would be nice if it had the same API as Jormungandr so the tools built using those APIs could work with both.

**Comment by Crypto2099** [comment] 2020-08-17 16:19
I'll throw my $0.02 in here to agree with Andrew's sentiment above. Being able to know if and when you have a block coming up would be extremely helpful from a maintenance/upgrade perspective and help to mitigate a lot of the strategies I'm currently hearing bandied about in public and private channels about how best to accomplish rolling updates (which almost always entail operating two instances of the BP for some simultaneous period).

**Comment by samcgill29** [comment] 2020-08-17 17:56
This is a MUCH needed utility. Could this feature request please be expedited? I am looking for a CLI tool that will output a leader log for the entire epoch, similar to the tool that was available in Jormungandr.

**Comment by cyber-russ** [comment] 2020-08-20 14:57
Second this request. I have a pool which should be producing blocks, but so far isn't even though all prometheus (Cardano-node) stats look good. How do I tell whether it's just been bad luck - no slots assigned, versus some fault in configuration or upstream network issue that I am not aware of? This would be a great starting point to diagnose.

**Comment by AndrewWestberg** [comment] 2020-09-01 19:09
Adding another comment to this one to keep it on everyone's radar. This is my very top #1 desired thing to have as a SPO. Without it, we cannot track our real performance or plan maintenance without potential injury to our pool or delegation. For SPOs living on the edge where every block counts, this is critical.

**Comment by samcgill29** [comment] 2020-09-01 19:16
@Jimbo4350 Can we get an update on the status of this FR, please?

**Comment by mrbrinker** [comment] 2020-09-07 06:53
@vhulchenko-iohk do we have any updates on this FR?

**Comment by AndrewWestberg** [comment] 2020-10-05 16:43
![image](https://user-images.githubusercontent.com/245918/95107465-ca3e5d80-06ee-11eb-99d8-233d4b68e147.png)

I have cracked the nut and will be adding this functionality to an upcoming version of JorManager.

JorManager Telegram: https://t.me/jormanager

I have been sharing my knowledge with other developers in the community. They have confirmed that they are working on a Python version, a javascript version, and a GO version. They will be released to the SPO community once complete as well.

This discussion is happening in this group if you want to follow along: https://t.me/joinchat/OKP2Okapw5FrZXBPGtadIQ

**Comment by cyber-russ** [comment] 2020-10-05 19:51
I am strongly against this as it open us a whole class of DDoS attacks against the network. Once you know slot leader you can attack relays easily based on publicly accessible knowledge. This needs to be fixed fast in the node to stop this capability.

**Comment by Crypto2099** [comment] 2020-10-05 21:01
> Smart work and good that this has been disclosed but I am strongly against this as it opens SPOs up to a whole class of DDoS attacks against the network. Once you know slot leader you can attack their relays easily based on publicly accessible knowledge. This needs to be fixed fast in the node to stop this capability.
> 
> It also allows SPOs to game and only be online for slots which weakens the overall network and its processing capabilities.

As I understand it, currently, the VRF/KES of the pool in question is required to calculate the slot leadership schedule for that pool. So this is a far way if not impossible from telling us the slot leadership schedule of other parties (and thereby allowing us to target them).

**Comment by mark-stopka** [comment] 2020-10-06 07:28
> ![image](https://user-images.githubusercontent.com/245918/95107465-ca3e5d80-06ee-11eb-99d8-233d4b68e147.png)
> 
> I have cracked the nut and will be adding this functionality to an upcoming version of JorManager.
> 
> JorManager Telegram: https://t.me/jormanager
> 
> I have been sharing my knowledge with other developers in the community. They have confirmed that they are working on a Python version, a javascript version, and a GO version. They will be released to the SPO community once complete as well.
> 
> This discussion is happening in this group if you want to follow along: https://t.me/joinchat/OKP2Okapw5FrZXBPGtadIQ

Do you have a functional specification for the feature? I have a developer to implement it directly into the Cardano Node codebase...

**Comment by cyber-russ** [comment] 2020-10-06 07:37
If that's correct then its good news that this requires the KES/VRF as that makes a fix less urgent.

I would attack this way instead. Sybil attack- register a LOT (thousands) of pools, I only need my pool to be available for its one slot (I'm not going to put much delegation against any pool, as I get to know what pools will be successful that Epoch), and I don't need much resource as I use the same relays and just switch in and out on the core node for the pool that will be successful.

Law of unintended consequences applies here. You are changing fundamental security tenets of the system which is that slot leaders are elected with a provably random algorithm in a previous Epoch. Once you know the slots there is no random.

**Comment by rene84** [comment] 2020-10-06 08:03
I don't quite understand that attack scenario. Registering thousands of pools will cost you 500 ADA per pool. Then putting in sufficient stake per pool to even get assigned one block per epoch even more and re-using stake across other pools will have a delay of 2 epochs

**Comment by cyber-russ** [comment] 2020-10-06 08:09
Rene, perhaps I’m wrong on the attacks, I haven’t worked through the numbers. But Cardano aspires to be the worlds financial operating system it won’t be if SPOs can game it like this...

**Comment by mark-stopka** [comment] 2020-10-06 15:55
> Rene, perhaps I’m wrong on the attacks, I haven’t worked through the numbers. But Cardano aspires to be the worlds financial operating system it won’t be if SPOs can game it like this...

You think you are preventing something when it is implementable by an attacked but not just implemented? You are not... honesty of 51% stake is a Ouroboros security assumption, if validated, it is not provably secure, period.

**Comment by 2072** [comment] 2020-10-06 22:48
@cyber-russ This is not gaming the system at all, the security prerequisite is that only the SPOs are allowed to know if they are going to make a block - mainly to prevent DDOs from other SPOs - and this is not violated since the data required to know that has always been available, there was just no implementation, probably because it's just a convenience feature and was not a priority for IOG...

**Comment by AndrewWestberg** [comment] 2020-10-10 16:24
For those who happen across this issue ticket, here are some links to the community-based projects that allow you to see leader logs.

JorManager:
https://bitbucket.org/muamw10/jormanager

Python:
https://github.com/papacarp/pooltool.io/tree/master/leaderLogs

NodeJS:
https://github.com/MarcelKlammer/cardano-leader-logs

**Comment by AndrewWestberg** [comment] 2020-11-20 16:40
CNCLI contains an implementation built in RUST.

https://github.com/AndrewWestberg/cncli

**Comment by AndrewWestberg** [comment] 2020-11-20 16:40
This issue can probably be closed out.

**Comment by laplasz** [comment] 2021-01-06 21:02
cncli 0.5.6
leaderlog:
```
  "assignedSlots": [
    {
      "no": 1,
      "slot": 18525136,
      "slotInEpoch": 208336,
      "at": "2021-01-07T23:37:07-08:00"
    }
  ]
```
the machine which created the report is in UTC
`Wed Jan  6 14:37:41 UTC 2021`

my question is that what is the timezone of the assignment? Why there is a 8 hour subtraction?
THanks!

**Comment by AndrewWestberg** [comment] 2021-01-06 21:08
@laplasz Support for CNCLI belongs in this project -> https://github.com/AndrewWestberg/cncli

That being said, you can change the timezone with a command-line parameter. The default is "America/Los_Angeles".

**Comment by dorin100** [comment] 2021-03-29 12:38
Reopening this issue in order to track the implementation of the requested functionality directly into the CLI. This would help with debugging the producer functionality using the node directly.

**Comment by nc6** [comment] 2021-03-29 12:56
Note that there's already functionality exposed in the ledger for this feature, but it would need some changes in consensus to expose the necessary information to the query protocol.

**Comment by AndrewWestberg** [comment] 2021-03-29 23:26
Let me set the bar for this now that it's been re-opened. The current cardano-node ledger does not set values like the epoch nonce until the epoch change actually happens. The nonce can actually be known 1.5 days before the epoch cutover. 

If you build out a leaderlogs command without addressing this, cardano-cli leaderlogs will likely remain unused in favor of community tools like CNCLI that give the results to SPOs 1.5 days early.

**Comment by Scitz0** [comment] 2021-03-30 06:50
CNCLI will most likely still be the default option in the community tool CNTools even after this is implemented due to the additional functionality it adds in addition to leaderlogs by storing a lightweight SQLite DB with all blocks since Shelley. This makes it easy to validate if the scheduled block was created by the pool, race condition with another pool or if it ended up on a fork.

**Closed** 2022-01-11 16:30 UTC
Labels: enhancement, priority medium, cli revision, API&CLI-Backlog
