### ISSUE TITLE
[BUG] - Relay nodes keep all the old connections open when restarting, causing a silent self-DDOS attack.

### ISSUE THREAD

**Issue by joseiadicicco** [input-output-hk/cardano-node#4707] opened 2022-12-11 16:24 UTC
**External**

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
Relay nodes keep all the old connections open when restarting, causing a silent self-DDOS attack. This issue is particularly significant for nodes that run with low memory because their relays restart often.
On top of that, the operator doesn't know that this is caused by the relay restarting, so, thinking it's a DDOS attack, it blocks or limits connections to valid peers. Causing delays in the block propagation.

1.- Nodes with few resources (which are the most affected), start to have less and less resources as with each reset they increase their open TCP/IP connections.

2.- The traffic in the backbone of the network increases considerably, since each open connection between Peers, requires keep alive packets to be maintained, which generates a lot of useless traffic.

3.- The nodes that receive the connections suspect that it is an attack, and therefore block those Peers that could be completely desirable, generating communication barriers in a decentralized P2P network, with all that this entails.

4.- In addition to blocking, in other cases the countermeasures include the programming of IPTABLE rules to limit the number of connections per IP, which increases the number of operations on the packets received, adding more processing delay (although it is little for that node, as it occurs in many nodes throughout the network, it ends up being a lot for a P2P blockchain network where every millisecond counts and each timeslot takes 1 second and the overall propagation must be kept below 5 seconds).

5.- Because these delays directly affect the lowest layer of Cardano, it ends up affecting all the layers mounted on it.

**Steps to reproduce**
1. Run two relays:
    - Relay A: A non-optimized relay with 16Gb of RAM (using port 6000)
    - Relay B: It doesn't matter as long as it doesn't restart (using port 6000).
2. Link both relays as peers and verify the connections are working.
3. Exhaust the relay's A resources, so it's forced to restart.
4. Once node A restarts, run  `sudo netstat -enp | grep ":6000" | awk {'print $5'} | cut -d ':' -f 1 | sort | uniq -c | sort` in relay B, and you should see the old TCP/IP connections are still open together with the new ones.
5. The amount of connections keeps multiplying on every restart. If the node is connected with 20 other nodes and restarts 4 times, we'd have 100 open connections, of which 80 are completely useless.

**Expected behavior**
Once the relay restarts, the old TCP/IP connections should be cleared or reused.

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version: 20.04 Ubuntu x86_64 GNU/Linux
- Node version: `cardano-node 1.35.3 - linux-x86_64 - ghc-8.10 git rev 950c4e222086fed5ca53564e642434ce9307b0b9` 
- CLI version: `cardano-cli 1.35.3 - linux-x86_64 - ghc-8.10 git rev 950c4e222086fed5ca53564e642434ce9307b0b9`

**Screenshots and attachments**
When I run the command in step 4, this is what I get (I removed the unique connections and bidirectional unique ones). First column is the amount of open connections, second column is the IP address):
```
     10 41.79.70.146
     14 77.174.62.158
     15 142.116.40.190
     27 45.7.230.26
      3 185.156.121.131
      3 51.89.97.17
      4 98.97.12.169
      6 181.239.208.17
      6 54.39.107.148
      8 194.233.79.155
      8 85.242.63.235
```

**Comment by avilsmeier** [comment] 2022-12-12 18:00
I've noticed several incoming connections to my public relays matching the description of this issue. Will o some testing and report back.

**Comment by LatinStakePools** [comment] 2022-12-13 13:09
I've had the same issue. I thought I was being DDoS attack but then realized my own relay (45.7.230.26) was doing the same. I took the action of adding the following IPs to IPtables because the node was getting 500 incoming connections and was not functioning properly. 

`66.94.121.240
173.93.28.12
108.236.80.73
44.238.246.64
3.19.78.159
66.94.119.88
148.72.153.168
62.171.165.103
157.90.251.241
51.195.7.48
213.34.102.83
5.161.114.127
207.244.255.196`

**Comment by rodrigoioyz** [comment] 2022-12-13 22:59
+1 the same Issue over here too

**Comment by scap2000** [comment] 2022-12-14 13:05
+1 Same issue here

![imagen](https://user-images.githubusercontent.com/1715667/207602442-2410012e-c010-44cf-85ec-ceacf765118e.png)
![imagen](https://user-images.githubusercontent.com/1715667/207602734-3857ac3b-a6c2-4065-97bf-859a94a2a79d.png)
![imagen](https://user-images.githubusercontent.com/1715667/207602765-fcec506a-83e3-436c-b1fb-24af188cc100.png)
![imagen](https://user-images.githubusercontent.com/1715667/207602830-724cd487-77e2-4f61-8a4a-9dfeace8639a.png)

**Comment by Bez625** [comment] 2022-12-14 16:07
+1 For #HONEY

We actually noticed this with our own relay to BP at first. We fixed by increasing the memory to stop the restarts, but it would be good if restarting the process didnt keep alive the TCP connections of previous runs.

**Comment by avilsmeier** [comment] 2022-12-14 16:31
I can confirm I see a few zombie connections in all my mainnet relays, even had 2 offenders from my own relays to my BP. :/

**Comment by pabstma** [comment] 2022-12-14 19:26
![grafik](https://user-images.githubusercontent.com/29088060/207692871-9030ecc8-1b9c-40f2-8cca-ce9a09b7ab36.png)

I saw something similar some time ago. Other relays suddenly kept opening connections to my relay. In peak there were over 460 incoming connections. The majority came from around 10 relays which each had 10+ open connections to my relay. Needed to restart the node as it was not responding anymore at that point. 

After this incident, I specifically monitored the IPs of the relays that were causing these connections, but it never happened again, and they are still connected to my relay to this day.

**Comment by coot** [comment] 2022-12-19 18:52
You are running non-p2p nodes, isn't it?  If that's right, can you reproduce this with p2p enabled (for that in `1.35.4` you need `EnableP2P: True` and `TestEnableDevelopmentNetworkProtocols: True`)?

**Comment by dcoutts** [comment] 2022-12-19 22:29
It'd be nice to get more detail on what's actually happening here. It cannot be the case that the new restarted process starts with all the same connections, since that's just not how Linux works.

Can someone clarify if it's the other peer (not the one that restarted) that thinks that the connections are still there, and if so how long they hang around for in this zombie state?

Or if you think it's really the restarted process that has the connections, then again more detail would be helpful.

My guess is that the phenomena people are observing is that when a node dies, its peers do not immediately notice that the connections are dead. The issue is really how long that carries on for.

And as @coot says, knowing if this is in the old non-p2p code or the new p2p code would be very helpful.

**Comment by joseiadicicco** [comment] 2022-12-21 15:15
> You are running non-p2p nodes, isn't it? If that's right, can you reproduce this with p2p enabled (for that in `1.35.4` you need `EnableP2P: True` and `TestEnableDevelopmentNetworkProtocols: True`)?
Dear Marcin:
How are you? First let me tell you that this problem does not happen only to us, it is massive in the whole network, only very few report it, because they confuse it with a DDoS attack and block the addresses from where the multiple connections come, but there are nodes generating zombie connections all over the planet, wasting a huge amount of resources and creating interconnection barriers in a p2p network, which has very serious consequences for the whole network, considering that we are also talking about lower layer, where each delay affects all the upper layers. This bug has been around for a long time, long before the possibility of implementing p2p, but only now we have been able to identify it thanks to having a close relationship with many SPOs (we have even detected fights between SPOs who thought they were being attacked by other SPOs for this very reason). Most of the operators have not yet enabled the P2P function to true, so I do not know if the problem would be solved by enabling that function, but considering that we can not force all nodes to enable that option, we should correct the bug by reviewing the current connection architecture.

**Comment by coot** [comment] 2022-12-21 22:48
^ I fixed formatting of your message.

**Comment by joseiadicicco** [comment] 2022-12-24 20:36
We have been doing some tests from two of the nodes reporting the problem, and when checking the TCP connections established, we see several inconsistencies as can be seen through the Netstat command executed simultaneously on both nodes, there are connections that we can only see them from 1 of the two P2P connected nodes:

![From190 210 100 137](https://user-images.githubusercontent.com/33583361/209450390-fffa0ce5-1c52-4caa-9f8c-77ad0209c7b6.jpg)

![From45 7 230 26](https://user-images.githubusercontent.com/33583361/209450393-7ee577df-d93c-4cfc-b5da-f1a3c97e51d9.jpg)

**Comment by coot** [comment] 2022-12-26 11:08
> there are connections that we can only see them from 1 of the two P2P connected nodes

@joseiadicicco either these nodes are not running P2P or you are explicitly asking to use ephemeral ports.  Is that intentional?

**Comment by joseiadicicco** [comment] 2022-12-31 22:39
@coot both nodes are not running P2P, and are configured without any special configuration.

**Comment by coot** [comment] 2023-01-19 10:47
We decided not to fix this issue, P2P relays will be gradually deployed which will protect the SPOs from such an issue.

**Closed by coot** 2023-01-19 10:47 UTC
Labels: type: bug
