### ISSUE TITLE
[BUG] - GHC generational copy garbage collector causes long pauses and high memory utilization

### ISSUE THREAD

**Issue by orpheus-antpool** [input-output-hk/cardano-node#3216] opened 2021-09-18 18:35 UTC
The default GHC generational copy garbage collector leads to high memory utilization (6GB+) and causes long pauses, which leads to missed slots especially at epoch boundary. 

Switching to the concurrent mark-and-sweep garbage collector and activating all cores (by adding "--non-moving-gc -N" to the RTS options) seems to dramatically reduce memory consumption (down to 4GB) and pauses (significantly less missed slots).

Is there a reason why the default RTS options activate only two cores and use the older GC?

**Comment by seriru** [comment] 2021-09-22 13:16
We ran extensive testing using the mark-and-sweep GC by setting the --nonmoving-gc RTS option. It runs a lot smoother, no missed slots for example, but the node seems to never run a major GC. The node will eventually run out of memory and crash. It behaves like if there is a memory leak when using --nonmoving-gc RTS option. There must be a way to resolve the issue of the node process being temporarily blocked by GC runs, which causes missed slots and node not responding to prometheus requests. Could you advise regarding the mark-and-sweep GC, please?

**Comment by orpheus-antpool** [comment] 2021-09-22 16:35
I found it requires a bit of tweaking, like reducing the factor (-F1.2), allowing idle major collections (-I0.3), keeping the allocation unit  small (-A1M), limiting the heap if you run on 8 GiB (-M7G), keep a minimum heap size to accelerate startup (-H2G). I see around 5  GiB of RSS (effective memory use: touched pages never released back to the OS). 

My suspicion is that the non-moving GC is really competing with new allocations and truly is non-blocking under all circumstances, even if close to the heap limit (if you don't have a limit, it will start swapping). Thus, if it is slower than new allocations, the latter will simply trigger a heap limit exceeded exception and terminate the node. This is likely a design flaw in GHC (new allocations should try a blocking GC instead of instantly giving up). So, to compensate for two things help: call the GC more frequently (which is achieved by activating the idle collections and reducing the factor) and reduce fragmentation due non-moving behavior (which is achieved by lowering the allocation unit). Let me know if this works for you.

**Comment by seriru** [comment] 2021-09-29 11:22
Running one relay with +RTS -N4 -H3G -I0.3 -A1M -F1.2 --disable-delayed-os-memory-return --nonmoving-gc -M11G -RTS and get a coredump.

```
kernel: cardano-node:w[28128]: segfault at 1000000002f ip 00000000018c7332 sp 00007f96abffea90 error 4 in cardano-node[400000+15af000]
kernel: Code: f4 00 00 00 48 3b 1d f5 dc 2c 00 0f 83 e7 00 00 00 48 89 d8 48 89 d9 48 c1 e8 06 48 81 e1 00 00 f0 ff 25 c0 3f 00 00 48 09 c8 <f6> 40 2f 04 0f 85 c4 00 00 00 49 83 c5 01 49 83 c7 20 4d 3b 6c 24
systemd[1]: Created slice system-systemd\x2dcoredump.slice.
systemd[1]: Started Process Core Dump (PID 28129/UID 0).
systemd-coredump[28130]: Core file was truncated to 2147483648 bytes.
systemd-coredump[28130]: Process 27824 (cardano-node) of user 0 dumped core.
                                                            
                                                            Stack trace of thread 156:
                                                            #0  0x00000000018c7332 n/a (/nix/store/xbq4yynx9my6ysggvmam2a27cr5i4pgc-cardano-node-exe-cardano-node-1.30.1/bin/cardano-node)
Sep 29 11:12:28 relay2.xor-nand.io systemd[1]: systemd-coredump@0-28129-0.service: Succeeded.
```

**Comment by orpheus-antpool** [comment] 2021-09-29 18:17
Unfortunately this stack trace is not useful. How did you compile cardano-node (ghc version, options used)?

**Comment by seriru** [comment] 2021-09-30 08:15
Using the official docker container v 1.30.1.

**Comment by orpheus-antpool** [comment] 2021-09-30 16:07
> Using the official docker container v 1.30.1.

This was probably built using GHC 8.10.4, there are stability and bug fixes to the non-moving GC since then. You should build with 8.10.7.

**Comment by seriru** [comment] 2021-10-03 10:14
It crashes after build on ghc 8.10.7 as well. The issue is -I0.3. If omitted it's working fine for a while but continues to increase RAM usage.

```
kernel: cardano-node:w[257572]:  segfault at 38 ip 0000000003f3de13 sp 00007f1453877910 error 6 in cardano-node[400000+3cf1000]
kernel: Code:  48 3b 5c 24 28 75 d0 48 83 3d b0 e5 81 00 00 0f 85 b3 00 00 00 49 8b 45 28 48 8b 50 10 48 8b 48 18 48 81 fa 28 82 75 04 74 04 <48> 89 4a 18 48 81 f9 28 82 75 04 74 61 48 89 51 10 49 8b 94 24 48
```

**Comment by orpheus-antpool** [comment] 2021-10-04 04:40
Hmm, I never experienced this issue before. In any case, you can add -I0.3 -Iw1800, this will make sure the idle GC is not called more than once every 30min and you should see the live data size decreasing.

**Comment by 34r7h** [comment] 2021-11-08 12:10
https://forum.cardano.org/t/solving-the-cardano-node-huge-memory-usage-done/67032

**Comment by Jimbo4350** [comment] 2022-10-27 08:34
Closing this. If this is still relevant please reopen.

**Closed by Jimbo4350** 2022-10-27 08:34 UTC
Labels: bug
