### ISSUE TITLE
[BUG] - Resource exhausted error on parallel querying the testnet node (Bug or Intended behavior?)

### ISSUE THREAD

**Issue by nabin6246** [input-output-hk/cardano-node#3492] opened 2022-01-11 07:02 UTC
External otherwise.

**Area**
Other : Cardano test node query

**Summary**
I was trying to measure the concurrent performance of a nft market place. When querying the testnet node in parallel it fails to give response to some of the query requests. This issue can be  basically reproduced by running background sub-processes in bash for querying the node.
Some processes fails with error : 
For command 
`for x in {1..20} ; do cardano-cli query utxo --address $(cat default.addr) --testnet-magic 1097911063 & done;`

Some processes return
`
cardano-cli: Network.Socket.connect: <socket: 11>: resource exhausted (Resource temporarily unavailable)`

**Steps to reproduce**
1. Start the cardano node with testnet configuration.
2. Run the following bash command for your own address e.g default.addr is used in below command
`for x in {1..20} ; do cardano-cli query utxo --address $(cat default.addr) --testnet-magic 1097911063 & done;`
3. See below error for number of sub processes

`
cardano-cli: Network.Socket.connect: <socket: 11>: resource exhausted (Resource temporarily unavailable)`
`[1]   Done                    cardano-cli query utxo --address $(cat default.addr) --testnet-magic 1097911063`
`[2]   Exit 1                  cardano-cli query utxo --address $(cat default.addr) --testnet-magic 1097911063`
`[4]   Done                    cardano-cli query utxo --address $(cat default.addr) --testnet-magic 1097911063 ... And so on with multiple fails and passes.
`
Above we can see some process are returning exit 1 with failed condition.

**Expected behavior**
Is it intended behavior as not to overload the node with bombarding of request or is it a bug?
Expected behavior would be all query returns utxos successfully eventually.

**System info:**
- OS Name - [Linux Mint]
- OS Version - [20.1]
- Node version - 1.33.0
- CLI version  - 1.33.0

**Screenshot**
![image](https://user-images.githubusercontent.com/18091631/148896083-0fa0d215-d0ef-4bf9-99bd-eb9fcc5124f8.png)

**Comment by nabin6246** [comment] 2022-06-16 06:21
Now on vasil testnet running the following commands shutdowns the node.
for x in {1..20000}; do cardano-cli query tip --testnet-magic 9 & done;

**Comment by Jimbo4350** [comment] 2022-10-27 08:41
Closing this. If this is still relevant please reopen.

**Closed by Jimbo4350** 2022-10-27 08:41 UTC
Labels: bug, user type: external, comp: cardano-cli, release: 1.33.0

**Comment by infrmtcs** [comment] 2023-02-16 06:10
@Jimbo4350 I'm running `inputoutput/cardano-node` 1.35.5 docker image and can also reproduce the issue above by running `cardano-cli` inside the docker container. Is this an intended behaviour, or can we somehow configure max number of connections?
