### ISSUE TITLE
remove out of date config files

### ISSUE THREAD

**Issue by paradoxicalsphere** [input-output-hk/cardano-node#4415] opened 2022-09-04 23:48 UTC
With the release of https://github.com/input-output-hk/cardano-node/releases/tag/1.35.3-configs please remove links to out of date configuration files from https://book.world.dev.cardano.org/environments.html

**Comment by dorin100** [comment] 2022-09-05 04:53
duplicate of https://github.com/input-output-hk/cardano-node/issues/4406

**Comment by Jimbo4350** [comment] 2022-10-31 14:21
Closing because this is a duplicate of #4406

**Closed by Jimbo4350** 2022-10-31 14:21 UTC
Labels: type: documentation, user type: external
