### ISSUE TITLE
cardano-node expects SIGINT not SIGTERM for graceful shutdown

### ISSUE THREAD

**Issue by nyetwurk** [input-output-hk/cardano-node#2627] opened 2021-04-19 06:31 UTC
`docker stop` does not politely shut down the cardano-node container built by:

https://github.com/input-output-hk/cardano-node/blob/9088aacfae5c46a8b4bd4ed056f8e37d7cf42811/nix/docker.nix#L100

This is because cardano-node expects SIGINT, not SIGTERM (the docker default).

In a Dockerfile, this can be overridden by `STOPSIGNAL`, but nix-docker doesn't seem to be aware that is an option.

`docker kill -s INT` isn't useful, since it doesn't fall back on KILL if it fails, and it also exits immediately, which means you need to do a `docker wait`... which is useless because docker, in their infinite wisdom, don't have a timeout option for wait.

Then again, you'd think they'd add a `--signal` option for `docker stop` and `docker restart`.

**Comment by nyetwurk** [comment] 2021-04-19 06:43
It's possible something like
```
config = {
      EntryPoint = [ "${entry-point}/bin/entry-point" ];
      StopSignal = "TERM";
    };
```
may work

**Comment by nyetwurk** [comment] 2021-04-19 06:45
It would be nice if `EntryPoint` was a bit more deterministic to make it easier to wrap.

Even better `${entry-point}` could have a symlink in `/usr/lib/` pointing to it or something.

**Comment by nyetwurk** [comment] 2021-04-19 22:26
Something like this worked for me to create something hookable:
```
ARG version=1.26.2
FROM inputoutput/cardano-node:${version}

RUN mkdir -p /usr/local/bin
RUN ln -s $(ls -1 /nix/store/*-entry-point/bin/* /nix/store/*-cardano-node-*/bin/*) /usr/local/bin/
```

**Comment by tdiesler** [comment] 2021-04-22 05:03
This is a duplicate of #2353 which would be fixed by PR #2608.

In the meantime, you can use  the [nessusio/cardano-node](https://hub.docker.com/r/nessusio/cardano-node) image which is a multiarch clone of the IOHK image that among other things also fixes this issue.

**Comment by nyetwurk** [comment] 2021-04-22 05:11
Curious why cardano-node doesn't just natively trap SIGINT?

**Comment by tdiesler** [comment] 2021-04-22 05:29
This might be a question best answered by cardano-node itself.

As it stands now, substantial improvements to the cardano-node docker image are available and have been for months. From my part the proposal can be adopted, partially adopted or rejected for a better proposal. It is also not a conclusive proposal that claims to set things in stone. Instead it proposes a number of small iterative steps to the cardano-node image, which over time can be modified and expanded on by folks who like to contribute to the cardano project with their domain knowledge.

Perhaps they are not adopting because of legal issues (i.e. a suitable contributor agreement). 
Anyway, the ball is with IOHK.

**Comment by juampe** [comment] 2021-04-25 11:46
I solved this issue with "STOPSIGNAL SIGINT"  statement in Dockerfile
https://github.com/juampe/cardano-docker

**Comment by tdiesler** [comment] 2021-04-25 12:03
@juampe Yes, we are likely going to do this as well in the Nix build

* [#49](https://github.com/tdiesler/nessus-cardano/issues/49) Simplify stop signal handling by using SIGINT directly

**Comment by nyetwurk** [comment] 2021-07-09 19:42
https://github.com/input-output-hk/cardano-node/commit/952ce084373908f275110f57a43cea338604c4b3

**Comment by tdiesler** [comment] 2021-07-28 17:55
This should be out of date

**Comment by nyetwurk** [comment] 2021-07-28 18:04
In which version is it released? I have a workaround for it in our CI and need to know on which versions it is no longer needed.

**Comment by nyetwurk** [comment] 2021-07-28 18:05
> I solved this issue with "STOPSIGNAL SIGINT" statement in Dockerfile
> https://github.com/juampe/cardano-docker

This is the same workaround I am using.

**Comment by tdiesler** [comment] 2021-07-28 18:05
It'll be in 1.28.0

**Comment by jterrier84** [comment] 2022-03-13 20:38
Is the solution with "STOPSIGNAL SIGINT" in the dockerfile still valid for version 1.34.1? I used it but my container is not stopping gracefully. My dockerfile is this one: https://github.com/jterrier84/Cardano-node-docker/blob/master/dockerfiles/armada-cn-arm64.dockerfile. Would appreciate your help.

**Comment by Jimbo4350** [comment] 2022-10-27 08:17
Closing this. If this is still relevant please reopen.

**Closed by Jimbo4350** 2022-10-27 08:17 UTC
