### ISSUE TITLE
[BUG] - cardano-cli query kes-period-info

### ISSUE THREAD

**Issue by Eggham** [input-output-hk/cardano-node#4246] opened 2022-07-30 15:07 UTC
**External**

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
I ran the following command in my block producing node, trying to determining the counter value:
```
cardano-cli query kes-period-info \
  --mainnet \
  --op-cert-file node.cert
```
It produced the output as follows:
```
✓ The operational certificate counter agrees with the node protocol state counter
✗ Node operational certificate at: node.cert has an incorrectly specified KES period. 
The operational certificate's specified KES period is outside of the current KES period interval.
KES period interval start: 496
KES period interval end: 558
Operational certificate's specified KES period: 466
```
However my block producing node has been working fine using the `node.cert`. All scheduled blocks have been successfully produced using the `node.cert`.

**Steps to reproduce**
See above.

**Expected behavior**
Expected output would look like:
```
✓ Operational certificate's KES period is within the correct KES period interval
✓ The operational certificate counter agrees with the node protocol state counter
{
    "qKesCurrentKesPeriod": 15,
    "qKesEndKesInterval": 18,
    "qKesKesKeyExpiry": null,
    "qKesMaxKESEvolutions": 6,
    "qKesNodeStateOperationalCertificateNumber": 3,
    "qKesOnDiskOperationalCertificateNumber": 3,
    "qKesRemainingSlotsInKesPeriod": 690,
    "qKesSlotsPerKesPeriod": 300,
    "qKesStartKesInterval": 12
}
```

**System info (please complete the following information):**
- OS Name: [Ubuntu]
- OS Version [20.04]
- Node version
   cardano-node 1.34.1 - linux-x86_64 - ghc-8.10
   git rev 73f9a746362695dc2cb63ba757fbcabb81733d23
- CLI version  
    cardano-cli 1.34.1 - linux-x86_64 - ghc-8.10
   git rev 73f9a746362695dc2cb63ba757fbcabb81733d23

**Screenshots and attachments**
See above

**Additional context**
None

**Comment by cardistack** [comment] 2022-08-02 15:02
I have same issue +1

**Comment by BridaNewb** [comment] 2022-08-08 23:47
I have the same issue.
1.34.1
My kes numbers are slightly different at 496/558/469 but same exact output otherwise.

How did you end up rotating kes?

**Comment by JaimeToca** [comment] 2022-08-09 07:58
I got the same output,  rotated the keys, and had no issues. Everything is fine and minting blocks.

**Comment by BridaNewb** [comment] 2022-08-09 08:07
Thanks. I went ahead with mine also. I will find out tomorrow if mint went successful but everything else seems normal so far

**Comment by simpliste** [comment] 2022-08-10 12:11
Having the same issue and indeed also have had no problem minting blocks so far.

**Comment by rphair** [comment] 2022-08-13 23:19
This is a duplicate of https://github.com/input-output-hk/cardano-node/issues/3689 which was closed as "fixed" because the fix had been included in IOHK's development branch (several weeks before this issue was opened).

**Comment by joseiadicicco** [comment] 2022-08-21 16:30
Same for me, my BP is working perfectly (minting blocks), but the command shows:
✓ The operational certificate counter agrees with the node protocol state counter
✗ Node operational certificate at: node.cert has an incorrectly specified KES period. 
The operational certificate's specified KES period is outside of the current KES period interval.
KES period interval start: 496
KES period interval end: 558
Operational certificate's specified KES period: 477

Aparently, there is a bug in the query formula.

System info:
KES current/remaining             : 536 / 3
KES expiration date               : 2022-08-25 09:44:51 UTC  

    OS Name: [Ubuntu]
    OS Version [20.04]
    Node version
cardano-cli 1.34.1 - linux-x86_64 - ghc-8.10
git rev 73f9a746362695dc2cb63ba757fbcabb81733d23

cardano-node 1.34.1 - linux-x86_64 - ghc-8.10
git rev 73f9a746362695dc2cb63ba757fbcabb81733d23

**Comment by newhoggy** [comment] 2023-02-23 09:51
Can this issue be closed?

**Comment by rphair** [comment] 2023-02-26 16:36
I understand from prior discussion this was fixed a while ago & I can personally confirm as an SPO that the values in `curl -s 127.0.0.1:12798/metrics | grep -i kes` match the ones in `cardano-cli query kes-period-info --mainnet --op-cert-file node.cert` nicely.

**Comment by newhoggy** [comment] 2023-02-27 03:41
Thanks!  If this is remains an issue, please re-open.

**Closed by newhoggy** 2023-02-27 03:41 UTC
Labels: bug, Vasil, type: bug, user type: external, comp: cardano-cli, area: kes-info, era: babbage, tag: 1.34.1
