### ISSUE TITLE
[BUG] - cardano-node 1.18.1 failed on MC4

### ISSUE THREAD

**Issue by onyxstakepool** [input-output-hk/cardano-node#1676] opened 2020-08-12 15:02 UTC
*External*   otherwise.

**Summary**
Cardano node failed after upgrade to 1.18.1 on MC4.

```
cardano-node: reapplyLedgerBlock At (Block {blockPointSlot = SlotNo {unSlotNo = 44373}, blockPointHash = b189bf576c5f61774aeca20a9fe8402403d3ebb4323ff3f7a274a095167c4afb}): HeaderProtocolError (HardForkValidationErrFromEra S (Z (WrapValidationErr {unwrapValidationErr = ChainTransitionError [OverlayFailure (VRFLeaderValueTooBig (OutputVRF {getOutputVRFBytes = "\ENQ\203\161A\199JR\SI\203\197\228B\156\209\226\168\238\ng\154\246x9\t*\222Z<+\b\211\204\198\\*\DC3\229h'\rF\191 \177E}\216\214B\a\v\238\155\&95\204\&6\220)\166w\181\185\199"}) (0 % 1) (ActiveSlotCoeff {unActiveSlotVal = UnsafeUnitInterval (1 % 20), unActiveSlotLog = -512932943875505334261962382072846}))]})))                                                                                                                    peers:           0         │    
CallStack (from HasCallStack):                                                                                                                                 │    
  error, called at src/Ouroboros/Consensus/Ledger/Extended.hs:200:19 in ouroboros-consensus-0.1.0.0-inplace:Ouroboros.Consensus.Ledger.Extended                │    
  reapplyLedgerBlock, called at src/Ouroboros/Consensus/Ledger/Abstract.hs:95:7 in ouroboros-consensus-0.1.0.0-inplace:Ouroboros.Consensus.Ledger.Abstract
```

**Steps to reproduce**
1. Start cardano-node 1.18.1 as block producer on mainnet-candidate-4 network

**Expected behavior**
Normal operation of the block producing node.

**System info (please complete the following information):**
- OS: Ubuntu
- Version 20.04
- Node version
```
cardano-cli 1.18.1 - linux-x86_64 - ghc-8.6
git rev a4b6dae699fa21dc3c025c8a83d1718475cb3afc

cardano-node 1.18.1 - linux-x86_64 - ghc-8.6
git rev a4b6dae699fa21dc3c025c8a83d1718475cb3afc
```

**Additional context**
It could be a coincidence or different bug: 
After the incident above the stake pools in Daedalus 1.6.0-STN5 are again ordered by pool hash instead of performance.
Did cardano-node 1.18.1 introduce a blockchain corruption?

**Comment by disassembler** [comment] 2020-08-12 23:36
MC4 is in the process of being retired. There's a known bug in 1.18.0 that we've mitigated on mainnet from making it to the block chain.

**Comment by mark-stopka** [comment] 2020-08-13 04:17
> MC4 is in the process of being retired. There's a known bug in 1.18.0 that we've mitigated on mainnet from making it to the block chain.

Should that not be mentioned in the release log as a known issue then? I mean testing on a test environment prior to production deployment should be part of the update procedure for every serious pool operator...

**Comment by AndrewWestberg** [comment] 2020-08-13 16:18
This is scary to re-open this issue. Can we get any status update? Has this issue been reproduced internally?

**Comment by latheesan-k** [comment] 2020-08-14 00:18
So this error happened to me today. I was in process of adding new relay yesterday, so i started off with a clean install of 1.18.1 and had it syncing overnight.

Today when I wanted to work on it, it was fully synced and was already at epoch 210 (I transitioned through the epoch boundary with 1.18.1)  and then I was notified about the announcement to not use the 1.18.1. 

Since it's a new relay (not in use), i shut it down and checked out 1.18.0 (tag) and re-compiled and when I started the node up, I got this error in the logs:

```
{
  "at": "2020-08-13T23:04:32.75Z",
  "env": "1.18.0:ba0f9",
  "ns": [
    "cardano.node.ErrorPolicy"
  ],
  "data": {
    "event": "ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (HeaderError (At (Block {blockPointSlot = SlotNo {unSlotNo = 5789249}, blockPointHash = 68914f093daebff961def6df4830a21b2fffccec69442e8e6b780e51c40d5217})) (HeaderProtocolError (HardForkValidationErrFromEra S (Z (WrapValidationErr {unwrapValidationErr = ChainTransitionError [OverlayFailure (VRFLeaderValueTooBig (OutputVRF {getOutputVRFBytes = \"\\NUL\\NUL\\157\\185\\199\\189l\\210Y\\130\\175\\220\\248\\140\\242\\129\\&4!\\138\\193\\175\\235\\238c*h(\\\\\\187\\156Y3\\239\\204lYMF\\160\\239F.>S\\248\\193l\\CAN\\162\\181\\204\\147\\241\\EOT\\183\\182P{R`z\\200vM\"}) (0 % 1) (ActiveSlotCoeff {unActiveSlotVal = UnsafeUnitInterval (1 % 20), unActiveSlotLog = -512932943875505334261962382072846}))]})))) (Tip (SlotNo {unSlotNo = 5789244}) 9c925a40b21eb2768f2b07733568f7bd9dbfe74848f0b29755b9e8a230b4f43e (BlockNo {unBlockNo = 4555199})) (Tip (SlotNo {unSlotNo = 5793577}) 9e188f28510fc9b6f7d5f622e5902dcd6ff21dbf74cf37bfa375f9e8deaae993 (BlockNo {unBlockNo = 4555416}))))) 200s 200s",
    "kind": "ErrorPolicyTrace",
    "address": "3.23.235.130:3001"
  },
  "app": [],
  "msg": "",
  "pid": "84390",
  "loc": null,
  "host": "vps-fff6",
  "sev": "Warning",
  "thread": "627"
}
```
The whole time, i had the default topology for the main net (i.e. only IOHK relays) and i had 0 peers (after downgrading back to 1.18.0). 

I ended up having to delete the whole db/* folder and restarted the sync with 1.18.0 - now I got peers (2 from IOHK relay).

**Comment by disassembler** [comment] 2020-08-14 01:47
If you still have the state, you just need to remove the volatile and ledger state and let it rebuild rather than wiping the whole db and resyncing from scratch.

**Comment by disassembler** [comment] 2020-08-14 01:48
> This is scary to re-open this issue. Can we get any status update? Has this issue been reproduced internally?

Yes, this issue was reproduced this morning and we pulled 1.18.1 as soon as we identified where the issue was and that it wasn't an easy fix that we could complete and get distributed before the epoch boundary. Better safe than sorry. We'll have the performance improvements in an upcoming node release at some point in the future.

**Comment by JaredCorduan** [comment] 2020-08-14 17:53
Thank you very much for raising this issue @onyxstakepool , it was extremely helpful to have something reproducible. this issue is closed by https://github.com/input-output-hk/cardano-ledger-specs/pull/1784

**Closed by JaredCorduan** 2020-08-14 17:53 UTC
Labels: bug, priority high

**Comment by rphair** [comment] 2020-08-19 09:59
We had run `1.18.1` for about 24 hours in the last epoch, and rolled back to `1.18.0` about a day after the rollback announcement.  We didn't observe any difficulties until this last epoch boundary, at which our relays stopped syncing with these errors, reported repeatedly for every peer:
```
[relay-ny:cardano.node.DnsSubscription:Error:53946]
[2020-08-19 08:15:50.04 UTC]
[String "Application Exception: 54.201.36.182:6000 HeaderError
  (At (Block {blockPointSlot = SlotNo {unSlotNo = 6221024}, blockPointHash = ...}))
  (HeaderProtocolError (HardForkValidationErrFromEra S (Z (WrapValidationErr
    {unwrapValidationErr = ChainTransitionError [OverlayFailure (VRFLeaderValueTooBig
      (OutputVRF {getOutputVRFBytes = \"..."}) (3334337931 % 4383606254572)
      (ActiveSlotCoeff {unActiveSlotVal = UnsafeUnitInterval (1 % 20), unActiveSlotLog = ...})
    )]}))))
  (Tip (SlotNo {unSlotNo = 6230299}) ... (BlockNo {unBlockNo = 4576507}))
  (Tip (SlotNo {unSlotNo = 6258650}) ... (BlockNo {unBlockNo = 4578327}))",
 String "SubscriptionTrace",
 String "\"node1.stakelove.com\""]
```
The [consensus on the forum](https://forum.cardano.org/t/relays-out-of-sync-headerprotocolerror-chaintransitionerror-vrfleadervaluetoobig/38796) is to blow away the DB and rebuild the chain from genesis.  I've saved the log files for the last epoch as well as the corrupted DB in case they would be useful to anyone.
