### ISSUE TITLE
[BUG] - Synchronization is too slow

### ISSUE THREAD

**Issue by satonz** [input-output-hk/cardano-node#1985] opened 2020-10-15 03:26 UTC
After 90% of the node data is synchronized, the synchronization speed becomes extremely slow

**Comment by erikd** [comment] 2020-10-23 01:44
@satonz What does "slow" mean? An hour, a year? How long did it take for 90% of the data? How do you figure its 90%, is that 90% of the tip block height?

For the node to sync from scratch I expect syncing to take 1-2 hours on a standard desktop machine with a decent internet connection.

**Comment by andrejpodzimek** [comment] 2021-04-01 06:18
On my (above) standard desktop machine, synchronization hasn’t completed for a week or so and is stuck slightly above 23%, as reported in #2559. My personal definition of *slow* would be a decade or so, which is what it would take at the current pace. Something is broken in the communication with peers with lots of `...closed when reading data...` messages.

**Comment by erikd** [comment] 2021-04-01 06:55
@andrejpodzimek This is almost certainly a problem with *your* internet connection. With a decent internet connection, full sync from scratch should be under 4 hours.

**Comment by erikd** [comment] 2021-04-01 10:35
Ok, your machine and network connection seem highly capable. My connection is nowhere near as good and neither is my machine. However, on my machine (or rather a VM running on my machine) I can download the whole chain in well under 4 hours.

**Comment by andrejpodzimek** [comment] 2021-04-01 18:06
Up until the ~23% that I managed to sync, it was quite fast and it looked like a full sync would be done in units of hours at most. But then _something_ happened and it got stuck. It‘s unclear to me what that _something_ could have been.

I’m considering a deletion of the whole database and a re-sync, but that’s definitely not a good way to find the root cause of this.

**Comment by erikd** [comment] 2021-04-01 22:33
Have you tried just restarting it? There is a chance you initially connected to one or more very poor nodes. If you restart it, it is likley to pick up new difference peers.

**Comment by francisco-olea** [comment] 2021-04-02 07:57
Hi, I have the exact same issue after 25 million slots. I have tried:

- Restarting everything
- Starting all over again
- Trying different networks
- Connecting over 50+ different nodes (outcome: same speed)
- Deleting db

None of them worked. It is clear that the speed at the beginning its fine but not optimal. As @andrejpodzimek when I reach ~23% it gets stuck... around 6 kb/s for me at least. I wrote on Cardano forum and the best idea was to sync with other nodes but as I said, every single one of them had the same speed.

**Comment by erikd** [comment] 2021-04-02 11:05
Ok, need more information about this.

* What version of the node are you running (version, git tag or git hash)?
* How was it built?
* Where are you getting the config file from?

**Comment by mrbrinker** [comment] 2021-04-02 13:06
@francisco-olea from experience to bootstrap a node the less peers you have in your topology file the quicker. I would suggest you try with one or two and see how it goes.

**Comment by andrejpodzimek** [comment] 2021-04-02 17:35
@erikd Yes, I’ve tried restarting it and also [a number of other random trial-and-error steps](https://github.com/input-output-hk/cardano-node/issues/2559#issuecomment-812303575), but nothing helped. My most recent tweak was to set `valency` to 16 (for `relays-new.cardano-mainnet.iohk.io` in `mainnet-topology.json`). Now, while I do see 16 connections in `netstat -atpn`, it’s still stuck. After my last database deletion and reset, it froze at 23.3% this time.

**Comment by andrejpodzimek** [comment] 2021-04-02 17:44
> * What version of the node are you running (version, git tag or git hash)?

`1.26.1`. (But `1.25.1` had the same issue. The only reason why I tried `1.26.1` was to make sure I’m not reporting something that’s already fixed.)

> * How was it built?

Using [this package](https://aur.archlinux.org/packages/cardano-node/), just with `s/1\.25\.1/1.26.1/` in `PKGBUILD`.

> * Where are you getting the config file from?

Also from [the package](https://aur.archlinux.org/packages/cardano-node/); they are linked directly in the package overview. Their current source links are:
* [`mainnet-topology.json`](https://hydra.iohk.io/build/5367762/download/1/mainnet-topology.json) (I now have `valency` set to 16 in this. I haven’t chantged anything else, also because I don’t have a block-signing node configured (yet).)
* [`mainnet-config.json`](https://hydra.iohk.io/build/5367762/download/1/mainnet-config.json) (I haven’t changed anything here or below.)
* [`mainnet-shelley-genesis.json`](https://hydra.iohk.io/build/5367762/download/1/mainnet-shelley-genesis.json)
* [`mainnet-byron-genesis.json`](https://hydra.iohk.io/build/5367762/download/1/mainnet-byron-genesis.json)

**Comment by francisco-olea** [comment] 2021-04-02 18:05
@erikd Same as @andrejpodzimek .

[Cardano-cli](https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/install.md/) version: 1.26.1.
[Package](https://docs.cardano.org/projects/cardano-node/en/latest/stake-pool-operations/getConfigFiles_AND_Connect.html)
I have only changed `mainnet-topology.json` to different addresses. @mrbrinker I put one at a time, still the same result. I have changed valency up to 4 but not 16 though.

Also I attach the sync speed timeline.

![timeline2](https://user-images.githubusercontent.com/67300003/113441188-b4121100-93a2-11eb-9d0c-68eaac195474.PNG)

**Comment by andrejpodzimek** [comment] 2021-04-02 21:21
Yet another possible cause ruled out: Some [`systemd` unit examples](https://forum.cardano.org/t/systemd-service-file-for-cardano-node/33490) suggest an increase to the file descriptor limit. The default `LimitNOFILE` is 1024 on my system. So I’ve just set 32768 to try it out and verified with `prlimit -p $(pidof cardano-node)` that it took effect.

No change, unfortunately: Cardano actually uses way below 100 file descriptors most of the time (says `lsof -p $(pidof cardano-node)` and synchronization is still as stuck as ever before.

**Comment by erikd** [comment] 2021-04-02 22:48
Is there anything suspicious in the logs?

**Comment by andrejpodzimek** [comment] 2021-04-02 23:00
> Is there anything suspicious in the logs?

The usual warnings every now and then. Once they appear, they seem to be somewhat correlated with the slowness. 

```
[charon:cardano.node.ErrorPolicy:Warning:258] [2021-04-02 22:52:27.48 UTC] IP xxx.xxx.xxx.xxx:39208 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (MuxError MuxBearerClosed "<socket: 38> closed when reading data, waiting on next header True"))) 20s 20s
[charon:cardano.node.ErrorPolicy:Warning:258] [2021-04-02 22:52:32.52 UTC] IP xxx.xxx.xxx.xxx:50768 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (MuxError MuxBearerClosed "<socket: 48> closed when reading data, waiting on next header False"))) 20s 20s
[charon:cardano.node.ErrorPolicy:Warning:258] [2021-04-02 22:52:38.58 UTC] IP xxx.xxx.xxx.xxx:57686 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (MuxError MuxBearerClosed "<socket: 48> closed when reading data, waiting on next header False"))) 20s 20s
```

Otherwise there are lots of `Notice`s (e.g. new tip) and very few `Info`s. The `Chain extended` messages are more frequent than anything else:

```
[charon:cardano.node.ChainDB:Notice:234] [2021-04-02 22:46:47.50 UTC] Chain extended, new tip: 3b3d44792ed5153623e57dc67e8deed010c7817563a55346192c742ac61386a1 at slot 25837316
[charon:cardano.node.ChainDB:Info:234] [2021-04-02 22:46:47.66 UTC] Block fits onto some fork: e2533a3cd8575334743b6e34222878acea7542b1a5fbea354197916d1acca56c at slot 25837314
[charon:cardano.node.ChainDB:Info:234] [2021-04-02 22:46:47.66 UTC] Valid candidate e2533a3cd8575334743b6e34222878acea7542b1a5fbea354197916d1acca56c at slot 25837314
```

**Comment by andrejpodzimek** [comment] 2021-04-02 23:05
> Is there anything suspicious in the logs?

Actually, not sure why I haven’t grep’d for `Error`s explicitly. Here are some specimen:

```
[charon:cardano.node.DnsSubscription:Error:1977] [2021-04-02 22:04:10.98 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Application Exception: xxx.xxx.xxx.xxx:3001 ExceededTimeLimit (ChainSync (Header (HardForkBlock (': * ByronBlock (': * (ShelleyBlock (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Allegra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Mary StandardCrypto)) ('[] *))))))) (Tip HardForkBlock (': * ByronBlock (': * (ShelleyBlock (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Allegra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Mary StandardCrypto)) ('[] *))))))) (ServerAgency TokNext TokMustReply)
[charon:cardano.node.DnsSubscription:Error:2103] [2021-04-02 22:46:04.94 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Application Exception: xxx.xxx.xxx.xxx:3001 MuxError MuxBearerClosed "<socket: 68> closed when reading data, waiting on next header True"
```

**Comment by francisco-olea** [comment] 2021-04-02 23:29
> Is there anything suspicious in the logs?

Just `Info` and `Notice`, I get `ErrorPolicy:Notice:80` but still getting `Chain extended`.

`[relay-no:cardano.node.DnsSubscription:Notice:113]  [2021-04-02 23:08:30.93 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Connection Attempt Start, destination 35.158.3.162:3001`
`[relay-no:cardano.node.ChainDB:Notice:61]  [2021-04-02 23:08:30.94 UTC] Chain extended, new tip: 234929eb62e6ef12471bb4d5dd2949c497e7bdf79c9f29291bd284794a8fd141 at slot 25837901`
`[relay-no:cardano.node.DnsSubscription:Notice:98]  [2021-04-02 23:08:30.96 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Connection Attempt End, destination 3.18.83.182:3001 outcome: ConnectSuccessLast`
`[relay-no:cardano.node.ErrorPolicy:Notice:80]  [2021-04-02 23:08:30.96 UTC] IP 35.177.89.129:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = "Parallel connection cancelled", seStack = []}))) 1s`

**Comment by erikd** [comment] 2021-04-03 06:16
I am currently synching my node from scratch. It has been running for about 6 hours and is currently at epoch 237 (about 20 epoch until it has caught up to the tip). This is slower than I remember it, but is has been some time since I synced a node from scratch,

Also is this related? https://github.com/input-output-hk/cardano-node/issues/2222

**Comment by francisco-olea** [comment] 2021-04-03 06:34
> I am currently synching my node from scratch. It has been running for about 6 hours and is currently at epoch 237 (about 20 epoch until it has caught up to the tip). This is slower than I remember it, but is has been some time since I synced a node from scratch.

Are you running `cardano-cli` version `1.26.1`?

**Comment by erikd** [comment] 2021-04-03 08:12
Yes `1.26.1` of both the node and cli. By the way see https://github.com/input-output-hk/cardano-node/issues/2559 .

**Comment by francisco-olea** [comment] 2021-04-03 23:14
> Yes `1.26.1` of both the node and cli. By the way see #2559 .

Yeah, I followed #2559 and got

    CARDANO_NODE_SOCKET_PATH=~/Pool/relay/db/node.socket cardano-cli query tip --mainnet
    {
         "epoch": 257,
         "hash": "35c1c274c45b0edb1f22935aee04eb3cb1eb756ec7b1c0a3157cf4cbee7adb0c",
         "slot": 25924913,
        "block": 5545895
    }

so is fully synced. Thanks!

**Comment by erikd** [comment] 2021-04-04 00:07
Ok, closing this. Thanks1

**Closed by erikd** 2021-04-04 00:07 UTC
Labels: bug
