### ISSUE TITLE
[BUG]  [cardano-api] - Utxo Redeemer Pointer mismatch in TxBody 

### ISSUE THREAD

**Issue by mesudip** [input-output-hk/cardano-node#3389] opened 2021-11-25 13:23 UTC
**External** : Plutus Partners

I have very grim about anybody here, reading this issue, but here it goes..

**Context :**
When trying to redeem from script in a complex transaction I got following error.
```
ShelleyTxValidationError ShelleyBasedEraAlonzo (
    ApplyTxError [
     UtxowFailure (ExtraRedeemers [RdmrPtr Spend 2]),
     UtxowFailure (MissingRedeemers [(Spending (TxInCompact (TxId {_unTxId = SafeHash "f1faf6f98e39c5b4b1a2fd544df64117213fa0b09740afe33b3de45f170da68a"}) 0),ScriptHash "a75abe73708b263d086f9b0d298dcaddff37c0892e9425675a6d26e9")
])
```

**Reason :**
in `makeTransactionBody` function, the `txins` are `mapped`  to Shelley with the following function
```haskell
Set.fromList (map (toShelleyTxIn . fst) txIns
```
It should be noted that the newly constructed set may not have the `txIns` in same order because the data are different.

But to calculate RedeemerPtr in the redeemers, the `txIns` are directly used in previous order

**Workaround For Now :**
Before calling `makeTransactionBody` , reorder the `txIns` in `TxBodyContent`
```haskell
reorderInputs :: [(TxIn, a)] -> [(TxIn,a)]
reorderInputs txIns = map ((\key-> (key,forceJust $ Map.lookup key  mapped)) . fromShelleyTxIn) ordered
  where
    ordered =  Set.toList $  Set.fromList (map (toShelleyTxIn . fst) txIns)
    mapped = Map.fromList txIns
    forceJust (Just a) = a
```

**Comment by vsubhuman** [comment] 2022-02-17 14:39
same

**Comment by vsubhuman** [comment] 2022-02-17 14:49
I think the problem is that there's no way for nodes to recognize which redeemer is for which script-input. For example, if there are two script-inputs and two redeemers in the witnesses - nodes have no way to somehow match a redeemer to a script, except matching them by order.

Although it's definitely feels like a problem that nodes don't skip non-script inputs, so even if there's a single script input at all - it always MUST be on the very first position, or it will never get matched with the redeemer.

**Comment by vsubhuman** [comment] 2022-02-17 15:01
Feels like a logical convention would be to require for there to be same number of redeemers as there are script inputs and for the redeemers to be in the same order as **script inputs** in the input list, but not necessarily match inputs and redeemers index-to-index - i.e. redeemer on index `0` is assumed to be for the input on index `0` - this is how it works atm.

**Comment by KtorZ** [comment] 2022-02-17 16:39
>  think the problem is that there's no way for nodes to recognize which redeemer is for which script-input. For example, if there are two script-inputs and two redeemers in the witnesses - nodes have no way to somehow match a redeemer to a script

This is incorrect. Redeemers are stored in a transaction as map of pointers to redeemers data. Those pointers explicitly refers to transaction inputs (or minting policies, or withdrawals, or certificates depending on the redeemer's type) and are unambiguous. 

> But to calculate RedeemerPtr in the redeemers, the txIns are directly used in previous order

I don't think this is the case. Inside `makeTransactionBody`, redeemer pointers are ultimately figured out from https://github.com/input-output-hk/cardano-node/blob/333c701ca9be38e5d955c9d3ee0fab391e85e4f4/cardano-api/src/Cardano/Api/TxBody.hs#L2819 which correctly takes care of ordering transaction inputs lexicographically as they also are in the input set: https://github.com/input-output-hk/cardano-node/blob/333c701ca9be38e5d955c9d3ee0fab391e85e4f4/cardano-api/src/Cardano/Api/TxBody.hs#L2839-L2843

---

@mesudip are you by any chance "fiddling" with the transaction after `makeTransactionBody` , like, adding change input/output to it before passing it to the node?

**Comment by etiennejf** [comment] 2022-02-18 09:52
Note that even if you want to impose an order on the input by making your own `makeTransactionBody` function (e.g., use of `Set.fromAscList` instead of `Set.fromList`to preserve txins order from TxBodyContent) and properly patch the `collectTxBodyScriptWitnesses`, you will still be faced with an ordering issue when submitting the transaction to cardano-node (either via cli or directly using cardano-api). In fact, when cardano-node will decode the transaction, it will implicitly reapply Set.fromList, which can alter the input order. So no ordering other that txId order can be imposed on transaction input.

**Comment by mesudip** [comment] 2022-02-22 07:03
@KtorZ , I am api as follows

- create dummy transaction with minFee, exUnits and change and  call `makeTransactionBody`
- use `evaluateTransactionExecutionUnits` and update it, and recall `makeTransactionBody`
- reCalculate Fee and call `makeTransactionBody`. Now we are ready to sign the tx :)

**Comment by KtorZ** [comment] 2022-02-22 07:46
> and update it

That's the part I am the most interested about. What kind of update :) ?

**Comment by Jimbo4350** [comment] 2022-10-27 08:38
Closing this. If this is still relevant please reopen.

**Closed by Jimbo4350** 2022-10-27 08:38 UTC
Labels: bug
