### ISSUE TITLE
[BUG] - FatalError "Shelley.Spec.Ledger.Address.getByron: undefined" 

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#1010] opened 2020-05-21 07:58 UTC
**Summary**
FatalError "Shelley.Spec.Ledger.Address.getByron: undefined" when working with `shelley stake-addresses`

**Steps to reproduce**
1. create an address with delegation power using `cardano-cli shelley stake-address build`
2. get the address info
```
cardano-cli shelley address info --address 820058204caa06d28a8516c160da1b582cc0c8f718db3d0f4fc50819ea192e2e0737bbc9
cardano-cli: FatalError {fatalErrorMessage = "Shelley.Spec.Ledger.Address.getByron: undefined"}
```
- the same error can be seen also when building a raw transaction having such an address as destination.

**Expected behavior**
We should be able to create and use `stake-addresses` without any errors.

**System info (please complete the following information):**
- OS: `Ubuntu 20.04 LTS (GNU/Linux 5.4.0-28-generic x86_64)`
```
git rev-parse --verify HEAD
4669b38e48ad278cb61d23cbfa481e0b7dbeb893
```
```
cardano-cli version
cardano-cli 1.11.0 - linux-x86_64 - ghc-8.6
git rev 4669b38e48ad278cb61d23cbfa481e0b7dbeb893
```

**Comment by zandeck** [comment] 2020-05-21 10:10
I do get the same error when trying to run cardano-node built from tags/pioneer-3 and use the following configs: https://hydra.iohk.io/build/2622346/download/1/index.html.

**Comment by dorin100** [comment] 2020-05-21 10:16
@zandeck , you are using an old genesis file. Here is the latest that you should use - https://hydra.iohk.io/build/2674253

**Comment by zandeck** [comment] 2020-05-21 10:44
Thank you @dorin100, it looks much better.

**Comment by dorin100** [comment] 2020-05-21 11:13
Scenario:
- I have a payment utxo with some funds attached
- I want to create a `stake-address` that will be used as a stake pool owner + for delegation purposes
- I am using the below steps for creating the `stake-address` and for sending some funds from the initial utxo into this new address but I am getting the below error:
```
# 1. create payment keys for pool owner address
cardano-cli shelley address key-gen \
	--verification-key-file owner_payment.vkey \
	--signing-key-file owner_payment.skey

# 2. create stake keys for pool owner address
cardano-cli shelley stake-address key-gen \
	--verification-key-file owner_stake.vkey \
	--signing-key-file owner_stake.skey

# 3. create pool owner's registration certificate 
cardano-cli shelley stake-address registration-certificate \
	--staking-verification-key-file owner_stake.vkey \
	--out-file owner_registration.cert

# 4. create the address with stake powers (for the pool owner)
cardano-cli shelley stake-address build \
	--staking-verification-key-file owner_stake.vkey > owner.addr
	
5. send some funds form the existing payment address to the newly created stake addres
# the stake address will be used further as pool owner + paying the tx fees for submitting 
# the certificates
# == SRC_ADDR (utxo from a payment key): 61156241e0e3458e0374dc291352d028330e677c3cc5f7985dfeec6e6f3a2296c2
# == DST_ADDR (stake addr from above): 8200582036944b703a6bd9731b03b859dd3375e07d42e216c1531cc57cff106cb081cb9d

 cardano-cli shelley query filtered-utxo \
     --address 61156241e0e3458e0374dc291352d028330e677c3cc5f7985dfeec6e6f3a2296c2 \
     --testnet-magic 42
     
  ----------------------------------------------------------------------------------------
  5041c9c6a3b320693c3f49f4e54ae92d88847c5e8c9ca4b3df4f6894922fc6b4     1      999999831891

999999831891 - 168097 - 1000000000 = 998999663794

cardano-cli shelley query protocol-parameters \
	--testnet-magic 42 > ../pparams.json
	
cardano-cli shelley transaction build-raw \
	--tx-in 5041c9c6a3b320693c3f49f4e54ae92d88847c5e8c9ca4b3df4f6894922fc6b4#1 \
	--tx-out 8200582036944b703a6bd9731b03b859dd3375e07d42e216c1531cc57cff106cb081cb9d+1000000000 \
	--tx-out 61156241e0e3458e0374dc291352d028330e677c3cc5f7985dfeec6e6f3a2296c2+998999663794 \
	--ttl 400000 \
	--fee 168097  \
	--tx-body-file tx1.raw

cardano-cli: FatalError {fatalErrorMessage = "Shelley.Spec.Ledger.Address.getByron: undefined"}
```

In order to register the stake pool certificate and the stake-address delegation certificate I need the funds into the `stake-address`.

**Comment by dcoutts** [comment] 2020-05-21 12:50
> I am using the below steps for creating the stake-address and for *sending some funds from the initial utxo into this new address*

This is not possible. You cannot send funds to a stake address. Rewards are added to the account associated with a stake address, and you can spend such funds. You cannot add more funds into stake addresses. They are not the same as normal payment addresses.

**Comment by ItFlyingStart** [comment] 2020-05-21 18:59
> @zandeck , you are using an old genesis file. Here is the latest that you should use - https://hydra.iohk.io/build/2674253

Many thanks. This helps me out as well :-)

**Comment by kevinhammond** [comment] 2020-06-03 18:16
Can we close this?

**Comment by Jimbo4350** [comment] 2020-06-12 11:20
Closing. I can't reproduce the initial bug and `getByron` has been implemented in the ledger specs. Re-open a new issue if necessary.

**Closed by Jimbo4350** 2020-06-12 11:20 UTC
Labels: Pioneer, cli revision, documentation, priority low
