### ISSUE TITLE
[FR] - Conversion of cardano-address generated keys (base16) to cborHex

### ISSUE THREAD

**Issue by MarcelKlammer** [input-output-hk/cardano-node#1496] opened 2020-07-18 10:06 UTC
**Exernal**

**Describe the feature you'd like**

(Edited to make it more clear.)

Convert  base16 prv/pub keys (created by cardano-address) to cborHex skey/vkey keys (created by cardano-cli).

Base16 prv/pub keys can be derived from eg. 15 word mnemonic, which represent a wallet in Daedalus. 

Either cardano-cli or cardano-address should implement a command that converts Base16 keys to cborHex keys.

Almost all pool operators will benefit from an easy to store/safeguard mnemonic pass phrase instead of dealing with key hashes in text files.

Thanks for considering this.

@kantp

**Comment by dcoutts** [comment] 2020-07-18 10:56
The CLI now supports extended/HD singing keys, so this would be possible in principle.

**Comment by angelstakepool** [comment] 2020-07-18 18:19
I had this same concern from the very beginning of STN. Concerning our payment/pledge address, and specially for backup purposes (metal wallets come to mind), it is much easier to deal with a single mnemonic instead of 4 keys (payment.skey, payment.vkey, staking.skey, staking.vkey). So, we (POs and whales providing pledge to pools, ie staking.skey & staking.vkey) would still be able to monitor our pledge addresses from Daedalus, while we have the 4 associated keys to sign any transaction [using cardano-cli in disconnected environment].

**Comment by Griff1221** [comment] 2020-07-18 19:01
Thank you for raising this issue! I do not like moving great value around. And soon we will have Ledger support with Daedalus. I would hope that my stake would reside there.

**Comment by staking4ada** [comment] 2020-07-18 19:08
For us pool operators to deal with whale co-owners, who do not necessarily have required skills to generate/supply their own stake keys, it is important we can let them at least generate their payment.skey/vkey, by deriving them from their daedalus wallet themselves in a semi-userfriendly way.

**Comment by glitch40** [comment] 2020-07-18 21:49
The above reason is directly where this leads. It greatly reduces the function of pledge as the security mechanism it is intended to be. With that inclusion everybody is freely able to market pledging to pools directly with the incentive of promised additional returns. This unravels the function of pledge, and heads directly to a race to saturate pledge on as many pools as possible leading to the exact thing pledge was intended to protect against. A large scale attack with not very much out of pocket by the attacker (51 percent attack back in play).   

I am for simplistic address recovery and security but against finding loopholes in security features designed to protect the network.  

Not looking for an argument and this will be my only post, all that i am asking is that you open your eyes and look to where the path leads, the easier you make it the less security there is against this type of attack look at it from both sides.

**Comment by MarcelKlammer** [comment] 2020-07-19 06:39
The source code is there. It's a simple conversion of keys. The security in pledging lies at the trust level. Secure funds will be a benefit for all involved.

**Comment by Proxiweb** [comment] 2020-07-24 14:02
It would be great to have this feature for mainnet. Not being able to use directly funds stored in a Shelley Daedalus wallet as owner stake when creating is sub-optimal.

**Comment by jhonkingcai** [comment] 2020-08-13 10:50
> The source code is there. It's a simple conversion of keys. The security in pledging lies at the trust level. Secure funds will be a benefit for all involved.

Sorry I don’t understand the Haskell development language.
Can you tell me the specific coding principle of converting base16key to payment key (0x5880 | xprv | pub | chaincode)?
My previous wallet used the base16 key created by cardano-address, now I cannot use my ada.
 thank you so much!!!

**Comment by MarcelKlammer** [comment] 2020-08-13 11:08
I still hope to see it implemented in the cli, but ilap gave us the algorithm just in time for stake pool creation:

https://gist.github.com/ilap/3fd57e39520c90f084d25b0ef2b96894

**Comment by vix-io** [comment] 2020-09-15 10:17
This is in our backlog

**Comment by Jimbo4350** [comment] 2022-10-27 07:58
Closing this. If this is still relevant please re-open.

**Closed by Jimbo4350** 2022-10-27 07:58 UTC
Labels: enhancement, cli revision
