### ISSUE TITLE
[BUG] - cardano-node taking 4GB+ of memory (macOS)

### ISSUE THREAD

**Issue by mreed911** [input-output-hk/cardano-node#2636] opened 2021-04-20 17:27 UTC
*External* 
*Other* 

**Summary**
cardano-node is using far too much memory - more than 4GB - nearly double of anything else in use

**Steps to reproduce**
1. Install Daedalus 4.0.5 and launch
2.  Look at system activity monitor for resources consumed
3. See 4.09GB assigned to cardano-node

**Expected behavior**
Less than 4GB of memory in use by cardano-node

**System info (please complete the following information):**
- OS: macOS 10.15.7
- Daedalus 4.0.5 (cardano-node from that project/build/install)	

**Screenshots and attachments**
- Screenshot of Activity Monitor memory usage/categories
- cardano-node logs, daedalus versions info

![Screen Shot 2021-04-20 at 12 23 05 PM](https://user-images.githubusercontent.com/75264265/115438661-47d14300-a1d3-11eb-849f-0b3ac7d10b45.png)

[logs-2021-04-20T171233.0589Z.zip](https://github.com/input-output-hk/cardano-node/files/6345500/logs-2021-04-20T171233.0589Z.zip)

**Comment by benapetr** [comment] 2021-04-26 06:55
on Windows it uses about 10GB of RAM, and on GNU/Linux it uses about 4GB as well, it's been always like that so not sure if this is a bug, some optimization might help though.

FYI this is visible on mainnet only, on testnet it uses about 600MB

**Comment by 2072** [comment] 2021-05-11 08:09
On 2 of my relays I have to restart the node  every 12 hours because it leaks memory (it slowly goes above 7GB), other 2 relays use between 5GB and 6 GB and are very stable (currently running for 9 days).
All my relays are running on Debian system with 8GB or RAM (the node was built with GHC 8.10.4), so it must have something to do with the external requests the nodes are receiving and is not related to the OS.
The only difference between the relays where it leaks and those where it doesn't is the number of CPU cores (I run the node with the `-N#` parameter where `#` is changed depending on the number of cores)

All my nodes are running with these parameters where N is adjusted properly:
`+RTS -N4 --disable-delayed-os-memory-return -xn -RTS`

(the `-xn` flag does not seem to impact this behavior)

The producer node does not leak despite the `-N4` flag but its swap is disabled and of course it cannot receive random requests...

**Comment by krissemicolon** [comment] 2021-05-31 09:06
Thats about the expected memory use

**Comment by 2072** [comment] 2021-07-17 15:21
Ok, the issue is solved for me, I've detailed my findings in this post: https://forum.cardano.org/t/solving-the-cardano-node-huge-memory-usage-done/67032 it still uses more thatn 4GB of memory but at least it stays below 6GB

**Comment by Jimbo4350** [comment] 2022-10-27 08:22
Closing this. If this is still relevant please reopen.

**Closed by Jimbo4350** 2022-10-27 08:22 UTC
Labels: bug
