### ISSUE TITLE
[BUG] - cardano-cli transaction calculate-min-required-utxo defaults to --mary-era

### ISSUE THREAD

**Issue by AndrewWestberg** [input-output-hk/cardano-node#3228] opened 2021-09-20 18:18 UTC
**External**

**Area**
*Other*  cardano-cli

**Summary**
The default value for era should be alonzo and not mary. The default for protocol parameters, which this command can use already defaults to alonzo era

**Steps to reproduce**
1. run the command passing a protocol params json file and no era parameter
2. See error

```
Command failed: transaction calculate-min-value  Error: The MaryEra protocol parameters value is missing the following field: MinUTxoValue. Did you intend to use a MaryEra protocol  parameters value?
```

**Expected behavior**
Command should default to alonzo era if not specified. Also, the error message should reference the proper command name and not the old deprecated command.

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version 20.04
- Node version cardano-node 1.30.0 - linux-x86_64 - ghc-8.10
git rev 9d4e58740043e6a504929bce39bf9eb9b73d1b65
- CLI version cardano-cli 1.30.0 - linux-x86_64 - ghc-8.10
git rev 9d4e58740043e6a504929bce39bf9eb9b73d1b65

**Comment by disassembler** [comment] 2021-09-20 18:23
I think this should probably be generalized to updating all CLI commands to default to Alonzo now that we've hard forked.

**Comment by mkoura** [comment] 2021-09-20 19:36
Duplicate of https://github.com/input-output-hk/cardano-node/issues/3201

**Comment by nc6** [comment] 2021-10-04 08:55
Closing as a duplicate of #3201

**Closed by nc6** 2021-10-04 08:55 UTC
Labels: bug, priority high, API&CLI-Backlog
