### ISSUE TITLE
[FR] - Lovelace output needed when output address for native tokens is the same as change address

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node#3057] opened 2021-08-11 07:22 UTC
**Internal/External**
*Internal*

**Area**
*Native Tokens*    Related to Native Tokens (Mary).

**Summary**
I'm using `transaction build` command for minting native tokens. That command automatically creates output for Lovelace change. In my transaction, change was higher than minimum UTxO value. The output for minted tokens was the same address as was used for the change, i.e. the UTxO for that change address would have Lovelace amount greater than minimum UTxO value + the minted tokens. However the transaction failed with

```
$ cardano-cli transaction build --tx-in 2cb330d4125cfcd3a8bbffbd5f596e95e4abb58c957459cf810955da909b8b83#0 --tx-out addr_test1vqqt0x3ax6d5320eqtpykjf573ue00td834zcljhdyfd3useuevxa+2000000+1 d8e5fe41f76e817956a85dcb4751d86d0dd294f47e91ee0e01301817.couttscoingvzm --tx-out addr_test1vr0ukapgh8fxn2ywnvk2t8vr4p4dwt2lxam6x33gvdshcegkvpshl+19999999 d8e5fe41f76e817956a85dcb4751d86d0dd294f47e91ee0e01301817.couttscoingvzm --change-address addr_test1vr0ukapgh8fxn2ywnvk2t8vr4p4dwt2lxam6x33gvdshcegkvpshl --alonzo-era --testnet-magic 42 --out-file test_transfer_tokens_1_True_tx.body

Command failed: transaction build  Error: Minimum UTxO threshold not met for tx output: addr_test1vr0ukapgh8fxn2ywnvk2t8vr4p4dwt2lxam6x33gvdshcegkvpshl + 19999999 d8e5fe41f76e817956a85dcb4751d86d0dd294f47e91ee0e01301817.couttscoingvzm
Minimum required UTxO: Lovelace 1379280
```

**System info (please complete the following information):**
- OS Name: Fedora 34
- Node & CLI version:
```
cardano-cli 1.28.0 - linux-x86_64 - ghc-8.10
git rev 4ff39790a8f80e4b2617e641b2c6060b52525f10
```

**Comment by dcoutts** [comment] 2021-08-16 08:27
This is a feature request, not a bug.

As designed, the change address feature is very simple: you provide a change address and we use that to create a single output with the ada/lovelace change. It doesn't matter if you also use the same address for other outputs. There is no feature to combine the change output with another output. If you want more precise control, use the `build-raw` command.

**Comment by Jimbo4350** [comment] 2021-11-02 12:54
Closing this as I agree with Duncan. Use the `build-raw` command.

**Closed by Jimbo4350** 2021-11-02 12:54 UTC
Labels: enhancement, alonzo-purple, API&CLI-Backlog
