### ISSUE TITLE
Repo Preparation for MBO

### ISSUE THREAD

**Issue by ThatGuyLLC** [input-output-hk/cardano-node#4603] opened 2022-11-03 13:13 UTC
This repo has been marked as core tech and is part of initiative of repo preparation, part of this includes adding needed missing documentation.
This repo in particular needs:
-Include the Standard Code of Conduct
-Identify the Core Maintainers

**Comment by Jimbo4350** [comment] 2022-11-04 14:56
This is also not a bug

**Comment by Jimbo4350** [comment] 2022-11-07 12:58
Closing this until I get a clarification from @ThatGuyLLC

**Closed by Jimbo4350** 2022-11-07 12:58 UTC

**Comment by coot** [comment] 2022-11-07 16:40
I'd suggest that maintainers should be included in `*.cabal` files, we ought to write this in the handbook.
