### ISSUE TITLE
[BUG] - SubscriptionWorker exiting

### ISSUE THREAD

**Issue by shawnim** [input-output-hk/cardano-node#1714] opened 2020-08-17 22:36 UTC
**Internal/External**
*External*

**Summary**
In the block producer log file:
[ip-172-3:cardano.node.DnsSubscription:Error:4451] [2020-08-17 18:57:08.04 UTC] [String "Application Exception: 107.23.61.45:3001 SubscriberError {seType = SubscriberWorkerCancelled, seMessage = \"SubscriptionWorker exiting\", seStack = []}",String "SubscriptionTrace",String "\"passive2.squidpool.com\""]

**Steps to reproduce**
1. Run cardano-node 1.18.0 as block producer with below relay topology.
2. Happened after running fine for awhile.
3. Has not repeated yet.

**Expected behavior**
Handle error more gracefuly and not exit.

**System info (please complete the following information):**
- OS: Ubuntu
- Version 18.04
- Node version
cardano-node 1.18.0 - linux-x86_64 - ghc-8.6
git rev fcdd3bfee23e3f8b2d5a1281f42d13a0e305f17c

**Additional context**
From the log:
[...]
[ip-172-3:cardano.node.ForgeTime:Info:453] [2020-08-17 18:57:07.00 UTC] fromList []
[ip-172-3:cardano.node:Info:4446] [2020-08-17 18:57:07.91 UTC] fromList [("time(ps)",Number 1.676756885865156e18),("kind",String "MeasureTxsTimeStart"),("mempoolNumBytes",Number 3504.0),("mempoolNumTxs",Number 2.0)]
[ip-172-3:cardano.node.Mempool:Info:4446] [2020-08-17 18:57:07.91 UTC] fromList [("tx",Object (fromList [("txid",String "txid: TxId {_unTxId = \"1f981ed5d7afeb5be2f2e03f8d5957d3121077e461f8a6ffd9d1e3be80335661\"}")])),("kind",String "TraceMempoolAddedTx"),("mempoolSize",Object (fromList [("numTxs",Number 2.0),("bytes",Number 3504.0)]))]
[ip-172-3:cardano.node.Mempool:Info:4436] [2020-08-17 18:57:07.93 UTC] fromList [("tx",Object (fromList [("txid",String "txid: TxId {_unTxId = \"1f981ed5d7afeb5be2f2e03f8d5957d3121077e461f8a6ffd9d1e3be80335661\"}")])),("kind",String "TraceMempoolRejectedTx"),("mempoolSize",Object (fromList [("numTxs",Number 2.0),("bytes",Number 3504.0)])),("err",Object (fromList [("kind",String "BadInputsUTxO"),("error",String "The transaction contains inputs that do not exist in the UTxO set."),("consumed",Number 0.0),("badInputs",Array [Array [String "ba28efa0a6a45c2134d54a37b3fc3bb7ba2332a02442803c4c4e1b01c69f4e14",Number 5.0],Array [String "ba28efa0a6a45c2134d54a37b3fc3bb7ba2332a02442803c4c4e1b01c69f4e14",Number 6.0],Array [String "ba28efa0a6a45c2134d54a37b3fc3bb7ba2332a02442803c4c4e1b01c69f4e14",Number 7.0],Array [String "ba28efa0a6a45c2134d54a37b3fc3bb7ba2332a02442803c4c4e1b01c69f4e14",Number 12.0],Array [String "ba28efa0a6a45c2134d54a37b3fc3bb7ba2332a02442803c4c4e1b01c69f4e14",Number 14.0],Array [String "ba28efa0a6a45c2134d54a37b3fc3bb7ba2332a02442803c4c4e1b01c69f4e14",Number 15.0],Array [String "db24c84d506e4706467403de2080f405626e4dcdc993cae73eac78cc83e219da",Number 17.0],Array [String "fbbe4a0b6464eefcfc01ee92d087f3fa5ffd5622bb7d29581620ef12faca5af5",Number 0.0],Array [String "fbbe4a0b6464eefcfc01ee92d087f3fa5ffd5622bb7d29581620ef12faca5af5",Number 2.0],Array [String "fbbe4a0b6464eefcfc01ee92d087f3fa5ffd5622bb7d29581620ef12faca5af5",Number 4.0]]),("produced",Number 3.4165688050908e13)]))]
[ip-172-3:cardano.node.Forge:Info:453] [2020-08-17 18:57:08.00 UTC] {"kind":"TraceStartLeadershipCheck","slot":6124337,"utxoSize":735827}
[ip-172-3:cardano.node.ForgeTime:Info:453] [2020-08-17 18:57:08.00 UTC] fromList []
[ip-172-3:cardano.node.Forge:Info:453] [2020-08-17 18:57:08.00 UTC] Not leading slot 6124337
[ip-172-3:cardano.node.ForgeTime:Info:453] [2020-08-17 18:57:08.00 UTC] fromList []
[ip-172-3:cardano.node.DnsSubscription:Error:4454] [2020-08-17 18:57:08.04 UTC] [String "Application Exception: 107.23.61.45:3002 SubscriberError {seType = SubscriberWorkerCancelled, seMessage = \"SubscriptionWorker exiting\", seStack = []}",String "SubscriptionTrace",String "\"passive2.squidpool.com\""]
[ip-172-3:cardano.node.DnsSubscription:Error:4451] [2020-08-17 18:57:08.04 UTC] [String "Application Exception: 107.23.61.45:3001 SubscriberError {seType = SubscriberWorkerCancelled, seMessage = \"SubscriptionWorker exiting\", seStack = []}",String "SubscriptionTrace",String "\"passive2.squidpool.com\""]

mainnet-topology.json

```
 {
    "Producers": [
      { "addr": "passive2.squidpool.com", "port": 3001, "valency": 1 },
      { "addr": "passive2.squidpool.com", "port": 3002, "valency": 1 }
    ]
  }

```

**Comment by kevinhammond** [comment] 2020-08-25 11:31
I believe this is just informational rather than indicating a bug.  The DNS process has been terminated, but the node should continue running.  This would be normal behaviour if there was a DNS lookup issue, for example.

**Comment by coot** [comment] 2020-08-31 10:43
`SubscriberWorkerCancelled` means either: 

* the subscription main loop exited (that would be a bug)
* the node was exiting and was cancelling threads  

But since this seems noot easily reproducible, and in not a too distinct future we will replace subscription with p2p-governor I'm keen to close this issue. Please re-open if you'd be able to reproduce it.

**Closed by coot** 2020-08-31 10:43 UTC
