### ISSUE TITLE
[BUG] - Panic! applyHeaderTransition failed

### ISSUE THREAD

**Issue by 2072** [input-output-hk/cardano-node#1356] opened 2020-06-28 20:43 UTC
**Internal/Exernal**

*External*   otherwise.

**Summary**
Block producing node crashed with

```
[xxxxcardano.node.ChainDB:Info:5] [2020-06-28 20:39:48.35 UTC] Closed db with immutable tip at (Point 429960, HashHeader {unHashHeader = f6823180da948e34b28b47536fa591c6ad5e81f27cc498a4ecb70483729fcb46}) and tip (Point 431985, HashHeader {unHashHeader = df3881b5aeecda0f2d6ab75e1a1d0f66eb0af2d44e3a9ad2571938feabc4a48d})

Shutting down..
cardano-node: ExceptionInLinkedThread "ThreadId 50" Panic! applyHeaderTransition failed.
CallStack (from HasCallStack):
  error, called at src/Shelley/Spec/Ledger/API/Validation.hs:99:11 in shelley-spec-ledger-0.1.0.0-inplace:Shelley.Spec.Ledger.API.Validation

```
and will crash again almost instantly with the same error if restarted

**Steps to reproduce**

I have no idea

**Expected behavior**
should not crash

**System info (please complete the following information):**
- OS: [Debian]
- Version [Buster]
- Node version 1.14.0 46f296f

**Screenshots and attachments**
default logging doesn't seem to provide any additional info

**Additional context**

**Comment by 2072** [comment] 2020-06-28 21:31
Not sure if it's useful since the testnet appears to be stuck but just in case, here is my database which trigger the crash every time: https://we.tl/t-2nzRThfPfh 
I let the node recreate its db from scratch, it no longer crashes but the logs loop with:

```
[vps-9179:cardano.node.Forge:Info:56] [2020-06-28 21:29:19.00 UTC] Testing for leadership at slot 440959
[vps-9179:cardano.node.ForgeTime:Info:56] [2020-06-28 21:29:19.00 UTC] fromList []
[vps-9179:cardano.node.Forge:Error:56] [2020-06-28 21:29:19.00 UTC] No ledger view at slot 440959
```

**Comment by johnalotoski** [comment] 2020-06-28 23:07
Thank you very much for this ticket and chain state @2072.  The following adds some additional context to this event:

* Earlier today, a proposal update was submitted to the `shelley_testnet` environment adjusting the following genesis parameters (@disassembler, please correct as needed if this is incomplete):

```
-        "nOpt": 50,
-        "rho": 1.78650067e-3,
-        "tau": 0.1,
-        "a0": 0.1

+        "nOpt": 250,
+        "rho": 0.0022,
+        "tau": 0.05,
+        "a0": 0.3
```

* At the time of proposal submission, the proposal was accepted by the network without indication of any problem.  The proposal update took effect on the network at 2020-06-28 19:00 UTC at which point IOHK core/stakepool nodes were immediately observed to panic with the log message below.  The same panics were repeated with additional restart attempts:

```
Jun 28 18:59:58 cardano[11758]: Not leading slot 431998
Jun 28 18:59:58 cardano[11758]: fromList []
Jun 28 18:59:59 cardano[11758]: Testing for leadership at slot 431999
Jun 28 18:59:59 cardano[11758]: fromList []
Jun 28 18:59:59 cardano[11758]: Not leading slot 431999
Jun 28 18:59:59 cardano[11758]: fromList []
Jun 28 19:00:00 cardano[11758]: Testing for leadership at slot 432000
Jun 28 19:00:00 cardano[11758]: fromList []
Jun 28 19:00:00 cardano[11758]: [String "Application Exception: $IP1:3001 SubscriberError {seType = subscriberWorkerCancelled, seMessage = \"SubscriptionWorker exiting\", seStack = []}",String "SubscriptionTrace",String "\"$NODE1\""]
Jun 28 19:00:00 cardano[11758]: [String "Application Exception: $IP2:3001 SubscriberError {seType = SubscriberWorkerCancelled, seMessage = \"SubscriptionWorker exiting\", seStack = []}",String "SubscriptionTrace",String "\"$NODE2\""]
Jun 28 19:00:00 cardano[11758]: [String "Application Exception: $IP3:3001 SubscriberError {seType = SubscriberWorkerCancelled, seMessage = \"SubscriptionWorker exiting\", seStack = []}",String "SubscriptionTrace",String "\"$NODE3\""]
Jun 28 19:00:00 cardano[11758]: [String "Application Exception: $IP4:3001 SubscriberError {seType = SubscriberWorkerCancelled, seMessage = \"SubscriptionWorker exiting\", seStack = []}",String "SubscriptionTrace",String "\"$NODE4\""]
Jun 28 19:00:00 cardano[11758]: [String "Application Exception: $IP5:3001 SubscriberError {seType = SubscriberWorkerCancelled, seMessage = \"SubscriptionWorker exiting\", seStack = []}",String "SubscriptionTrace",String "\"$NODE5\""]
Jun 28 19:00:00 cardano[11758]: Closed db with immutable tip at (Point 429960, HashHeader {unHashHeader = f6823180da948e34b28b47536fa591c6ad5e81f27cc498a4ecb70483729fcb46}) and tip (Point 431985, HashHeader {unHashHeader = df3881b5aeecda0f2d6ab75e1a1d0f66eb0af2d44e3a9ad2571938feabc4a48d})
Jun 28 19:00:00 f9s2jkq2ldm6d7l8pp8mc75qy4qbbj9j-unit-script-cardano-node-start[11758]: Shutting down..
Jun 28 19:00:00 f9s2jkq2ldm6d7l8pp8mc75qy4qbbj9j-unit-script-cardano-node-start[11758]: cardano-node: ExceptionInLinkedThread "ThreadId 48" Panic! applyHeaderTransition failed.
Jun 28 19:00:00 f9s2jkq2ldm6d7l8pp8mc75qy4qbbj9j-unit-script-cardano-node-start[11758]: CallStack (from HasCallStack):
Jun 28 19:00:00  f9s2jkq2ldm6d7l8pp8mc75qy4qbbj9j-unit-script-cardano-node-start[11758]:   error, called at src/Shelley/Spec/Ledger/API/Validation.hs:99:11 in shelley-spec-ledger-0.1.0.0-5mKzyU7EBplFMOWBxSrYvj:Shelley.Spec.Ledger.API.Validation
Jun 28 19:00:00 systemd[1]: cardano-node.service: Main process exited, code=exited, status=1/FAILURE
Jun 28 19:00:00 systemd[1]: cardano-node.service: Failed with result 'exit-code'.
```

* The short testnet genesis parameters made the required recovery time from this condition 72 minutes:
```
2 * (securityParam = 108) * (slotLength = 1s) / (activeSlotsCoeff = 0.05) = 4,320 seconds or 72 minutes
```

* Due to this short testnet recovery period, the network was re-created from fresh genesis while the condition described above is investigated for root cause.

**Comment by nc6** [comment] 2020-06-29 07:48
I _suspect_ that we are seeing an issue related to https://github.com/input-output-hk/cardano-ledger-specs/pull/1593. It's something @uroboros and I were looking at on Friday, but the short description is: if a pool is reaped (e.g. its retirement is processed) in the same epoch transition that introduces new protocol parameters, then the new protocol parameter transition can fail. 

Our automated tests discovered this situation, but a bug/trickiness in the way the tests are generated was causing those failures to be thrown out as test cases, rather than failing the tests.

A separate issue is obviously that the error message in that case is spectacularly unhelpful. We will fix this.

Will look into and attempt to confirm the error today.

**Comment by kevinhammond** [comment] 2020-07-01 10:25
@nc6 - can you link to the PR that deals with this please, and then we can close this issue.

**Comment by kevinhammond** [comment] 2020-07-10 14:06
I believe we can close this issue, since it was related to the protocol parameter update that @nc6 mentioned

**Closed by kevinhammond** 2020-07-10 14:06 UTC
Labels: bug
