### ISSUE TITLE
[FR] - Please implement Bech32 encoding for assets in the API

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-node#2548] opened 2021-03-29 00:58 UTC
**Internal**

**Area**
*Native Tokens*

**Describe the feature you'd like**
Please implement Bech32 encoding for assets as specified in https://github.com/cardano-foundation/CIPs/pull/64 .

**Describe alternatives you've considered**
n/a

**Additional context / screenshots**
n/a

**Comment by gitmachtl** [comment] 2021-03-29 19:49
Duplicate of https://github.com/input-output-hk/cardano-node/issues/2426 but not limited to Native Assets

**Comment by Jimbo4350** [comment] 2022-10-27 08:16
Closing this. If this is still relevant please reopen.

**Closed by Jimbo4350** 2022-10-27 08:16 UTC
Labels: enhancement
