### ISSUE TITLE
[BUG] - `transaction build` does not balance correctly when the certificate is already submitted

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#3040] opened 2021-08-06 11:25 UTC
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
We get error when submitting a tx based on `transaction build`

**Steps to reproduce**
1. try to submit a tx with a stake pool registration cert already registered.

```
cardano-cli transaction build \
    --alonzo-era \
    --testnet-magic $MAGIC \
    --tx-in ed977081747a09f922a3948531d9759e2857afa883cce14a1c1ead934589a274#0 \
    --change-address $(cat addr/addr1.addr) \
    --protocol-params-file protocol-params.json \
    --certificate-file pool/pool_registration.cert \
    --witness-override 3 \
    --out-file tx_raw1.body 

cardano-cli transaction sign \
  --tx-body-file tx_raw1.body \
  --testnet-magic $MAGIC \
  --signing-key-file addr/addr1.skey \
  --signing-key-file pool/pool_cold.skey \
  --signing-key-file addr/addr1_stake.skey \
  --out-file tx_raw1.signed

cardano-cli transaction submit \
    --testnet-magic $MAGIC \
    --tx-file tx_raw1.signed

Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (ValueNotConservedUTxO (Value 998961429977 (fromList [])) (Value 998461429977 (fromList [])))))])
```

- the diff is the 500 Ada (pool reg cert) that is already paid.
- 
**Expected behavior**
The tx should be already correctly balanced.

**System info (please complete the following information):**
- OS Name: Ubuntu
```
$ cardano-cli --version
cardano-cli 1.28.0 - linux-x86_64 - ghc-8.10
git rev 708de685d49ec6af4b2d8b3cbfa0eca0e9e43edf

$ cardano-node --version
cardano-node 1.28.0 - linux-x86_64 - ghc-8.10
git rev 708de685d49ec6af4b2d8b3cbfa0eca0e9e43edf
```

**Comment by gitmachtl** [comment] 2021-08-08 08:28
Thats not an error of the application, thats an user error 😄 

Behavior was always this way, if there is already a pool registered, you don't have to pay the 500 ada registration fee again. In that case just send the new certificate but reduce the amount to send with the poolRegistrationFee of 500 ada.

**Comment by dcoutts** [comment] 2021-08-19 18:05
We suspect that the cause of this bug is that the cli is currently passing an empty set of pool ids rather. To do this properly will require querying the current set of pool ids and passing them in place of the empty set.

**Comment by dcoutts** [comment] 2021-08-19 21:58
Related #3101

**Comment by Jimbo4350** [comment] 2021-11-09 20:50
Fixed in: https://github.com/input-output-hk/cardano-node/pull/3176

**Closed by Jimbo4350** 2021-11-09 20:50 UTC
Labels: bug, alonzo-white, API&CLI-Backlog
