### ISSUE TITLE
[BUG] - At a loss, trying to understand why two separate test relay nodes stopped sync'ing completely. This scares me about my production setup, will this just happen?

### ISSUE THREAD

**Issue by systemsbigthink** [input-output-hk/cardano-node#3291] opened 2021-10-13 03:17 UTC
Cardano node stops sync'ing on testnet for no reason.
This has happened to more than one server/system and I cannot explain it.
What has changed or would cause this?

Sorry for the insane logs, this is cardano node 1.29.0 running in docker/k8s. This worked perfectly then just stopped all of a sudden.  I realize this isn't a ton of detail here, but this was working perfectly since Alonzo hardfork.

Config files came from:

https://hydra.iohk.io/job/Cardano/cardano-node/cardano-deployment/latest-finished/download/1

[cardano-:cardano.node.DnsSubscription:Notice:514] [2021-10-13 03:08:47.99 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Connection Attempt Start, destination 52.58.32.201:3001
[cardano-:cardano.node.DnsSubscription:Notice:515] [2021-10-13 03:08:48.01 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Connection Attempt Start, destination 52.58.117.45:3001
[cardano-:cardano.node.DnsSubscription:Notice:514] [2021-10-13 03:08:48.14 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Connection Attempt End, destination 52.58.32.201:3001 outcome: ConnectSuccess
[cardano-:cardano.node.DnsSubscription:Notice:515] [2021-10-13 03:08:48.18 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Connection Attempt End, destination 52.58.117.45:3001 outcome: ConnectSuccessLast
[cardano-:cardano.node.DnsSubscription:Error:514] [2021-10-13 03:08:48.87 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Application Exception: 52.58.32.201:3001 HeaderError (At (Block {blockPointSlot = SlotNo 39614475, blockPointHash = 1acb3ab3338115eb485e8ae73e8abc24b2c48f2ddb4880bd85ca586aa6dcfd5b})) (HeaderEnvelopeError (OtherHeaderEnvelopeError (HardForkEnvelopeErrFromEra S (S (S (S (Z (WrapEnvelopeErr {unwrapEnvelopeErr = ObsoleteNodeCHAIN 6 5})))))))) (Tip (SlotNo 39614381) 809a09ac9273bf7c468622c0f6f480deb8f81946c4381e7dbdf1aae63195c678 (BlockNo 2984847)) (Tip (SlotNo 39725286) 1e996a62f332f1fc11893e46d55a92e7f6348fb3071680b0eae2a6d84e4450b0 (BlockNo 2988187))
[cardano-:cardano.node.ErrorPolicy:Warning:61] [2021-10-13 03:08:48.87 UTC] IP 52.58.32.201:3001 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (HeaderError (At (Block {blockPointSlot = SlotNo 39614475, blockPointHash = 1acb3ab3338115eb485e8ae73e8abc24b2c48f2ddb4880bd85ca586aa6dcfd5b})) (HeaderEnvelopeError (OtherHeaderEnvelopeError (HardForkEnvelopeErrFromEra S (S (S (S (Z (WrapEnvelopeErr {unwrapEnvelopeErr = ObsoleteNodeCHAIN 6 5})))))))) (Tip (SlotNo 39614381) 809a09ac9273bf7c468622c0f6f480deb8f81946c4381e7dbdf1aae63195c678 (BlockNo 2984847)) (Tip (SlotNo 39725286) 1e996a62f332f1fc11893e46d55a92e7f6348fb3071680b0eae2a6d84e4450b0 (BlockNo 2988187))))) 200s 200s
[cardano-:cardano.node.DnsSubscription:Error:515] [2021-10-13 03:08:48.94 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Application Exception: 52.58.117.45:3001 HeaderError (At (Block {blockPointSlot = SlotNo 39614475, blockPointHash = 1acb3ab3338115eb485e8ae73e8abc24b2c48f2ddb4880bd85ca586aa6dcfd5b})) (HeaderEnvelopeError (OtherHeaderEnvelopeError (HardForkEnvelopeErrFromEra S (S (S (S (Z (WrapEnvelopeErr {unwrapEnvelopeErr = ObsoleteNodeCHAIN 6 5})))))))) (Tip (SlotNo 39614381) 809a09ac9273bf7c468622c0f6f480deb8f81946c4381e7dbdf1aae63195c678 (BlockNo 2984847)) (Tip (SlotNo 39725286) 1e996a62f332f1fc11893e46d55a92e7f6348fb3071680b0eae2a6d84e4450b0 (BlockNo 2988187))
[cardano-:cardano.node.ErrorPolicy:Warning:61] [2021-10-13 03:08:48.94 UTC] IP 52.58.117.45:3001 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (HeaderError (At (Block {blockPointSlot = SlotNo 39614475, blockPointHash = 1acb3ab3338115eb485e8ae73e8abc24b2c48f2ddb4880bd85ca586aa6dcfd5b})) (HeaderEnvelopeError (OtherHeaderEnvelopeError (HardForkEnvelopeErrFromEra S (S (S (S (Z (WrapEnvelopeErr {unwrapEnvelopeErr = ObsoleteNodeCHAIN 6 5})))))))) (Tip (SlotNo 39614381) 809a09ac9273bf7c468622c0f6f480deb8f81946c4381e7dbdf1aae63195c678 (BlockNo 2984847)) (Tip (SlotNo 39725286) 1e996a62f332f1fc11893e46d55a92e7f6348fb3071680b0eae2a6d84e4450b0 (BlockNo 2988187))))) 200s 200s
[cardano-:cardano.node.DnsSubscription:Notice:549] [2021-10-13 03:08:57.99 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Connection Attempt Start, destination 52.58.32.201:3001
[cardano-:cardano.node.DnsSubscription:Notice:549] [2021-10-13 03:08:58.15 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Connection Attempt End, destination 52.58.32.201:3001 outcome: ConnectSuccess
[cardano-:cardano.node.DnsSubscription:Warning:63] [2021-10-13 03:08:58.15 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Failed to start all required subscriptions
[cardano-:cardano.node.DnsSubscription:Error:549] [2021-10-13 03:08:58.86 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Application Exception: 52.58.32.201:3001 HeaderError (At (Block {blockPointSlot = SlotNo 39614475, blockPointHash = 1acb3ab3338115eb485e8ae73e8abc24b2c48f2ddb4880bd85ca586aa6dcfd5b})) (HeaderEnvelopeError (OtherHeaderEnvelopeError (HardForkEnvelopeErrFromEra S (S (S (S (Z (WrapEnvelopeErr {unwrapEnvelopeErr = ObsoleteNodeCHAIN 6 5})))))))) (Tip (SlotNo 39614381) 809a09ac9273bf7c468622c0f6f480deb8f81946c4381e7dbdf1aae63195c678 (BlockNo 2984847)) (Tip (SlotNo 39725286) 1e996a62f332f1fc11893e46d55a92e7f6348fb3071680b0eae2a6d84e4450b0 (BlockNo 2988187))
[cardano-:cardano.node.ErrorPolicy:Warning:61] [2021-10-13 03:08:58.86 UTC] IP 52.58.32.201:3001 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (HeaderError (At (Block {blockPointSlot = SlotNo 39614475, blockPointHash = 1acb3ab3338115eb485e8ae73e8abc24b2c48f2ddb4880bd85ca586aa6dcfd5b})) (HeaderEnvelopeError (OtherHeaderEnvelopeError (HardForkEnvelopeErrFromEra S (S (S (S (Z (WrapEnvelopeErr {unwrapEnvelopeErr = ObsoleteNodeCHAIN 6 5})))))))) (Tip (SlotNo 39614381) 809a09ac9273bf7c468622c0f6f480deb8f81946c4381e7dbdf1aae63195c678 (BlockNo 2984847)) (Tip (SlotNo 39725286) 1e996a62f332f1fc11893e46d55a92e7f6348fb3071680b0eae2a6d84e4450b0 (BlockNo 2988187))))) 200s 200s
[cardano-:cardano.node.DnsSubscription:Notice:569] [2021-10-13 03:09:08.05 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Connection Attempt Start, destination 18.132.238.21:3001
[cardano-:cardano.node.DnsSubscription:Notice:569] [2021-10-13 03:09:08.20 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Connection Attempt End, destination 18.132.238.21:3001 outcome: ConnectSuccess
[cardano-:cardano.node.DnsSubscription:Warning:63] [2021-10-13 03:09:08.20 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Failed to start all required subscriptions
[cardano-:cardano.node.DnsSubscription:Error:569] [2021-10-13 03:09:08.85 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Application Exception: 18.132.238.21:3001 HeaderError (At (Block {blockPointSlot = SlotNo 39614475, blockPointHash = 1acb3ab3338115eb485e8ae73e8abc24b2c48f2ddb4880bd85ca586aa6dcfd5b})) (HeaderEnvelopeError (OtherHeaderEnvelopeError (HardForkEnvelopeErrFromEra S (S (S (S (Z (WrapEnvelopeErr {unwrapEnvelopeErr = ObsoleteNodeCHAIN 6 5})))))))) (Tip (SlotNo 39614381) 809a09ac9273bf7c468622c0f6f480deb8f81946c4381e7dbdf1aae63195c678 (BlockNo 2984847)) (Tip (SlotNo 39725286) 1e996a62f332f1fc11893e46d55a92e7f6348fb3071680b0eae2a6d84e4450b0 (BlockNo 2988187))
[cardano-:cardano.node.ErrorPolicy:Warning:61] [2021-10-13 03:09:08.85 UTC] IP 18.132.238.21:3001 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (HeaderError (At (Block {blockPointSlot = SlotNo 39614475, blockPointHash = 1acb3ab3338115eb485e8ae73e8abc24b2c48f2ddb4880bd85ca586aa6dcfd5b})) (HeaderEnvelopeError (OtherHeaderEnvelopeError (HardForkEnvelopeErrFromEra S (S (S (S (Z (WrapEnvelopeErr {unwrapEnvelopeErr = ObsoleteNodeCHAIN 6 5})))))))) (Tip (SlotNo 39614381) 809a09ac9273bf7c468622c0f6f480deb8f81946c4381e7dbdf1aae63195c678 (BlockNo 2984847)) (Tip (SlotNo 39725286) 1e996a62f332f1fc11893e46d55a92e7f6348fb3071680b0eae2a6d84e4450b0 (BlockNo 2988187))))) 200s 200s
[cardano-:cardano.node.DnsSubscription:Notice:588] [2021-10-13 03:09:17.99 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Connection Attempt Start, destination 18.132.238.21:3001
[cardano-:cardano.node.DnsSubscription:Notice:588] [2021-10-13 03:09:18.13 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Connection Attempt End, destination 18.132.238.21:3001 outcome: ConnectSuccess
[cardano-:cardano.node.DnsSubscription:Warning:63] [2021-10-13 03:09:18.13 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Failed to start all required subscriptions
[cardano-:cardano.node.DnsSubscription:Error:588] [2021-10-13 03:09:18.81 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Application Exception: 18.132.238.21:3001 HeaderError (At (Block {blockPointSlot = SlotNo 39614475, blockPointHash = 1acb3ab3338115eb485e8ae73e8abc24b2c48f2ddb4880bd85ca586aa6dcfd5b})) (HeaderEnvelopeError (OtherHeaderEnvelopeError (HardForkEnvelopeErrFromEra S (S (S (S (Z (WrapEnvelopeErr {unwrapEnvelopeErr = ObsoleteNodeCHAIN 6 5})))))))) (Tip (SlotNo 39614381) 809a09ac9273bf7c468622c0f6f480deb8f81946c4381e7dbdf1aae63195c678 (BlockNo 2984847)) (Tip (SlotNo 39725286) 1e996a62f332f1fc11893e46d55a92e7f6348fb3071680b0eae2a6d84e4450b0 (BlockNo 2988187))
[cardano-:cardano.node.ErrorPolicy:Warning:61] [2021-10-13 03:09:18.81 UTC] IP 18.132.238.21:3001 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (HeaderError (At (Block {blockPointSlot = SlotNo 39614475, blockPointHash = 1acb3ab3338115eb485e8ae73e8abc24b2c48f2ddb4880bd85ca586aa6dcfd5b})) (HeaderEnvelopeError (OtherHeaderEnvelopeError (HardForkEnvelopeErrFromEra S (S (S (S (Z (WrapEnvelopeErr {unwrapEnvelopeErr = ObsoleteNodeCHAIN 6 5})))))))) (Tip (SlotNo 39614381) 809a09ac9273bf7c468622c0f6f480deb8f81946c4381e7dbdf1aae63195c678 (BlockNo 2984847)) (Tip (SlotNo 39725286) 1e996a62f332f1fc11893e46d55a92e7f6348fb3071680b0eae2a6d84e4450b0 (BlockNo 2988187))))) 200s 200s
[cardano-:cardano.node.DnsSubscription:Warning:63] [2021-10-13 03:09:27.99 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Failed to start all required subscriptions

**Comment by mrbrinker** [comment] 2021-10-13 04:01
There was a new node release about 15 days ago and IOG has recommended everyone updates it. On test net, we have been using it even longer. There is a telegram group for people using the public test net if you DM me there I can send it to you, but normally all the information for main net is published here and on IOG's social media accounts.

**Comment by arielelkin** [comment] 2021-10-13 10:06
I think the main problem here is that cardano-node's error messages are currently confusing and ambiguous. I filed a separate bug report about this: https://github.com/input-output-hk/cardano-node/issues/3293 

Please upvote it if you find it relevant ;)

**Comment by CarlosLopezDeLara** [comment] 2022-08-13 05:21
Not a bug. Closing the issue since it is expected behavior that an outdated node version (i.e a version that does not support functionalities introduced with a hardfork cannot cross the hardfork.  However we are keeping https://github.com/input-output-hk/cardano-node/issues/3293 opened since the error message can and should be improved.

**Closed by CarlosLopezDeLara** 2022-08-13 05:21 UTC
