### ISSUE TITLE
[BUG] - Node restarts after starting with expired KES key

### ISSUE THREAD

**Issue by AndrewWestberg** [input-output-hk/cardano-node#1314] opened 2020-06-20 19:22 UTC
*External* 

**Summary**
My KES key rotation script was exiting before actually changing out the KES key so the node was restarted with the same old keys. It entered a state where it would continually shut down with an error message only to be brought back up by systemd.

**Steps to reproduce**
1. Try to start a node with an expired kes key.

**Expected behavior**
Expect the node to run, but just give error messages when it comes to leadership events.

**System info (please complete the following information):**
- OS: Ubuntu
- Version 20.04
- Node version 1.13.0-rewards

**Screenshots and attachments**
syslog file
```
2403 Jun 16 05:58:33 papa bcsh-node[611678]: Listening on http://127.0.0.1:12789
2404 Jun 16 05:58:52 papa bcsh-node[611678]: Shutting down..
2405 Jun 16 05:58:52 papa bcsh-node[611678]: cardano-node: ExceptionInLinkedThread "ThreadId 54" Could not update KES key
2406 Jun 16 05:58:52 papa bcsh-node[611678]: CallStack (from HasCallStack):
2407 Jun 16 05:58:52 papa bcsh-node[611678]:   error, called at src/Ouroboros/Consensus/Shelley/Ledger/Forge.hs:109:27 in ouroboros-consensus-shelley-0.1.0.0-in     place:Ouroboros.Consensus.Shelley.Ledger.Forge
2408 Jun 16 05:58:57 papa bcsh-node[612516]: Listening on http://127.0.0.1:12789
2409 Jun 16 05:59:16 papa bcsh-node[612516]: Shutting down..
2410 Jun 16 05:59:16 papa bcsh-node[612516]: cardano-node: ExceptionInLinkedThread "ThreadId 54" Could not update KES key
2411 Jun 16 05:59:16 papa bcsh-node[612516]: CallStack (from HasCallStack):
2412 Jun 16 05:59:16 papa bcsh-node[612516]:   error, called at src/Ouroboros/Consensus/Shelley/Ledger/Forge.hs:109:27 in ouroboros-consensus-shelley-0.1.0.0-in     place:Ouroboros.Consensus.Shelley.Ledger.Forge
2413 Jun 16 05:59:21 papa bcsh-node[613395]: Listening on http://127.0.0.1:12789
2414 Jun 16 05:59:40 papa bcsh-node[613395]: Shutting down..
2415 Jun 16 05:59:40 papa bcsh-node[613395]: cardano-node: ExceptionInLinkedThread "ThreadId 54" Could not update KES key
2416 Jun 16 05:59:40 papa bcsh-node[613395]: CallStack (from HasCallStack):
2417 Jun 16 05:59:40 papa bcsh-node[613395]:   error, called at src/Ouroboros/Consensus/Shelley/Ledger/Forge.hs:109:27 in ouroboros-consensus-shelley-0.1.0.0-in     place:Ouroboros.Consensus.Shelley.Ledger.Forge
2418 Jun 16 05:59:45 papa bcsh-node[614198]: Listening on http://127.0.0.1:12789
2419 Jun 16 06:00:04 papa bcsh-node[614198]: Shutting down..
2420 Jun 16 06:00:04 papa bcsh-node[614198]: cardano-node: ExceptionInLinkedThread "ThreadId 54" Could not update KES key
2421 Jun 16 06:00:04 papa bcsh-node[614198]: CallStack (from HasCallStack):
2422 Jun 16 06:00:04 papa bcsh-node[614198]:   error, called at src/Ouroboros/Consensus/Shelley/Ledger/Forge.hs:109:27 in ouroboros-consensus-shelley-0.1.0.0-in     place:Ouroboros.Consensus.Shelley.Ledger.Forge
2423 Jun 16 06:00:10 papa bcsh-node[615218]: Listening on http://127.0.0.1:12789
2424 Jun 16 06:00:28 papa bcsh-node[615218]: Shutting down..
2425 Jun 16 06:00:28 papa bcsh-node[615218]: cardano-node: ExceptionInLinkedThread "ThreadId 54" Could not update KES key
2426 Jun 16 06:00:28 papa bcsh-node[615218]: CallStack (from HasCallStack):
2427 Jun 16 06:00:28 papa bcsh-node[615218]:   error, called at src/Ouroboros/Consensus/Shelley/Ledger/Forge.hs:109:27 in ouroboros-consensus-shelley-0.1.0.0-in     place:Ouroboros.Consensus.Shelley.Ledger.Forge
2428 Jun 16 06:00:34 papa bcsh-node[616078]: Listening on http://127.0.0.1:12789
2429 Jun 16 06:00:44 papa bcsh-node[616078]: Shutting down..
2430 Jun 16 06:00:44 papa bcsh-node[616078]: cardano-node: ExceptionInLinkedThread "ThreadId 54" Could not update KES key
2431 Jun 16 06:00:44 papa bcsh-node[616078]: CallStack (from HasCallStack):
2432 Jun 16 06:00:44 papa bcsh-node[616078]:   error, called at src/Ouroboros/Consensus/Shelley/Ledger/Forge.hs:109:27 in ouroboros-consensus-shelley-0.1.0.0-in     place:Ouroboros.Consensus.Shelley.Ledger.Forge
2433 Jun 16 06:00:50 papa bcsh-node[616551]: Listening on http://127.0.0.1:12789
2434 Jun 16 06:01:00 papa bcsh-node[616551]: Shutting down..
2435 Jun 16 06:01:00 papa bcsh-node[616551]: cardano-node: ExceptionInLinkedThread "ThreadId 54" Could not update KES key
2436 Jun 16 06:01:00 papa bcsh-node[616551]: CallStack (from HasCallStack):
2437 Jun 16 06:01:00 papa bcsh-node[616551]:   error, called at src/Ouroboros/Consensus/Shelley/Ledger/Forge.hs:109:27 in ouroboros-consensus-shelley-0.1.0.0-in     place:Ouroboros.Consensus.Shelley.Ledger.Forge
```

**Comment by mrBliss** [comment] 2020-06-22 06:51
>  Expect the node to run, but just give error messages when it comes to leadership events.

This sprint, we'll be working on doing exactly this ^^. You can track the progress in #2299.

**Comment by mrBliss** [comment] 2020-06-22 07:27
Duplicate of https://github.com/input-output-hk/cardano-node/issues/1235

**Closed by mrBliss** 2020-06-22 07:27 UTC
Labels: bug, duplicate
