### ISSUE TITLE
[BUG] - LogFile Rotation is not working correct

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-node#2254] opened 2021-01-05 09:57 UTC
*External* 

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
The logfile rotation in cardano-node 1.24.2 is not working correct if there is a `-` in the given logfile name.

**Steps to reproduce**

**node-config.json**
```
...
  "defaultScribes": [
    [
      "StdoutSK",
      "stdout"
    ],
    [
            "FileSK",
            "/home/cardano/logs/relay-primary.json"
    ]
  ],
...
  "rotation": {
    "rpKeepFilesNum": 10,
    "rpLogLimitBytes": 15000000,
    "rpMaxAgeHours": 240
  },
  "setupBackends": [
    "KatipBK"
  ],
  "setupScribes": [
    {
      "scFormat": "ScJson",
      "scKind": "FileSK",
      "scName": "/home/cardano/logs/relay-primary.json",
      "scRotation": null
    }
  ]
...
```
will make files like:
`relay-primary-20210105091639.json`

but the auto-rotation does not work, the logfile accumulate until the hdd space is full

**Expected behavior**
LogfileNames with a `-` in it should also work correct. The rotation routine should search for the last `-` in the filename, not for the first one. I think this is fixable pretty easy.

**System info (please complete the following information):**
- OS: generic linux like debian10, but its a general bug
- Node version 1.24.2

**Comment by gacallea** [comment] 2021-01-05 12:21
nice find @gitmachtl,

FWIW: using systemd/journald/rsyslogd/logrotate does not have this issue:

``` ls -l /var/log/cardano-node.log*
-rw-r----- 1 syslog adm  69445518 Jan  5 12:16 /var/log/cardano-node.log
-rw-r----- 1 syslog adm 137421903 Jan  5 00:00 /var/log/cardano-node.log.1
-rw-r----- 1 syslog adm   6395381 Dec 27 00:00 /var/log/cardano-node.log.10.gz
-rw-r----- 1 syslog adm   6225270 Dec 26 00:00 /var/log/cardano-node.log.11.gz
-rw-r----- 1 syslog adm   6399418 Dec 25 00:00 /var/log/cardano-node.log.12.gz
-rw-r----- 1 syslog adm   6547954 Dec 24 00:00 /var/log/cardano-node.log.13.gz
-rw-r----- 1 syslog adm   6418511 Dec 23 00:00 /var/log/cardano-node.log.14.gz
-rw-r----- 1 syslog adm   6051340 Dec 22 00:00 /var/log/cardano-node.log.15.gz
-rw-r----- 1 syslog adm   5579939 Dec 21 00:00 /var/log/cardano-node.log.16.gz
-rw-r----- 1 syslog adm   6166592 Dec 20 00:00 /var/log/cardano-node.log.17.gz
-rw-r----- 1 syslog adm   6127784 Dec 19 00:00 /var/log/cardano-node.log.18.gz
-rw-r----- 1 syslog adm   6371869 Dec 18 00:00 /var/log/cardano-node.log.19.gz
-rw-r----- 1 syslog adm   6803746 Jan  4 00:00 /var/log/cardano-node.log.2.gz
-rw-r----- 1 syslog adm   5991265 Dec 17 00:00 /var/log/cardano-node.log.20.gz
-rw-r----- 1 syslog adm   6077381 Dec 16 00:00 /var/log/cardano-node.log.21.gz
-rw-r----- 1 syslog adm   6163733 Dec 15 00:00 /var/log/cardano-node.log.22.gz
-rw-r----- 1 syslog adm   6042832 Dec 14 00:00 /var/log/cardano-node.log.23.gz
-rw-r----- 1 syslog adm   6195837 Dec 13 00:00 /var/log/cardano-node.log.24.gz
-rw-r----- 1 syslog adm   6400898 Dec 12 00:00 /var/log/cardano-node.log.25.gz
-rw-r----- 1 syslog adm   6127585 Dec 11 00:00 /var/log/cardano-node.log.26.gz
-rw-r----- 1 syslog adm   4630028 Dec 10 00:00 /var/log/cardano-node.log.27.gz
-rw-r----- 1 syslog adm   4490511 Dec  9 00:00 /var/log/cardano-node.log.28.gz
-rw-r----- 1 syslog adm   4606174 Dec  8 00:00 /var/log/cardano-node.log.29.gz
-rw-r----- 1 syslog adm   6683123 Jan  3 00:00 /var/log/cardano-node.log.3.gz
-rw-r----- 1 syslog adm   4448664 Dec  7 00:00 /var/log/cardano-node.log.30.gz
-rw-r----- 1 syslog adm   6632496 Jan  2 00:00 /var/log/cardano-node.log.4.gz
-rw-r----- 1 syslog adm   6497595 Jan  1 00:00 /var/log/cardano-node.log.5.gz
-rw-r----- 1 syslog adm   6640678 Dec 31 00:00 /var/log/cardano-node.log.6.gz
-rw-r----- 1 syslog adm   7072374 Dec 30 00:00 /var/log/cardano-node.log.7.gz
-rw-r----- 1 syslog adm   6692903 Dec 29 00:00 /var/log/cardano-node.log.8.gz
-rw-r----- 1 syslog adm   6552846 Dec 28 00:00 /var/log/cardano-node.log.9.gz```

```
  "defaultScribes": [
    [
      "StdoutSK",
      "stdout"
    ]
  ],
```

Even if ```rotation``` is in place in the config.json it is  bypassed/not used. My systems' ```rsyslogd``` and ```logrotate``` actually take care of the logs rotation system wide, including ```cardano-node```.

```
  "rotation": {
    "rpKeepFilesNum": 10,
    "rpLogLimitBytes": 5000000,
    "rpMaxAgeHours": 24
  },
  "setupBackends": [
    "KatipBK"
  ],
  "setupScribes": [
    {
      "scFormat": "ScText",
      "scKind": "StdoutSK",
      "scName": "stdout",
      "scRotation": null
    }
```

**Comment by rdlrt** [comment] 2021-01-06 00:40
Duplicate of #992

**Comment by deepfire** [comment] 2021-05-17 15:14
This problem will not exist in the new implementation.

**Comment by Jimbo4350** [comment] 2022-10-27 08:03
Closing this. If this is still relevant please re-open.

**Closed by Jimbo4350** 2022-10-27 08:03 UTC
Labels: bug
