### ISSUE TITLE
Docker image 1.35.4 fails to start

### ISSUE THREAD

**Issue by got3nks** [input-output-hk/cardano-node#4750] opened 2023-01-04 18:19 UTC
Here is the log from Docker:

```
cardano-node_1_10f73c7b9a4b | Starting: /nix/store/c532mbhk7z8zzj2lm0r8r5p1p6v7ian2-cardano-node-exe-cardano-node-1.35.4/bin/cardano-node run
cardano-node_1_10f73c7b9a4b | --config /nix/store/4b0rmqn24w0yc2yvn33vlawwdxa3a71i-config-0-0.json
cardano-node_1_10f73c7b9a4b | --database-path /data/db
cardano-node_1_10f73c7b9a4b | --topology /nix/store/mb0zb61472xp1hgw3q9pz7m337rmfx7f-topology.yaml
cardano-node_1_10f73c7b9a4b | --host-addr 0.0.0.0
cardano-node_1_10f73c7b9a4b | --port 3001
cardano-node_1_10f73c7b9a4b | --socket-path /ipc/node.socket
cardano-node_1_10f73c7b9a4b |
cardano-node_1_10f73c7b9a4b |
cardano-node_1_10f73c7b9a4b |
cardano-node_1_10f73c7b9a4b |
cardano-node_1_10f73c7b9a4b |
cardano-node_1_10f73c7b9a4b | +RTS
cardano-node_1_10f73c7b9a4b | -N2
cardano-node_1_10f73c7b9a4b | -I0
cardano-node_1_10f73c7b9a4b | -A16m
cardano-node_1_10f73c7b9a4b | -qg
cardano-node_1_10f73c7b9a4b | -qb
cardano-node_1_10f73c7b9a4b | --disable-delayed-os-memory-return
cardano-node_1_10f73c7b9a4b | -RTS
cardano-node_1_10f73c7b9a4b | ..or, once again, in a single line:
cardano-node_1_10f73c7b9a4b | /nix/store/c532mbhk7z8zzj2lm0r8r5p1p6v7ian2-cardano-node-exe-cardano-node-1.35.4/bin/cardano-node run --config /nix/store/4b0rmqn24w0yc2yvn33vlawwdxa3a71i-config-0-0.json --database-path /data/db --topology /nix/store/mb0zb61472xp1hgw3q9pz7m337rmfx7f-topology.yaml --host-addr 0.0.0.0 --port 3001 --socket-path /ipc/node.socket      +RTS -N2 -I0 -A16m -qg -qb --disable-delayed-os-memory-return -RTS
cardano-node_1_10f73c7b9a4b | cardano-node: internal error: Itimer: Failed to spawn thread: Operation not permitted
cardano-node_1_10f73c7b9a4b |     (GHC version 8.10.7 for x86_64_unknown_linux)
cardano-node_1_10f73c7b9a4b |     Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
cardano_cardano-node_1_10f73c7b9a4b exited with code 139
```

**Comment by MarcFontaine** [comment] 2023-01-09 15:54
Closing this as a duplicate of https://github.com/input-output-hk/cardano-node/issues/4640

**Closed** 2023-01-09 15:54 UTC
Labels: type: bug
