### ISSUE TITLE
[1.24.2] - Source build fails on CentOS7

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/cardano-node#2212] opened 2020-12-13 10:51 UTC
Following the instructions [here](https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/install.html), I see ...

```
[134 of 134] Compiling Crypto.Tutorial  ( Crypto/Tutorial.hs, dist/build/Crypto/Tutorial.o, dist/build/Crypto/Tutorial.dyn_o )
In file included from cbits/aes/x86ni.h:38:0: error:
    0,
                     from cbits/aes/gf.c:35:
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/wmmintrin.h:34:3: error:
     error: #error "AES/PCLMUL instructions not enabled"
     # error "AES/PCLMUL instructions not enabled"
       ^
   |
34 | # error "AES/PCLMUL instructions not enabled"
   |   ^
In file included from cbits/aes/x86ni.h:39:0: error:
    0,
                     from cbits/aes/gf.c:35:
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/tmmintrin.h:31:3: error:
     error: #error "SSSE3 instruction set not enabled"
     # error "SSSE3 instruction set not enabled"
       ^
   |
31 | # error "SSSE3 instruction set not enabled"
   |   ^
`gcc' failed in phase `C Compiler'. (Exit code: 1)
cabal: Failed to build cryptonite-0.27 (which is required by
test:cardano-node-test from cardano-node-1.24.2, test:cardano-cli-test from
cardano-cli-1.24.2 and others). See the build log above for details.
```

which then causes (none) of the executables to be available.

```
Cannot build the executables in the package typed-protocols-examples because
it does not contain any executables. Check the .cabal file for the package and
make sure that it properly declares the components that you expect.
[core@cardano01 cardano-node]$
[core@cardano01 cardano-node]$ cardano-cli --version
-bash: cardano-cli: command not found
```

**Comment by rdlrt** [comment] 2020-12-14 02:31
You might want to add cryptonite to your cabal.project.local file using something like below:
echo -e "package cryptonite\n  flags: -use_target_attributes" >> cabal.project.local

**Comment by mrBliss** [comment] 2020-12-14 08:30
@rdlrt's solution should work (thanks!). This is a duplicate of https://github.com/input-output-hk/cardano-node/issues/1747

**Closed by mrBliss** 2020-12-14 08:30 UTC
Labels: bug
