### ISSUE TITLE
[FR] - Add epoch and slot in epoch to tip command

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#1737] opened 2020-08-20 15:16 UTC
**Internal/Exernal**
*Internal*   if an IOHK staff member.

**Describe the feature you'd like**
A clear and detailed description of what you are suggesting.

**Describe alternatives you've considered**

**Additional context / screenshots**

**Comment by mrBliss** [comment] 2020-08-21 08:21
Notes for myself and others:
* Querying the tip is currently implemented by connecting a ChainSyncClient, which receives the [`Tip`](https://github.com/input-output-hk/ouroboros-network/blob/966d101a7e943428c88e8b6e7354848eb6cea916/ouroboros-network/src/Ouroboros/Network/Block.hs#L269-L275) as part of every message. This `Tip` doesn't give us enough information (duh).
* Conversion from slot to epoch + relative slot depends on the hard fork (epoch lengths change at the transition), so this depends on the ledger state. One should obtain an [`Interpreter`](https://github.com/input-output-hk/ouroboros-network/blob/83baf7eb58907137d50605fc2c85fd4c51ae68e0/ouroboros-consensus/src/Ouroboros/Consensus/HardFork/History/Qry.hs#L384-L408) using the `LocalStateQuery` protocol and use that to do the conversion.

**Comment by intricate** [comment] 2020-08-25 14:44
Seems to be a duplicate of #1463

**Comment by AndrewWestberg** [comment] 2020-09-01 18:58
The ekg metrics already spit out all these values, so a work-around for getting tip would be to just get it from ekg instead.

**Comment by disassembler** [comment] 2020-09-15 12:03
Note that #1737 has more details and examples.

**Comment by mrBliss** [comment] 2020-10-30 12:59
The [`GetEpochNo` query](https://github.com/input-output-hk/ouroboros-network/blob/e6261f388f4428251e3f75c8571ab00d14b48682/ouroboros-consensus-shelley/src/Ouroboros/Consensus/Shelley/Ledger/Query.hs#L82) for Shelley was added a while back, which will come in handy to implement this.

**Closed** 2021-03-09 12:35 UTC
Labels: cli revision, enhancement
