### ISSUE TITLE
[BUG] -  Script context validity interval inequality failure

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-node#4172] opened 2022-07-12 13:09 UTC
Unable to test for inequality between validity intervals

**Comment by Jimbo4350** [comment] 2022-07-12 18:28
I asked @james-iohk  to create plutus scripts that do the following:
> It appears to be working as I expect. I've tried these :txInfoValidRange txInfo == txInfoValidRange txInfo

    V1 :white_check_mark:
    V2 :white_check_mark: 

txInfoValidRange txInfo /= txInfoValidRange txInfo

    V1 :white_check_mark:  correctly fails validation
    V2 :white_check_mark:  correctly fails validation

txInfoValidRange txInfo /= always

    V1 :white_check_mark:
    V2 :white_check_mark: 

Not done txInfoValidRange txInfo /= (txInfoValidRange txInfo + someTime) yet, will take me more time

**Comment by Jimbo4350** [comment] 2022-07-15 13:01
I'm good to close this because I've asked @james-iohk to try out some more scenarios but and we can't reproduce it. My main concern was not being able to pass `POSIXTimeRange`s via a redeemer but this has been show to be possible.

**Closed by Jimbo4350** 2022-07-15 13:01 UTC
Labels: bug, priority highest
