### ISSUE TITLE
[BUG] - cardano-cli wraps metadata dictionary in an array

### ISSUE THREAD

**Issue by refi93** [input-output-hk/cardano-node#2479] opened 2021-03-11 17:35 UTC
**Internal/External**
*External*

**Area**
*Other*   cardano-cli

**Summary**
cardano-cli, probably based on the changes introduced in Mary era to the transaction metadata format now wraps the metadata in an array instead of keeping the original dictionary given as-is, even though metadata (now auxiliary data) given as a dictionary is still a valid format and arguably, if there are no scripts, wrapping the metadata into an additional structure is just a waste of space and fees.

https://github.com/input-output-hk/cardano-ledger-specs/blob/38bb3c95ee225445f6b7498e80765dde085665d5/shelley-ma/shelley-ma-test/cddl-files/shelley-ma.cddl#L212

**Steps to reproduce**
1. create a `metadata.json` file containing the following:
```json
{ "1":{ "string":"cardano" } }
```
2. run
```bash
cardano-cli transaction build-raw \
 --mary-era \
 --fee 190000 \
 --tx-in afcf8497561065afe1ca623823508753cc580eb575ac8f1d6cfaa18c3ceeac01#0 \
 --tx-out addr_test1qzq0nckg3ekgzuqg7w5p9mvgnd9ym28qh5grlph8xd2z92sj922xhxkn6twlq2wn4q50q352annk3903tj00h45mgfmsu8d9w5+14620000 \
 --out-file tx.raw \
 --metadata-json-file metadata.json \
 --json-metadata-detailed-schema
```
3. the obtained  tx.raw would be
```json
{
    "type": "TxBodyMary",
    "description": "",
    "cborHex": "82a40081825820afcf8497561065afe1ca623823508753cc580eb575ac8f1d6cfaa18c3ceeac010001818258390080f9e2c88e6c817008f3a812ed889b4a4da8e0bd103f86e7335422aa122a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b42771a00df1560021a0002e6300758207ad89f0443618428fbf1e9024686a20ee284735a993f9e770896c1a0a8c8701482a1016763617264616e6f80"
}
```

4. If you decode it e.g. in https://cbor.me you would see the resulting metadata that makes it into the tx is `[{1: "cardano"}, []]`

**Expected behavior**
the metadata in the serialized tx should be just `{1: "cardano"}`

**System info (please complete the following information):**
- OS: ubuntu
- Version 20.04
- cli version
```
cardano-cli 1.24.2 - linux-x86_64 - ghc-8.10
git rev 400d18092ce604352cf36fe5f105b0d7c78be074
```

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by JaredCorduan** [comment] 2021-03-24 15:36
This is not a bug, but rather a change in the CDDL specification that was introduced at the Allegra hard fork. The transaction now contains `auxiliary_data` in place of `transaction_metadata`. Note that `auxiliary_data` contains the old `transaction_metadata`, and that we did preserve backwards compatibility.

https://github.com/input-output-hk/cardano-ledger-specs/blob/5f63e0f618e1dac27b33ceb33a66f155a465bf68/shelley-ma/shelley-ma-test/cddl-files/shelley-ma.cddl#L212-L217

**Comment by refi93** [comment] 2021-03-24 16:09
I see - at CDDL level the legacy format of auxiliary data as a dictionary is preserved, but cardano-cli wraps the metadata supplied as dict in an array at all times, even if the metadata is supplied as dict, which is as per the CDDL still valid - I think this can break tools that listen on the blockchain and still listen for metadata given as a dict, e.g. Catalyst voting metadata: https://github.com/cardano-foundation/CIPs/blob/master/CIP-0015/CIP-0015.md

**Comment by refi93** [comment] 2021-03-24 16:20
But I get that the "metadata" is now indeed wrapped in the "auxiliary-data" structure and the new version of cli just reflects that - perhaps it would make sense to introduce an "auxiliary-data" flag which would expect the auxiliary data as such and hence would not wrap the supplied auxiliary data json if the structure is a dict.

**Comment by JaredCorduan** [comment] 2021-03-24 16:50
I see, you would like to be able to pass a flag to the CLI which would force the old style (in the case when _only_ metadata is in the auxiliary data).

**Comment by JaredCorduan** [comment] 2021-03-24 17:06
or visa versa :)

**Comment by refi93** [comment] 2021-03-25 00:03
Also, from the CDDL I'm wondering if the [metadata_hash](https://github.com/input-output-hk/cardano-ledger-specs/blob/47c4a8438e2769afb881d78fe2dde6da7c32ea2e/shelley-ma/shelley-ma-test/cddl-files/shelley-ma.cddl#L57) is still the hash of the metadata or actually the whole auxiliary data - as far as I tried it seems to be the latter :thinking:

**Comment by JaredCorduan** [comment] 2021-03-25 02:05
:facepalm: oof, yea, that name is now terribly misleading. you are correct, it is the hash of the auxiliary data. thank you for pointing this out, we'll fix it :)

**Comment by dcoutts** [comment] 2021-03-25 13:52
I think the `--metadata-json-file` should still refer only to the tx metadata, and use the exact same format as before. i.e. I agree with the bug report.

The fact that our tx auxiliary data now consists of both the tx metadata and the other scripts (and later script data) is an internal detail of the structure and not something we should directly reflect in the CLI. The tx metadata is still the tx metadata. It has not changed.

The other aux data just needs its own flags to specify it.

**Comment by dcoutts** [comment] 2021-03-30 02:33
I realise I misread and misunderstood this bug report.

I had thought it was referring to the _input JSON format_ of the tx metadata (which should indeed be stable), but actually the report is about the _output binary format_ of `cardano-cli transaction build-raw`. That format does indeed vary between eras (reflecting the changes in the format of transactions). Specifically, it did indeed change from the Shelley to Allegra eras (adding the aux scripts into the aux data).

Furthermore, the format created by `build-raw` is not fixed by specification, it is simply the intermediate format used by the CLI. It should not be relied upon as a stable interface.

Alternatively, if the issue is really not about the intermediate format of the CLI, but about the final on-chain format of the tx, then it's a reasonable observation that the aux scripts are usually empty and so this is not the most space efficient encoding. That is not something we can change for the Allegra and Mary eras. The binary format is now fixed. There will however be further changes in this area for the Alonzo era, and we will probably move to a map style encoding, like we use for the tx body, which provides more efficient encoding of structures with many optional fields.

**Closed by dcoutts** 2021-03-30 02:33 UTC
Labels: bug

**Comment by refi93** [comment] 2021-03-30 07:53
@dcoutts Thanks for clarifying - does this mean there is currently no way to build with the cardano-cli a transaction with the auxiliary data as a standalone dictionary, i.e. [this format](https://github.com/input-output-hk/cardano-ledger-specs/blob/8e4b2b4043cba3cbbdce0c0ce41ccbeaae529701/shelley-ma/shelley-ma-test/cddl-files/shelley-ma.cddl#L213)?
