### ISSUE TITLE
Trouble installing node and wallet on kubernetes

### ISSUE THREAD

**Issue by gopherine** [input-output-hk/cardano-node#1686] opened 2020-08-13 11:25 UTC
I converted docker-compose.yml using kompose and generated kubernetes configs
when creating pod for the node I get the below error:

`Error: failed to start container "cardano-node": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/nix/store/cx2znvhca6hmy8wr7fx7gbwmy231600r-entry-point/bin/entry-point\": stat /nix/store/cx2znvhca6hmy8wr7fx7gbwmy231600r-entry-point/bin/entry-point: no such file or directory": unknown`

from what I understand that it is unable to find the entrypoint , so I then tried to hardcode entrypoint in 
COMMAND 

However, the above is not resolved

**Comment by kevinhammond** [comment] 2020-08-25 11:55
The issue seems to be with the file systems that are loaded - the docker script presumably has some embedded links to the NIX installation directory that will need to be added to the kubernetes configuration (I would suggest looking for /nix in the docker config, and using that as the basis for the kubernetes one).

@rhyslbw may be able to offer more advice/help

**Comment by vix-io** [comment] 2020-09-15 10:31
hi @gopherine can you still reproduce this?

**Comment by Kidist-Abraham** [comment] 2020-09-24 10:18
I am getting the same error while running cardano-node with AWS ECS fargate service. The problem comes when I use persistent volume (using AWS EFS). It works fine when I use the classic non-persistent volume.

**Comment by johnmathews** [comment] 2021-02-16 14:24
is the solution for this documented anywhere?

**Comment by johnmathews** [comment] 2021-02-16 22:03
@Kidist-Abraham not aws, but minikube.

**Comment by clemenshorn** [comment] 2021-04-12 15:54
I'm getting the same error as @gopherine when I try to run the cardano-node in GKE.

**Comment by npattman** [comment] 2021-05-24 19:57
Hey, I've seen this with docker and windows after a docker node image upgrade. The resolution for me was to delete the node-config mount via the docker command line. 
So, do 
`docker volume ls `
to list your volumes, then you may have one ending node-config, if you have one try 
`docker volume rm {folder_name}_node-config `
(where {folder_name} is the folder that the image is being launched from).
See also here: [https://iohk.zendesk.com/hc/en-us/articles/900001952526](https://iohk.zendesk.com/hc/en-us/articles/900001952526)
HTH, 
Nick

**Comment by Jimbo4350** [comment] 2022-10-27 08:01
Closing this. If this is still relevant please re-open.

**Closed by Jimbo4350** 2022-10-27 08:01 UTC
Labels: bug
