### ISSUE TITLE
CAD-411 Node should print to logs an error if an invalid block is processed

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#466] opened 2020-01-10 17:47 UTC
When an invalid block is processed by ledger rules on the chain, node doesn't print an error to the logs. This should at least print an error, and ideally exit the node when this occurs.

**Comment by dcoutts** [comment] 2020-01-10 17:49
> ideally exit the node when this occurs.

That's what we call failing due to adversarial behaviour. So no we can't do that.

Invalid blocks should indeed have a high logging level so they make it into the logs under normal circumstances.

**Comment by disassembler** [comment] 2020-01-11 01:34
I think what's happening is the exception is getting eaten in `scheduledChainSelection` which is backgrounded, and when it fails the tracer never reports the error up the stack so it never gets logged. Proxy doesn't have this problem as it calls TraceAddBlockEvent directly.

**Comment by dcoutts** [comment] 2020-01-11 12:21
It's not a failure or exception. I'm sure it is traced, but we probably need to adjust the default tracer settings and how we assign the log level so that these come out in the logs by default.

**Comment by dcoutts** [comment] 2020-01-11 21:58
We should certainly fix this. We need the right set of tracers on by default, and should review their log severity levels.

**Comment by oneEdoubleD** [comment] 2020-01-13 16:24
I've just synced `tags/1.3.0` and confirmed it *doesn't* throw an error when it stops syncing after `slot: 625615`. Instead the node repeatedly prints `[cardano.node-metrics:Notice:34]` info every 60 seconds or so. 

On a side note I'm currently syncing `jlotoski/cardano-node-issue-461` and it has already gone past `slot: 625615` indicating the issue has been fixed in that version. I'm re-syncing to check it's sync time at the moment.

**Comment by CodiePP** [comment] 2020-01-31 09:39
@oneEdoubleD is this still an issue?

**Comment by kevinhammond** [comment] 2020-02-25 13:24
Still open or can be closed?

**Comment by oneEdoubleD** [comment] 2020-03-03 09:48
This can be closed.

**Closed by oneEdoubleD** 2020-03-03 09:48 UTC
Labels: byron
