### ISSUE TITLE
[BUG] - docker run - cardano-node: Network.Socket.bind: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by laplasz** [input-output-hk/cardano-node#2673] opened 2021-05-04 12:47 UTC
**Internal/External**
*External*   otherwise.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
When running the command from the official documentation
`docker run -v /data -e NETWORK=mainnet inputoutput/cardano-node`
getting the following error:
cardano-node: Network.Socket.bind: does not exist (No such file or directory)

**Steps to reproduce**
1. docker run -v /data -e NETWORK=mainnet inputoutput/cardano-node

**Expected behavior**
docker running without error
**System info (please complete the following information):**
- OS: docker latest

**Additional context**
however when I adding an anonymous volume to node socket file i solves the issue:
`docker run -v /ipc -v /data -e NETWORK=mainnet inputoutput/cardano-node`

also would be great to use named volumes instead of anonymous - and run the container with host user to have proper permissions on the generated files stored on the volumes:
docker run --rm -v /home/user/ipc:/ipc -v /home/user/data:/data -e NETWORK=mainnet -u $(id -u):$(id -g) inputoutput/cardano-node

My question - is it possible to extend the documentation - if yes where it is stored on the github
Thanks!

**Comment by tdiesler** [comment] 2021-05-18 14:48
This is a duplicate of #2340, which is scheduled to get fixed in PR #2608

**Comment by Jimbo4350** [comment] 2022-10-27 08:19
Closing this. If this is still relevant please reopen.

**Closed by Jimbo4350** 2022-10-27 08:19 UTC
Labels: bug
